### PR TITLE
[compiler-v2][trivial] run lambda lifter for target modules and their transitive closures

### LINKED ISSUE #16363: [Bug] Compilation error when using lambdas
# 🐛 Bug

Compilation fails when a nested lambda is compiled (see example below)

## To reproduce

Use the following transactional test
```rust
//# publish
module 0x42::foo {
    struct Foo<T: store> has key {
        f: |()|vector<T>,
    }

    public fun make_foo<T: store>(account: &signer) {
        let f = || std::vector::empty<T>();
        move_to(account, Foo { f })
    }
}

//# publish
module 0x42::test {
    fun run<T: store>(account: &signer) {
        let f = |a| 0x42::foo::make_foo<T>(a);
        f(account);
    }
}
```

**Stack trace/error message**
```
processed 2 tasks

task 1 'publish'. lines 13-19:
Error: compilation errors:
 bug: unexpected lambda, expected to be eliminated by lambda lifting
  ┌─ TEMPFILE:7:17
  │
7 │         let f = || std::vector::empty<T>();
  │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR sets lambda lifter to be run against all modules instead of target modules to match behavior in bytecode generator which generates stackless bytecode for functions that are in non-target modules but used by functions in the target modules.

close #16363 

## How Has This Been Tested?

1) existing tests;
2) a new test case.

## Key Areas to Review

Whether we want to run lambda lifter on all modules?

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs [hunk 1]
```diff
@@ -79,12 +79,7 @@ pub struct LambdaLiftingOptions {
 pub fn lift_lambdas(options: LambdaLiftingOptions, env: &mut GlobalEnv) {
     // Go over target modules one by one. Since in each iteration
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:80]:
```suggestion
    // Go over all modules one by one. Since in each iteration
```

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs [hunk 2]
```diff
@@ -79,12 +79,7 @@ pub struct LambdaLiftingOptions {
...
     // we need to mutate the module, iterate over a vector of plain ids.
-    for module_id in env
-        .get_target_modules()
-        .into_iter()
-        .map(|me| me.get_id())
-        .collect_vec()
-    {
+    for module_id in env.get_modules().map(|me| me.get_id()).collect_vec() {
```
Comment (georgemitenkov) [inline third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:82]: nit: the comment still says "target modules"

**Review by vineethk — APPROVED** [review]
Btw, what is the reason we have to generate stackless bytecode for all modules and not just targets?

**Review by georgemitenkov — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs (hunk 2 above)
Comment (georgemitenkov) [reply third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:82]: Ah, already spotted by @vineethk 👍

**Comment by rahxephon89** [comment]
> Btw, what is the reason we have to generate stackless bytecode for all modules and not just targets?

When generating bytecode for each function, code of all used functions will also be generated which may include ones that are not in the target module.

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs (hunk 2 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:82]: I think we should do what is said in the PR description, do it like the bytecode generator, and actually go over the target modules _and only_ the non-target modules which are transitively used by all those modules. The algorithm is [here](https://github.com/aptos-labs/aptos-core/blob/8d630a3f06c84dee350bf4d32f36ba957a1e2ab3/third_party/move/move-compiler-v2/src/lib.rs#L252). You can factor it into `model.rs`, as a function of`GlobalEnv`, like `get_target_modules_transitive_closure`.

**Comment by wrwg** [comment]
> > Btw, what is the reason we have to generate stackless bytecode for all modules and not just targets?
> 
> When generating bytecode for each function, code of all used functions will also be generated which may include ones that are not in the target module. Added more context in the PR description.

The actual reason is some weiredness which Brian worked on for a while. Sometimes the build system expects to also generate bytecode for non-target modules. We still do not want to warn or similar in those non-targets. This lead to the `is_target_module` and `is_primary_target` predicates. I'm not fully sure whether I understand the current state, its somehow messed up.

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs (hunk 2 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:82]: PS. You don't need the by-function treatment like in the code, but can just use `get_used_modules` to compute the closure.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs]: done
