### PR TITLE
fix abigen testsuite to notice missing or extra output files

### LINKED ISSUE #13423: [Bug][move-compiler] Broken abigen test: Should move-prover abigen yield an error or silently do nothing for a Move script?
# 🐛 Bug

The following test passes:
```
cargo test -p move-abigen --testsuite -- some_script
```
but there is actually no .abi file generated, although there is an "expected" abi file
```
third_party/move/move-prover/move-abigen/tests/sources/some_script.abi
```
You can see this by deleting that file and running
```
UB=1 cargo test -p move-abigen --testsuite -- some_script
```

The testsuite here doesn't check for missing .abi files, just that those generated match the ones present.
The testsuite should also be fixed to check whether the set of .abi files generated is all of those expected.

In any case, either the abigen code needs to be fixed for this case or the some_script.abi file deleted.

### PR DESCRIPTION
**Pull request by brmataptos**
## Description

Fixes docgen and abigen to not add a spurious `0x1::` address on script files.

Fixes #13423.
Modifies test to be more clear what Abigen is outputting and whether it is what was expected.

Fixes `run_spec_checker` to mark scripts in a way which is compatible with other move_model code.

### CODE REVIEW

File: third_party/move/move-prover/move-abigen/tests/testsuite.rs [hunk 1]
```diff
@@ -70,7 +76,16 @@ fn test_abigen(path: &Path, mut options: Options, suffix: &str) -> anyhow::Resul
...
+                expected_apis.remove(&baseline_file_name);
+            }
+            let empty_contents = "".to_string();
+            for baseline_file_name in expected_apis.iter() {
+                verify_or_update_baseline(Path::new(baseline_file_name), &empty_contents)?;
             }
+            let buffer = error_writer.into_inner();
+            let contents = String::from_utf8_lossy(&buffer);
+            let baseline_path = path.with_extension(suffix);
+            verify_or_update_baseline(&baseline_path, &contents)?;
```
Comment (rahxephon89) [inline third_party/move/move-prover/move-abigen/tests/testsuite.rs:88]: Is this used to get the warnings/errors from `run_move_prover`?

**Review by rahxephon89 — APPROVED** [review]

**Review by wrwg — APPROVED** [review]
