### PR TITLE
[compiler-v2] Fail on warnings option

### LINKED ISSUE #13198: Warnings as errors
Please give the option to make warnings as errors, especially for framework builds. It ensures that we don't let less than proper code hit our framework and disrupt our builders' experiences.

### PR DESCRIPTION
**Pull request by vineethk**
## Description

Closes #13198.

This PR adds a new user provided option to the compiler: `--fail-on-warning`.

When running, e.g., `aptos move compile --fail-on-warning`, if there are one or more warnings produced by the compiler, then the compilation fails.

Note: [minor] we also update the move formatter target version to the latest available formatter version.

## How Has This Been Tested?
- Existing tests.
- Manually tested the CLI option.

## Type of Change
- [x] New feature

## Which Components or Systems Does This Change Impact?
- [x] Aptos CLI/SDK
- [x] Move Compiler

### CODE REVIEW

**Comment by vineethk** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16016?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#16016** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16016?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16016?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#16015** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16015?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#16010** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16010?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15937** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15937?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15933** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15933?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15930** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15930?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15927** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15927?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by rahxephon89 — APPROVED** [review]

File: aptos-move/framework/src/built_package.rs [hunk 1]
```diff
@@ -309,7 +309,10 @@ impl BuiltPackage {
             }
 
             if let Some(model_options) = model.get_extension::<Options>() {
-                if model_options.experiment_on(Experiment::STOP_AFTER_EXTENDED_CHECKS) {
+                if model_options.experiment_on(Experiment::FAIL_ON_WARNING) && model.has_warnings()
+                {
+                    bail!("found warning(s), and `--fail-on-warning` is set")
```
Comment (wrwg) [inline aptos-move/framework/src/built_package.rs:314]: This does it for now!

**Review by wrwg — APPROVED** [review]
