### PR TITLE
[compiler v2] Relaxing copy restrictions on `&mut`

### LINKED ISSUE #11117: [Bug][Compiler-v2] implicit copy of mutable reference
# 🐛 Bug

When compiling the `smart_table.move`, the following code snippet:

```
        let old_bucket = table_with_length::borrow_mut(&mut table.buckets, to_split);
        // partition the bucket, [0..p) stays in old bucket, [p..len) goes to new bucket
        let p = vector::partition(old_bucket, |e| {
            let entry: &Entry<K, V> = e; // Explicit type to satisfy compiler
            bucket_index(table.level, table.num_buckets, entry.hash) != new_bucket_index
        });
        let new_bucket = vector::trim_reverse(old_bucket, p);
```

leads the error: 

```
error: implicit copy of mutable reference in local `old_bucket` which is used later
    ┌─ /Users/tengzhang/aptos-core/aptos-move/framework/aptos-stdlib/../move-stdlib/sources/vector.move:473:5
    │  
473 │ ╭     public inline fun partition<Element>(
474 │ │         v: &mut vector<Element>,
475 │ │         pred: |&Element|bool
476 │ │     ): u64 {
    · │
492 │ │         p
493 │ │     }
    │ ╰─────^ implicitly copied here
    │  
    ┌─ /Users/tengzhang/aptos-core/aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move:199:26
    │
199 │         let new_bucket = vector::trim_reverse(old_bucket, p);
    │                          ----------------------------------- used here

```

Not sure whether it is a bug of reference checking or inline function. cc @wrwg @brianrmurphy

### PR DESCRIPTION
**Pull request by wrwg**
Closes #11117.

This relaxes the restriction on copying of `&mut`. A copy of a `&mut` is now handled similar as a move, by creating a skip edge to the source. While that edge exists, the original source cannot be used, according to the existing borrowing rules.

Thus in a case like this:

```
let r = &mut <<some>>;
{
  let x = r;
  mutate(x);
}
mutate(r);
```

The 'copy' of x to r is valid.  As long as the inner `x` lives, the outer `r` cannot be used. When `x` goes out of scope, `r` can be used again. Thus, while copies of mut-ref values is now possible, only one 'active' can exist at a time. Note that this also matches v1 semantics. At runtime, we do not really need to move the reference from `r` to `x`, we can just copy its representation. The fact that `&mut` is now copyable is also very helpful for copy propagation.

This PR also does the following:

- fixes a bug in reference-safety, resulting in more errors. v1 does not have those errors, but they appear justified. This is another gray zone in borrow semantics, so I think those errors should stay until we have counter examples in real code.
- enables reference-safety (it wasn't on in regular execution, only in tests)
- activates experiments and adds a first one `--experiment=no-safety` (or `MOVE_COMPILER_EXP=no-safety`) which allows to skip safety checks (currently visibility and reference safety). The env var should work if called via the aptos CLI or unit test framework.

### CODE REVIEW

**Review by brmataptos — CHANGES_REQUESTED** [review]
Still looking at the code examples, but see important comment first.

File: third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs [hunk 1]
```diff
@@ -305,37 +305,14 @@ impl<'a> CopyTransformation<'a> {
...
-                false
-            } else {
-                // TODO(#10723): insert ability check here
-                true
-            }
-        } else {
-            false
-        }
+        // TODO(#10723): insert ability check here
+        // Notice we do allow copy of &mut. Those copies are checked for validness in
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs]: Done

File: third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs [hunk 2]
```diff
@@ -305,37 +305,14 @@ impl<'a> CopyTransformation<'a> {
...
-                            target.get_local_name_for_error_message(temp)
-                        ),
-                        "implicitly copied here",
-                        self.make_hints_from_usage(info),
-                    );
-                }
-                // Don't copy &mut
-                false
-            } else {
-                // TODO(#10723): insert ability check here
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs:333]: This what the TODO already says on line 312: "// TODO(#10723): insert ability check here"

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/mutate_field_invalid.exp [hunk 3]
```diff
@@ -1,22 +1,49 @@
 
 Diagnostics:
-error: cannot write to reference in local `s` which is still borrowed
+error: cannot copy mutable reference in local `s` which is still borrowed
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/mutate_field_invalid.exp:3]: This message is not right.  local s is not being copied, it's being overwritten.  *Please* file an issue to  address this and/or merge it with the following error message.

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/mutate_full.exp [hunk 4]
```diff
@@ -1,10 +0,0 @@
-
-Diagnostics:
-error: implicit copy of mutable reference in local `x` which is used later
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/mutate_full.exp:3]: Being able to remove this error is nice, but I fear it may make it hard for users to reason about why it works.  Can you state a simple rule?  Will it still work if you had
```
     11         let x = &mut 0;
     12         let f = x; // error in v2 because of copy
     13         a = *f;
     14         *x = 0;
     15         b = *f;
```
Why not?  (Not for me, for a user.)

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/mutate_full.exp (hunk 4 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/mutate_full.exp:3]: Can you please check out the PR description? It contains the reasoning why it works. The above is still an error because even though you can copy mutref, while this copy is alive, the source cannot be used, as described in the PR header.  Here `x` is used before `f` goes out of scope.
