### PR TITLE
use ast::Value equivalence, not enum equality, to do constant folding of constants

### LINKED ISSUE #12516: [Bug][move-compiler-v2] AST Simplifier causes a test failure with V2 on aptos stdlibs
# 🐛 Bug

```
Test failures:

Failures in 0x1::ristretto255:

┌── test_scalar_from_canonical_bytes ──────
│ Test was not expected to error, but it aborted with code 1 originating in the module 0000000000000000000000000000000000000000000000000000000000000001::ristretto255 rooted here
└──────────────────

Test result: FAILED. Total tests: 875; passed: 874; failed: 1
test move_token_unit_tests ... FAILED

failures:

failures:
    move_token_unit_tests
```

### PR DESCRIPTION
**Pull request by brmataptos**
## Description

Fixes issue #12516 by using ast::Value equivalence
(newly exposed through function `Value::equivalent()`),
 rather than struct
equality, when constant-folding equality operations.
(`Value::ByteArray(..)` and `Value::AddressArray(..)` values can
each also be represented by `Value::Vector(..)` instead).

This fixes a failure that shows up in `0x1::ristretto:255`
test case `test_scalar_from_canonical_bytes`.

Fixes #12516.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Other (specify)
    V2 compiler
## How Has This Been Tested?
Included thorough unit test for new function `Value::equivalent`,
and a targeted test case `constant_folding_ristretto.move` for
comparison with V1 and V2 without simplification.

Existing V2 CI tests should show the original problem is fixed.

## Key Areas to Review
Consider redundancy and ambiguity of the AST representation, perhaps there are more cases.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by vineethk — APPROVED** [review]
I have added a comment to double check a scenario - it may or may not be an issue. If you think it is safe, then this is good to go.

File: third_party/move/move-model/src/ast.rs [hunk 1]
```diff
@@ -2034,12 +2035,58 @@ pub enum Value {
...
+                    } else {
+                        false
+                    }
+                },
+                (Value::Vector(x), Value::AddressArray(y))
+                | (Value::AddressArray(y), Value::Vector(x)) => {
+                    if x.len() == y.len() {
+                        iter::zip(x, y).all(|(value, addr)| {
+                            if let Value::Address(addr1) = value {
+                                addr1 == addr
```
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-model/src/ast.rs:2073]: Good idea.  I'll change it to make that case incomparable and not constant.

**Comment by brmataptos** [comment]
I changed `ast::Value::equivalent` to a partial function (returns `Option<bool>`) to allow constant folding to avoid folding cases where symbolic addresses make the value of the test unknown.  Not sure if those can actually arise, but it seems good to be safe.  I don't know how to test that case in the constant folder, but I have very very thorough tests of `ast::Value::equivalent` that helped make it correct, if a bit verbose.

PTAL

File: third_party/move/move-model/src/ast.rs [hunk 2]
```diff
@@ -2034,12 +2035,109 @@ pub enum Value {
...
     Vector(Vec<Value>),
     Tuple(Vec<Value>),
 }
 
+impl Value {
+    /// Implement an equality relation on values which identifies representations which
+    /// implement the same runtime value, assuming that types match.
+    ///
+    /// If `Address` values are symbolic and differ, then no answer can be given.
+    pub fn equivalent(&self, other: &Value) -> Option<bool> {
```
Comment (vineethk) [inline third_party/move/move-model/src/ast.rs:2052]: Appreciate such cleanly written code, makes it easy to reason about.

File: third_party/move/move-model/src/ast.rs [hunk 3]
```diff
@@ -2993,3 +3091,183 @@ impl<'a> fmt::Display for EnvDisplay<'a, Spec> {
         Ok(())
     }
 }
+
+#[test]
```
Comment (vineethk) [inline third_party/move/move-model/src/ast.rs:3095]: nit: it is more idiomatic (and helpful in the presence of further changes and maintainance) to wrap all this with:
```
#[cfg(test)]
mod tests {
    // code to be wrapped
}
```

Source: https://doc.rust-lang.org/book/ch11-01-writing-tests.html#the-anatomy-of-a-test-function

**Review by vineethk — APPROVED** [review]

File: third_party/move/move-model/src/ast.rs (hunk 3 above)
Comment (brmataptos) [reply third_party/move/move-model/src/ast.rs]: I found I had to add several `use` statements as well, then I read that page and saw an example using `use super::*;`, but after I pushed my new code.  I suppose explicit `use` statements provides guidance to users of the code.

**Review by wrwg — APPROVED** [review]

**Comment by brmataptos** [comment]
Symbolic Address inequality does not imply that Addresses are really different at runtime.
