### PR TITLE
[compiler][trivial] fix type instantiation for receiver style syntax

### LINKED ISSUE #16057: [Bug][Compiler-v2] In some cases where unknown type is not inferred
# 🐛 Bug

To report a security issue, please email security@aptoslabs.com.

## To reproduce

**Code snippet to reproduce**
```move
    #[test, expected_failure(abort_code = EINVALID_BUCKET_INDEX)]
    fun test_keys_invalid_bucket_index() {
        let table = new();
        table.add(1, 0);
        let num_buckets = table.num_buckets;
        // This line causes the error
        table.keys_paginated(num_buckets + 1, 0, 1);
        table.destroy();
    }
```
https://github.com/gregnazario/aptos-core/commit/81bbe425e396c022c8f230c62a879af63912c6d2#diff-9fdb0320ac6198d718b71cffd1c066907b3f160d04d48cd5cd12e35ed589b9a1R717-R725

**Stack trace/error message**
```
 aptos move test                                       λ:aptos-tokens-move-2  [    ]
INCLUDING DEPENDENCY MoveStdlib
BUILDING AptosStdlib
bug: unexpected type: _
    ┌─ /Users/greg/git/core-2/aptos-core/aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move:718:9
    │
718 │     fun test_keys_invalid_bucket_index() {
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


```

## Expected Behavior

Would be great to say what type is missing.  In this case, this code can be fixed with a simple typing in advance:

```move
    #[test, expected_failure(abort_code = EINVALID_BUCKET_INDEX)]
    fun test_keys_invalid_bucket_index() {
        let table = new<u64, u64>();
        table.add(1, 0);
        let num_buckets = table.num_buckets;
        // TODO: Note that, changing this line to receiver syntax, leads to `unexpected type: _`
        table.keys_paginated(num_buckets + 1, 0, 1);
        table.destroy();
    }
```
## System information

**Please complete the following information:**
- Aptos Core Version
- Rust Version
- Computer OS

### LINKED ISSUE #16091: [Bug] Smart Table: Error When Nesting Inline for_each_ref
# 🐛 Bug

 When using the smart table's inline for_each_ref function, an error occurs when two levels of smart table for_each_ref are used.

## To reproduce

**Code snippet to reproduce**
```rust
module 0xdead::test {
    use std::string::String;
    use aptos_std::smart_table::SmartTable;

    struct T has key {
        t: SmartTable<u64, SmartTable<u64, String>>
    }
    #[view]
    public fun test(): vector<String> acquires T {
        let vec = vector[];
        let table = &borrow_global<T>(@aptos_framework).t;
        table.for_each_ref(|_k,v|{
            v.for_each_ref(|_v_k, v_v|{
                vec.push_back(
                    *v_v
                )
            })
        });
        vec
    }
}
```

**Stack trace/error message**
```
 error: unable to infer instantiation of type `&_` (consider providing type arguments or annotating the type)
   ┌─ C:\Users\Ellen\Desktop\aptos-aave-v3\sources\test.move:13:29
   │
13 │             v.for_each_ref(|_v_k, v_v|{
   │                             ^^^^

{
  "Error": "Move compilation failed: exiting with checking errors"
}

```

## System information

**Please complete the following information:**
- Aptos Core Version: aptos cli v6.2.0
- Rust Version
- Computer OS: windows

## Additional context

```
module 0xdead::test {
    use std::string::String;
    use aptos_std::smart_table::SmartTable;

    struct T has key {
        t: SmartTable<u64, SmartTable<u64, String>>
    }
    #[view]
    public fun test(): vector<String> acquires T {
        let vec = vector[];
        let table = &borrow_global<T>(@aptos_framework).t;
        table.for_each_ref(|_k: &u64,v|{
            v.for_each_ref(|_v_k: &u64 , v_v|{
                vec.push_back(
                    *v_v
                )
            })
        });
        vec
    }
}
```

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR adds the logic to run `finalize_types` before and after `post_process_body` and only generates error in the second time so that type can be instantiated in receiver style syntax before finalizing types.

Close #16091 
Close #16057

## How Has This Been Tested?

1) existing tests;
2) added a new test.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by vineethk — APPROVED** [review]

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 1]
```diff
@@ -1573,8 +1573,8 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
             }
             let access_specifiers = et.translate_access_specifiers(&def.access_specifiers);
             let result = et.translate_seq(&loc, seq, &result_type, &ErrorMessageContext::Return);
-            et.finalize_types();
             let translated = et.post_process_body(result.into_exp());
+            et.finalize_types();
```
Comment (wrwg) [inline third_party/move/move-model/src/builder/module_builder.rs:1577]: This is not looking right. Finalization has to happen before post processing since this needs to have the ground types, it is not place by accident in this order. Its also happening inside of post process for some special cases [like here](https://github.com/aptos-labs/aptos-core/blob/a2db17a9fac269c0a92b28d6cc6fe56433628be3/third_party/move/move-model/src/builder/exp_builder.rs#L2233). Please look closer what is wrong here to find the right fix.

Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: The issue is that `finalize_types` generated the error before running `post_process_body`. I updated the code so that when `finalize_types` is run before `post_process_body`, error will not be generated.

File: third_party/move/move-compiler-v2/tests/checking/receiver/call_errors.move [hunk 2]
```diff
@@ -24,6 +24,5 @@ module 0x42::m {
         s.receiver_ref_mut(1u8);
         s.receiver_ref_mut::<u8>(1);
         s.receiver_ref_mut::<u8, u8>(1);
-        s.receiver_needs_type_args(x)
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/tests/checking/receiver/call_errors.move:27]: Add this to a separate test case because this error will be hidden by previous ones.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/receiver/call_errors.move:27]: This is caused by removing adhoc `finalize_type` in `post_process_receiver_call`.

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 3]
```diff
@@ -1573,8 +1573,9 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
             }
             let access_specifiers = et.translate_access_specifiers(&def.access_specifiers);
             let result = et.translate_seq(&loc, seq, &result_type, &ErrorMessageContext::Return);
-            et.finalize_types();
+            et.finalize_types(false);
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:1437]: done

[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/builder/module_builder.rs:1437]: Could you add the discussed `TODO: try to avoid running finalize twice`?

**Review by wrwg — APPROVED** [review]
