### PR TITLE
[compiler-v2] Fixing bug in stack balancing of file-format generator

### LINKED ISSUE #13912: [Bug][move-compiler-v2] Mutable borrow with copy on RHS of equality check
# 🐛 Bug
Compiler V1 can compile the following program but compiler V2 will give an error.

## To reproduce

**Code snippet to reproduce**
```move
module 0xCAFE::Module0 {
    public fun function2(var4: u8): bool {
        (&mut (var4) != &mut (copy var4))
    }
}
```

**Stack trace/error message**
V2 gives:
```
error: cannot copy local `var4` which is still mutably borrowed
  ┌─ ~/debug_package/sources/repro.move:3:30
  │
3 │         (&mut (var4) != &mut (copy var4))
  │         ---------------------^^^^^^^^^^^-
  │         ││                   │
  │         ││                   copied here
  │         │previous mutable local borrow
  │         │used by freeze
  │         conflicting reference used here
```

### PR DESCRIPTION
**Pull request by wrwg**
## Description

Fixes #13912

The `balance_stack_end_of_block` function in function_generator.rs was both dumb and incorrect. It first pushed the argument which is needed for a branch on the stack, then checked if the stack needs flush, and then flushed the value just pushed right away, leading to stupid code like

```

CopyLoc(temp)
StLoc(temp)
CopyLoc(temp)
BrFalse
```

This code is also wrong if `temp` is borrowed since `StLoc(temp)` is not allowed in this case, which was the bytecode verification failure hit by the bug.

The bug was masked if optimizations are on, because then the subsequent st/copy is eliminated.

The fix simpplifies the stack balance function to ensure `temp` is not flushed unnecessarily.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Existing tests have been migrated from reference-safety to file-format-generator, and a new test has been added, reflecting a regression first caused by the fix.

### CODE REVIEW

**Comment by wrwg** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14310?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14310** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14310?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#14306** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wrwg and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 1]
```diff
@@ -341,22 +341,26 @@ impl<'a> FunctionGenerator<'a> {
     }
 
     /// Balance the stack such that it exactly contains the `result` temps and nothing else. This
-    /// is used for instructions like `return` or `abort` which terminate a block und must leave
-    /// the stack empty at end.
+    /// is used for instructions like `brancg`, `return` or `abort` which terminate a block
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:344]:
```suggestion
    /// is used for instructions like `branch`, `return` or `abort` which terminate a block
```

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 2]
```diff
@@ -341,22 +341,26 @@ impl<'a> FunctionGenerator<'a> {
...
+    /// und must leave the stack empty at end.
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:345]:
```suggestion
    /// and must leave the stack empty at end.
```

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 3]
```diff
@@ -341,22 +341,26 @@ impl<'a> FunctionGenerator<'a> {
...
-            // Unfortunately, there is more on the stack than needed.
-            // Need to flush and push again so the stack is empty after return.
+        // If the stack contains already exactly the result and none of the temps is used after,
+        // nothing to do
+        let stack_ready = self.stack == result
+            && self
+                .stack
+                .iter()
+                .enumerate()
+                .all(|(pos, temp)| !ctx.is_alive_after(*temp, &result[pos + 1..], false));
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:359]: We already know that `stack == result` here, do we need to include the `remaining_args` here?

If the stack already had the copies of a value, this would make us unnecessarily flush them out and copy back again?

Comment (wrwg) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:359]: Lets better not rely on the invariant that all temps on the stack are distinct. Likely it is true, but I did not want to risk anything here, because and this check is safe if temps are distinct.

If the stack had already true (independent) copies, the temps on it would not be alive-after, so I don't think we flush to much here. I definitely have a test case which shows we need to do the alive-after check. There can be temps on the stack which are not saved yet an are used after, those stem from push_result.

Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:359]: Sorry, let me clarify: I was suggesting that we would be okay passing an empty slice to the `remaining_args` of `ctx.is_alive_after`, because we already know that `stack == result`.

If any of the stack values are used after (regardless of whether there are repeated values), then `stack_ready` would still be false.

If none of the stack values are used after, but there were some repeated values, then the stack is still ready - we don't have to do a flush in this particular case (but the current code does it).

**Review by vineethk — APPROVED** [review]
Have a comment on missing out on a potential optimization, but LGTM otherwise.

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 3 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:359]: > If none of the stack values are used after, but there were some repeated values, then the stack is still ready - we don't have to do a flush in this particular case (but the current code does it).

Ok, this may be true... there are two scenarios how temps can end on the abstract stack

- We pushed them as args, in which case we already emitted a copy if needed. In this case we definitely have duplicates on the stack, which a previous bug fix dealt with. But those are copies.
- We pushed them as results of function calls. In this case, there should be no duplicates.

Going for the empty slice then.
