### PR TITLE
[Compiler-v2] Fix `check_variant`

### LINKED ISSUE #14950: [Bug][Compiler-V2] `variants not allowed in this context` is generated when the struct has the same name as the module where it is defined
# 🐛 Bug

When compiling the following code using V2:

```
module 0x42::M {
    struct M has drop {
        v: u64
    }
}

module 0x42::M1 {
    use 0x42::M::{Self, M};

    fun test(_m: M::M): u64 {
        3
    }
}
```

The following error is generated:

```
error: variants not allowed in this context
   ┌─ tests/sources/functional/schemas_ok.move:15:18
   │
15 │     fun test(_m: M::M): u64 {
   │                  ^^^^
```

While V1 can compile the code.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

In the expansion [phase](https://github.com/aptos-labs/aptos-core/blob/55e368cbf9314abd824a4c22b6cbbd508a7472bd/third_party/move/move-compiler/src/expansion/translate.rs#L2308), module access with the form `A::B` is translated into access of the variant `B` of enum `A`  as `ModuleAccess(M1, M2, Some(B))` when `A` has an alias `M1::M2` where `M1` is the name of the module where `A` is defined. 

However, when `A` is both the name of a struct/enum type and the name of a module (which means `M1` == `A`) and `B` is a constant, a struct/enum type, then `A::B` needs to be interpreted as `ModuleAccess(M1, B, None)`.  This PR refactors the implementation of `check_variant(maccess: ModuleAccess)-> bool` in the `module_builder` such that, instead of directly returning false when `maccess` takes the form `ModuleAccess(M1, M2, Some(B))`, it will return  `ModuleAccess(M1, B, None)` if `M1::B` is a constant, schema or a struct. 

Close #14950 

## How Has This Been Tested?

1) existing tests pass;
2) add a new test case.

## Key Areas to Review

Corner cases such as when a type has an alias with the same name as the module in which it defines.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rahxephon89** [comment]
* **#14952** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14952?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rahxephon89 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 1]
```diff
@@ -262,15 +265,46 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+            } else {
+                self.parent.env.error(
+                    &self.parent.to_loc(&maccess.loc),
+                    "variants not allowed in this context",
+                );
+                (false, maccess.clone())
+            }
         } else {
-            true
+            (true, maccess.clone())
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/module_builder.rs:307]: Under what condition would this case happen?  Do we have tests that cover this case?

Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:307]: It covers all other cases where maccess cannot be interpreted as a variant so I don't think we need new test cases here.

**Review by wrwg — APPROVED** [review]

**Review by brmataptos — APPROVED** [review]
