### PR TITLE
[compiler-v2] New reference safety analysis

### LINKED ISSUE #12817: [Bug][compiler-v2] Bytecode verification error when multiple mutable references are used in a particular order
# 🐛 Bug

Consider the following program:
```
    public fun test1(): u64 {
        let x = 0;
        let r1 = &mut x;
        let r2 = &mut x;
        *r1 + *r2
    }

    public fun test2(): u64 {
        let x = 0;
        let r1 = &mut x;
        let r2 = &mut x;
        *r2 + *r1 // <- changed order here
    }
```

v1 and v2 compiler and run `test1` without any issues, but on `test2`:
- v1 gives a compiler error
- v2 does not give a normal compiler error but gives a "bytecode verification failure bug" error due to `READREF_EXISTS_MUTABLE_BORROW_ERROR`. We should instead provide a proper compiler error.

There are similar variations of the same problem:
```
    public fun test3() {
        let x = 0;
        let r1 = &mut x;
        let r2 = &mut x;
        let _ = *r1;
        let _ = *r2;
    }

    public fun test4() {
        let x = 0;
        let r1 = &mut x;
        let r2 = &mut x;
        let _ = *r2; // <- order changed
        let _ = *r1; // <-
    }
```

v1 and v2 compiler and run `test3` without any issues, but on `test4`:
- v1 gives a compiler error
- v2 does not give a normal compiler error but gives a "bytecode verification failure bug" error due to `READREF_EXISTS_MUTABLE_BORROW_ERROR`.

### LINKED ISSUE #13912: [Bug][move-compiler-v2] Mutable borrow with copy on RHS of equality check
# 🐛 Bug
Compiler V1 can compile the following program but compiler V2 will give an error.

## To reproduce

**Code snippet to reproduce**
```move
module 0xCAFE::Module0 {
    public fun function2(var4: u8): bool {
        (&mut (var4) != &mut (copy var4))
    }
}
```

**Stack trace/error message**
V2 gives:
```
error: cannot copy local `var4` which is still mutably borrowed
  ┌─ ~/debug_package/sources/repro.move:3:30
  │
3 │         (&mut (var4) != &mut (copy var4))
  │         ---------------------^^^^^^^^^^^-
  │         ││                   │
  │         ││                   copied here
  │         │previous mutable local borrow
  │         │used by freeze
  │         conflicting reference used here
```

### LINKED ISSUE #13976: [Bug] 2 mutable borrows in nested calls leads to `CALL_BORROWED_MUTABLE_REFERENCE_ERROR` on v2 only
# 🐛 Bug

```
    fun lifted_lambda(ap: &mut u64, z: u64): u64 {
        *ap = *ap + 1;
        z * *ap
    }

    entry fun foo2(): u64 {
        let a = 2;
        let z = 3;
        lifted_lambda(&mut a,
            lifted_lambda(&mut a, z))
    }
```
leads to a VM problem only on V2, not V1.

### PR DESCRIPTION
**Pull request by wrwg**
## Description

This implementation replicates the existing bytecode verifier and compiler v1 implementation, using the same shared 'borrow graph' logic. For documentation of the borrow graph, see `move_borrow_graph::graph::BorrowGraph`. For comparison with the bytecode verifier, see `move-bytecode-verifier/src/reference_safety/abstract_state.rs`.
    
The new analysis is the default. The old is still there and can be activated with `Experiment::REFERENCE_SAFETY_V3 = false`.
    
Fixes #12817
Fixes #13912
Fixes #13976

Also many more test cases succeed now which failed old reference analysis but pass bytecode verifier.
    
Some main instance of remaining bugs is related to bytecode verification failures without optimization enabled, and a type safety bug (see #14274).
    

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

IMPORTANT. For reading the test diff consider the following:
    
- The `.exp` files for the old reference analysis have been renamed from `foo.exp` to `foo.old.exp`. Those appear as new files but it has been manually verified that their content the same. It is safe to ignore those files for review.
- The new analysis uses the `.exp` and `.no-opt.exp` so we have a comparison point old against new.

### CODE REVIEW

**Comment by wrwg** [comment]
* **#14276** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14276?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wrwg and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rahxephon89 — APPROVED** [review]
The code looks good to me. Could you rebase and check whether the test case `third_party/move/move-compiler-v2/tests/reference-safety/immu_borrow_bug.move` can be resolved by this PR? Similar issues where V2 generates compilation error while V1 does not are #12834, #12836, #12849, #12889, #13149, #13489 and #13608.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs [hunk 1]
```diff
@@ -0,0 +1,1283 @@
...
+//!
+//! This implementation replicates the existing bytecode verifier and compiler v1
+//! implementation, using the same shared 'borrow graph' logic. For documentation
+//! of the borrow graph, see `move_borrow_graph::graph::BorrowGraph`. For
+//! comparison with the bytecode verifier, see
+//! `move-bytecode-verifier/src/reference_safety/abstract_state.rs`.
+//!
+//! A main difference between the bytecode verifier and this implementation
+//! is that we are dealing with a register machine whereas the bytecode
+//! verifier with a stack machine. Therefor we need to move or copy
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs:14]: Done

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs [hunk 2]
```diff
@@ -0,0 +1,1283 @@
...
+        }
+        self.state.release(id)
+    }
+
+    fn branch(&mut self, cond: TempIndex) {
+        let _value = self.move_or_copy(cond, &[], &[]);
+    }
+
+    fn comparison(&mut self, dest: TempIndex, srcs: &[TempIndex]) {
+        // Difference in comparison to regular callr is that we allow mutable references
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs:1021]: Done

**Review by brmataptos — APPROVED** [review]
Generally seems ok.  I tried to read through and compare everything to previous compiler pass and move-bytecode-verifier reference_safety analysis, and can't find any major issues.  I've pointed out a few nits, but if they pertain to copied code then maybe we don't need to fix them now, as we discussed off-line.

Perhaps file an issue to re-examine some of the poor code in the bytecode verifier pass.

File: third_party/move/move-borrow-graph/src/graph.rs [hunk 3]
```diff
@@ -110,6 +110,32 @@ impl<Loc: Copy, Lbl: Clone + Ord> BorrowGraph<Loc, Lbl> {
         returned_edges
     }
 
+    /// Returns true if the given reference is borrowed via the given label.
```
Comment (vineethk) [inline third_party/move/move-borrow-graph/src/graph.rs:113]: What was nice about the previous reference safety algorithm was that it explained all the core representations giving intuitions about them. Would be nice to have something similar here since you already understand this deeply, but it is not a PR blocker.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+        }
+    }
+}
+
+impl LifetimeInfoAtCodeOffset {
+    pub fn new(before: Rc<dyn LifetimeInfo>, after: Rc<dyn LifetimeInfo>) -> Self {
+        Self { before, after }
+    }
+
+    pub fn borrow_kind_before(&self, temp: TempIndex) -> Option<ReferenceKind> {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs:45]: Because these APIs could be used by other passes, would be good to add documentation and invariants.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs [hunk 5]
```diff
@@ -0,0 +1,1283 @@
...
+/// The domain with which the analysis framework will be instantiated.
+#[derive(Clone, Debug, PartialEq, Eq)]
+pub struct LifetimeState {
+    /// An instantiation of the borrow graph shared with the runtime. We use
+    /// `AttrId` for locations and the `Label` type defined below. Effectively,
+    /// each edge in the graph has associated `AttrId` for identifying instruction
+    /// (and location) which created it, and `Vec<Label>` for describing the operations
+    /// via which the edge was established.
+    borrow_graph: BorrowGraph<AttrId, Label>,
+    /// Locals and there associated abstract values, to be indexed by TempIndex.
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs:61]:
```suggestion
    /// Locals and their associated abstract values, to be indexed by TempIndex.
```

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs [hunk 6]
```diff
@@ -0,0 +1,1283 @@
...
+        }
+    }
+}
+
+/// A label of an edge in the borrow graph.
+#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
+enum Label {
+    Local(TempIndex),
+    Global(QualifiedId<StructId>),
+    Field(QualifiedId<StructId>, usize),
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs:82]: Document what the usize is for.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs [hunk 7]
```diff
@@ -0,0 +1,88 @@
...
+    }
+}
+
+/// A trait to be implemented by reference safety processors
+pub trait LifetimeInfo {
+    fn borrow_kind(&self, temp: TempIndex) -> Option<ReferenceKind>;
+    fn display(&self, target: &FunctionTarget) -> Option<String>;
+}
+
+struct NoLifetimeInfo();
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs:60]: Is this for code offsets that are not reachable?

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs (hunk 4 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs:45]: Is it correct that, if return value is Some(mut_or_immut), then `temp` is actively borrowed before this program point?

File: third_party/move/move-compiler-v2/src/lib.rs [hunk 8]
```diff
@@ -407,7 +407,15 @@ pub fn bytecode_pipeline(env: &GlobalEnv) -> FunctionTargetPipeline {
     // Reference check is always run, but the processor decides internally
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/lib.rs:407]: Move this comment to the `else` branch below (for the old ref safety processor)?

File: third_party/move/scripts/move_pr.sh [hunk 9]
```diff
@@ -150,7 +150,7 @@ if [ ! -z "$CHECK" ]; then
 fi
 
 CARGO_OP_PARAMS="--profile $MOVE_PR_PROFILE"
-CARGO_NEXTEST_PARAMS="--profile $MOVE_PR_NEXTEST_PROFILE --cargo-profile $MOVE_PR_PROFILE"
+CARGO_NEXTEST_PARAMS="--profile $MOVE_PR_NEXTEST_PROFILE --cargo-profile $MOVE_PR_PROFILE $MOVE_PR_NEXTEST_ARGS"
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/scripts/move_pr.sh:153]: I'm using it to pass `--num-threads 20` as otherwise nextest only utilizes 6 of my 24 cores. That's definitely useful for other use cases as well.

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 10]
```diff
@@ -289,15 +290,38 @@ const TEST_CONFIGS: Lazy<BTreeMap<&str, TestConfig>> = Lazy::new(|| {
...
+        // Reference safety tests no-opt
         TestConfig {
             name: "reference-safety-no-opt",
             runner: |p| run_test(p, get_config_by_name("reference-safety-no-opt")),
             include: vec!["/reference-safety/"],
             exclude: vec![],
             // Some reference tests create different errors since variable names are
             // known without optimizations, so we need to have a different exp file
-            exp_suffix: Some("no-opt.exp"),
+            exp_suffix:Some("no-opt.exp"),
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/testsuite.rs:324]: Strange, cargo fmt should have taken care of this. Fixed.

File: third_party/move/move-borrow-graph/src/graph.rs (hunk 3 above)
Comment (wrwg) [reply third_party/move/move-borrow-graph/src/graph.rs:113]: Yes, would need to pep up this code here and document better.

File: third_party/move/move-borrow-graph/src/graph.rs [hunk 11]
```diff
@@ -110,6 +110,32 @@ impl<Loc: Copy, Lbl: Clone + Ord> BorrowGraph<Loc, Lbl> {
...
+    pub fn is_borrowed_via(&self, id: RefID, label: Lbl) -> bool {
+        let mut parents = BTreeSet::new();
+        for (_loc, parent, path, _strong) in self.in_edges(id) {
+            if path.contains(&label) {
+                return true;
+            }
+            parents.insert(parent);
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-borrow-graph/src/graph.rs:120]: Right, this isn't good, as this can be a DAG. I factored out a parent edge visitor which is iterative and doesn't revisit the same parent.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs [hunk 12]
```diff
@@ -0,0 +1,88 @@
...
+    pub fn get_info_at(&self, code_offset: CodeOffset) -> &LifetimeInfoAtCodeOffset {
+        self.0.get(&code_offset).expect("lifetime info")
+    }
+}
+
+/// Information present at each code offset
+#[derive(Clone)]
+pub struct LifetimeInfoAtCodeOffset {
+    /// Information hidden via a trait, specific to the processor.
+    before: Rc<dyn LifetimeInfo>,
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs:27]: It's a technical issue. The thing needs to have `Clone`, and `Box<dyn T>` doesn't have it.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs (hunk 4 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs:45]: Yes, correct. Added doc.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs (hunk 7 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/mod.rs:60]: No, for being able to implement `Default`. Added a comment.

**Review by Khalilheyrani6367 — APPROVED** [review]
