### PR TITLE
[compiler-v2][trivial] Do not allow using inline functions as function value

### LINKED ISSUE #16678: [Bug] Unexpected lambda when calling inline function that has function value inside
# 🐛 Bug

```
//# publish
module 0xCAFE::Module0 {
    public inline fun function1() {
        (||{})();
    }

    public fun function2() {
        (function1)();
    }
}
```

fails compilation with

```
Error: compilation errors:
 bug: unexpected lambda, expected to be eliminated by lambda lifting
  ┌─ TEMPFILE:4:9
  │
4 │         (||{})();
  │         ^^^^^^
```

Note that `inline` and the parentheses around `function1` are necessary.

### LINKED ISSUE #16679: [Bug] Bytecode verifier error `UNIMPLEMENTED_HANDLE` when inline function is used as a variable
# 🐛 Bug

```
//# publish
module 0xCAFE::Module1 {
    public inline fun function1() {}

    public fun function2() {
        (function1)();
    }
}
```

fails bytecode verifier with

```
Error: compilation errors:
 bug: bytecode verification failed with unexpected status code `UNIMPLEMENTED_HANDLE`. This is a compiler bug, consider reporting it.
Error message: none
  ┌─ TEMPFILE:2:1
  │  
2 │ ╭ module 0xCAFE::Module1 {
3 │ │     public inline fun function1() {}
4 │ │     public fun function2() {
5 │ │         (function1)();
6 │ │     }
7 │ │ }
  │ ╰─^
```

Note that `inline` and the parentheses around `function1` are necessary.

Other usage of `function1` as a variable will trigger the same error code:

e.g.

```
    public inline fun function1() {}

    public fun function2() {
        f3(function1);
    }

    public fun f3(x: ||) {
        x();
    }
```

or

```
    struct S {
        x: ||,
    }

    public inline fun function1() {}

    public fun f4() {
        let s = S { x: function1 };
        let S { x } = s;
        x();
    }
```

This might be related to #16678

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR adds a check to forbid using inline functions as a function value.

close #16678  close #16679 

## How Has This Been Tested?

Existing tests and two new test cases.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by junxzm1990 — APPROVED** [review]

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 1]
```diff
@@ -3683,6 +3683,10 @@ impl ExpTranslator<'_, '_, '_> {
         }
 
         if let Some(entry) = self.parent.parent.fun_table.get(&global_var_sym) {
+            if entry.kind == FunctionKind::Inline {
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/exp_builder.rs:3686]: Could we please add the following tests (separating out the positive and negative tests in different files):

```
    public inline fun foo(x: u64): u64 {
        x + 1
    }

    public fun negative(): u64 {
        let f = foo;
        f(42)        
    }

    public fun positive_1(): u64 {
        let f = || foo(42);
        f()
    }

    public fun positive_2(): u64 {
        let f = |x| foo(x);
        f(42)
    }
```

**Review by vineethk — APPROVED** [review]
Left a comment with additional tests.

LGTM!

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:3686]: added the tests.
