### PR TITLE
[Compiler] Catch borrow of tuple at expression builder time

### LINKED ISSUE #16583: [Bug] `inconsistent tuple arity` when compiling reference of tuple
# 🐛 Bug

Compiling the program with `aptos move compile --language-version 2.2`:
```
//# publish
module 0xCAFE::Module0 {
    fun f() {
        &((1,2));
    }
}
```

gives

```
bug: inconsistent tuple arity: 1 and 2
  ┌─ .../test.move:4:10
  │
4 │         &((1,2));
  │          ^^^^^^^

{
  "Error": "Move compilation failed: exiting with stackless bytecode generation errors"
}
```

### PR DESCRIPTION
**Pull request by JakeSilverman**
## Description

Resolves #16583

Disallow borrowing tuples.

## How Has This Been Tested?

Existing text coverage

## Key Areas to Review

1) Look at error message added to `third_party/move/move-compiler-v2/tests/more-v1/parser/spec_parsing_inside_fun.exp`. This is potentially a bit confusing if the user doesn't know that `spec` has type `unit`. Are we fine with this error message?

2) I don't love that my solution spaghettifies the code. Curious if a better way to do this. 

3) Perhaps worth looking into: there were existing move language tests that clearly intended to capture this bug (which is why I didn't need to write new tests), but the`.exp` files were incomplete (for example, `spec_parsing_inside_fun.move` noted that the expression `&mut spec {};` is a typing error but the corresponding `.exp` file did not capture this). Are there other instances of move tests where the `.exp` file may be incomplete?

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by JakeSilverman** [comment]
* **#16661** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16661?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16661?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 1]
```diff
@@ -1901,9 +1901,13 @@ impl ExpTranslator<'_, '_, '_> {
                 } else {
                     self.translate_exp(exp, &target_ty)
                 };
-                if self.subs.specialize(&target_ty).is_reference() {
+                let specialized_target_ty = self.subs.specialize(&target_ty);
+                if specialized_target_ty.is_reference() {
                     self.error(&loc, "cannot borrow from a reference")
                 }
+                if specialized_target_ty.is_tuple() {
+                    self.error(&loc, "cannot borrow a tuple")
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/exp_builder.rs:1909]: We are actually allowing `let (_x, _y) = *&(a, b);` and let x = &(a)`, could you double check what happens after your fix?

Comment (JakeSilverman) [reply third_party/move/move-model/src/builder/exp_builder.rs:1909]: For `let x = &(a);`: this is allowed. Note that `(a)` is not parsed as a tuple. I can add this in as a test case.
For `let (_x, _y) = *&(a, b);`; this is not allowed with my fix. And I see that this is allowed with current move compiler. Is this intentional though or bug? The move book states "The only operation that can be done on tuples currently is destructuring." and this seems to break that logic.

Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:1909]: yeah, as far as I remember, this may relate to optimizing `*&` away, which is necessary for testing variants of enum during generation of stackless bytecode. Any insights on whether we should allow this, @vineethk?

Comment (JakeSilverman) [reply third_party/move/move-model/src/builder/exp_builder.rs:1909]: Yeah it has to be due to optimizing. As another data point, the current compiler will reject this
```
fun g() : &(u64, u64) {
    return &(1, 2)
}
fun f() {
    let (x, y) = *g();
}
```

Despite accepting `let (x, y) = *&(1, 2);`, which is a bit counter-intuitive.

Comment (vineethk) [reply third_party/move/move-model/src/builder/exp_builder.rs:1909]: I think it is okay to reject `*&(a, b)`: this may just have an oversight when the optimization was implemented.

The fix looks reasonable, can we please add more tests? Some thoughts:
- `&foo()` where `foo` is an inline function returning a tuple
- same as above, but `foo` is a regular function
- take `&mut` of a tuple and try to assign into it
- some of the examples discussed above.

Can approve after more tests are added.

Comment (vineethk) [reply third_party/move/move-model/src/builder/exp_builder.rs:1909]: The following test case:
```
fun ret_borrow_tup(): &(u64, u64) {
    abort 0
}
```
seems to generate a compiler ICE.

This is certainly a bug. You can look into fixing it in this PR (as it is closely related), or create another PR for it.

Comment (JakeSilverman) [reply third_party/move/move-model/src/builder/exp_builder.rs:1909]: I'll look into this in separate PR; going to spend rest of today addressing your comments to my other outstanding PR + focusing on Etna.
