### PR TITLE
[vm] Fixing variance in mutable assign of function values

### LINKED ISSUE #16335: [Bug] Modifying un-copyable function value raises  `UNKNOWN_INVARIANT_VIOLATION_ERROR`
# 🐛 Bug

```
//# publish
module 0x42::Test {
    fun f(x: &mut || has drop) {
        *x = || {};
    }

    fun f2() {
        let x: || has copy+drop = ||{};
        f(&mut x);
    }
}

//# run 0x42::Test::f2
```

Running the above as transactional test gives the VMError `UNKNOWN_INVARIANT_VIOLATION_ERROR`:

```
processed 2 tasks

task 1 'run'. lines 13-13:
Error: Function execution failed with VMError: {
    major_status: UNKNOWN_INVARIANT_VIOLATION_ERROR,
    sub_status: Some(1),
    location: 0x42::Test,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
```

### PR DESCRIPTION
**Pull request by wrwg**
## Description

The `WriteRef` instruction used direct comparison instead of assignability.

Closes #16335

## How Has This Been Tested?

Unit tests

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [ ] Other (specify)

### CODE REVIEW

**Comment by wrwg** [comment]
* **#16350** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16350?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16350?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-vm/types/src/loaded_data/runtime_types.rs [hunk 1]
```diff
@@ -612,13 +612,12 @@ impl Type {
     #[inline]
     pub fn paranoid_write_ref(&self, val_ty: &Type) -> PartialVMResult<()> {
         if let Type::MutableReference(inner_ty) = self {
-            if inner_ty.as_ref() == val_ty {
-                return inner_ty.paranoid_check_has_ability(Ability::Drop);
-            }
+            val_ty.paranoid_check_assignable(inner_ty)?;
+            inner_ty.paranoid_check_has_ability(Ability::Drop)
+        } else {
+            let msg = format!("Cannot write type {} to imuutable type {}", val_ty, self);
```
Comment (georgemitenkov) [inline third_party/move/move-vm/types/src/loaded_data/runtime_types.rs:618]: typo: `imuutable` --> `imutable`

**Review by georgemitenkov — APPROVED** [review]
