### PR TITLE
[Compiler-v2][trivial] fix error handling for `match` in expansion phase

### LINKED ISSUE #15073: [bug][compiler-v2] Thread 'main' panicked
Second time I've run into this with compiler-v2. I'm getting this error in various scenarios:
```
thread 'main' panicked at third_party/move/move-compiler/src/expansion/translate.rs:2606:61:
bind list always present
```

The first time I saw it was with this code:
```
match (entity_data) {
            Entity::V1 { tools, .. } => {
                vector::push_back(tools, tool_def);
            }
        };
```
I had failed to include `Entity` in a use statement.  When I added the use statement the error went away.  Today I'm seeing it with this code:
```
public fun init_registration(
		creator: &signer,
		tool_type: ToolType
	): Object<Registration> {
		let registration: Registration;
		match(tool_type) {
			ToolType::Http { uri } => {
				registration =	init_http_registration(uri);
			},
			ToolType::Aptos { module_address, module_name, function_name, max_transaction_amount } => {
				registration = init_aptos_registration(creator, module_name, function_name, max_transaction_amount);
			}
		}
		
	}
```
Clearly this code is not finished as it's not returning a value (along with some other problems). But rather than the compiler picking this up, it's throwing this same error:
```
(base) culbrethw@MBA beacon % aptos move compile --move-2
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Beacon
thread 'main' panicked at third_party/move/move-compiler/src/expansion/translate.rs:2606:61:
bind list always present
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When I add a return value to the code, even if it's wrong, the compiler functions as expected and identifies errors without panic. And to make it even more confusing, if I change two or three more things and then go back to the exact same code that was causing the panic, the compiler works as expected and doesn't throw the panic error. Perplixing and frustraiting as there's some sequence of events happening to get the compiler to this state that I haven't been able to replicate deliberately.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR closes #15073 by generating an error instead of using `expect` when `bind_list` fails during handling `match` statements.

## How Has This Been Tested?

1) existing tests pass;
2) added a new test.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by vineethk — APPROVED** [review]
Nice. LGTM.

File: third_party/move/move-compiler/src/expansion/translate.rs [hunk 1]
```diff
@@ -2600,13 +2600,20 @@ fn exp_(context: &mut Context, sp!(loc, pe_): P::Exp) -> E::Exp {
...
-                    let body = *exp(context, pb);
-                    sp(loc, (bind_list, opt_cond, body))
+                    if let Some(bind_list) = bind_list(context, pbl) {
+                        let opt_cond = pc.map(|e| *exp(context, e));
+                        let body = *exp(context, pb);
+                        Some(sp(loc, (bind_list, opt_cond, body)))
+                    } else {
+                        context.env.add_diag(diag!(
+                            Syntax::InvalidLValue,
+                            (loc, "bind list cannot be constructed")
```
Comment (wrwg) [inline third_party/move/move-compiler/src/expansion/translate.rs:2613]: I wonder if this is always a followup error (like in your test case) whether we should just ignore this if context.env.has_errors, and only produce this error if not.

**Review by wrwg — APPROVED** [review]

File: third_party/move/move-compiler/src/expansion/translate.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-compiler/src/expansion/translate.rs]: done

Comment (brmataptos) [reply third_party/move/move-compiler/src/expansion/translate.rs]: +1, a brief check of `bind_list` suggest that is the case.  But it would be better if we had a documented policy for these translate functions that they return `None` or `Err` only if a diagnostic has been generated.  Note that
```
    let x: Option<Vec<_>> = Vec::<Option<T>>::new().iter().collect();
```
yields `Some([])`, so that holds for the collector in `bind_list`.  I couldn't find official docs, but https://users.rust-lang.org/t/collect-option-t-on-an-empty-iterator/24966.

**Review by brmataptos — APPROVED** [review]
