### PR TITLE
[move-compiler-v2] fix #14633: fix error messages for lambdas, identify change points for more complete lambda implementation

### LINKED ISSUE #14633: [Bug][move-compiler-v2] problems with errors about lambda types in test hide panics due to missing error checks
# 🐛 Bug

Comparing
- third_party/move/move-compiler/tests/move_check/typing/lambda.exp
- third_party/move/move-compiler-v2/tests/checking/typing/lambda.exp

We see:
- line 40: V2 describes the error as the actual type of `action` (`|&T|`) being different from the type which would be expected from the context in which it is used (`|(&T, u64)|_`).  The user will be confused by this, since the entire expression is pointed to.  This should be changed to clarify somehow:
```
        error: expected `|(&T, u64)|_` but found a value of type `|&T|`
           ┌─ tests/checking/typing/lambda.move:40:13
           │
        40 │             action(XVector::borrow(v, i), i); // expected to have wrong argument count
           │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
- line 45: similarly confusing error message from V2
- line 61: V2 has a very confusing message, given that the previous line declares `x: u64`:
```
         error: cannot return `u64` from a function with result type `|integer|`
          ┌─ tests/checking/typing/lambda.move:61:9
          │
       61 │         x(1) // expected to be not a function
          │         ^^^^
```
- line 67 and 73: describe the error in terms of the internals of the type system, rather than the programmer's view.  Better would be to special-case built-in operations like `+` and say something like: `a value of reference type &integer is not allowed as an argument to operator +`.
```
       error: reference type `&integer` is not allowed as a type argument (type was inferred)
          ┌─ tests/checking/typing/lambda.move:67:35
          │
       67 │         foreach(&v, |e| sum = sum + e) // expected to cannot infer type
          │                                   ^
          │
          = required by instantiating type parameter `T` of function `+`
```
- lines 77, 81, 84, 86. 89 have errors in V1 which are missing from the V2 case.
   - Removing earlier errors allows V2 to catch line 84, but others are missing
- commenting out the code at line 84 causes a panic in `recursive_struct_checker.rs:105`.

The following is the part of the test code that doesn't yield an error and falls through to panic:
```
    public fun lambda_not_allowed() {
        let _x = |i| i + 1; // expected lambda not allowed
    }

    struct FieldFunNotAllowed {
        f: |u64|u64, // expected lambda not allowed
    }

    public inline fun macro_result_lambda_not_allowed(): |u64| {  // expected lambda not allowed
        abort (1)
    }
    public fun fun_result_lambda_not_allowed(): |u64| {  // expected lambda not allowed
        abort (1)
    }
```

### PR DESCRIPTION
**Pull request by brmataptos**
## Description

Catch all errors in `move-compiler-v2/tests/checking/typing/lambda.move` in Compiler V2,
after splitting and gradually commenting out code as `lambda[2-5].move`,
to avoid shadowing by other errors.  Lay groundwork for support of lambdas in various capacities.

Fixes #14633.

- add checking for function-typed function results in `function_checker`, and functions in parameters and results of function types in both args and results to functions there.
- Change `internal_error` to `error` in `bytecode_generator` and `module_generator`
  to properly show "error" rather than "bug" if lambdas are mistakenly used as values today.
- tag some code to show where changes are needed to support lambda: // TODO(LAMBDA)
- fix unused_params_checker and recursive_struct_checker to tolerate lambda types
- add experiments to control enabling of various aspects of lambda support:
  - `LAMBDA_IN_PARAMS`, `LAMBDA_IN_RETURNS` to allow lambdas as general function params or results
  - `LAMBDA_FIELDS` - support lambdas in struct fields
  - `LAMBDA_VALUES` - support lambdas in general-purpose values
  - may add `LAMBDA_TYPE_PARAMS` later
- update lambda-lifting test config to use those flags rather than disabling checks
- add a `result_type_loc` field to move-model's `FunctionData` (and model-builder's `FunEntry`)
  to more precisely locate errors in function result types.
- Fix `GlobalEnv::internal_dump_env` to use function- and struct-specific type contexts
  so that types are shown with correct type parameter names.
- Check that struct fields are not functions.

## How Has This Been Tested?

Running the usual tests.

## Key Areas to Review

Note that a few errors are caught quite late, in `bytecode-generator`,
and the order in which we catch errors may be a bit surprising to
users (errors in `exp_builder` come first, then errors caught by
`function_checker`, then (much later) `bytecode_generator`.).
Actually supporting particular subsets of the "experiments" mentioned
above would be difficult, but it seems useful to have the labels to
help understand just what features are supported by the implementation
as we go.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [x] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [X] Move Compiler
- [ ] Other (specify)

## Checklist
- [X] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I identified and added all stakeholders and component owners affected by this change as reviewers
- [X] I tested both happy and unhappy path of the functionality
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by brmataptos** [comment]
* **#14742** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14742?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @brmataptos and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs [hunk 1]
```diff
@@ -3,55 +3,190 @@
...
+fn type_has_function(ty: &Type) -> bool {
+    match ty {
+        Type::Tuple(tys) => tys.iter().any(|ty| ty.is_function()),
+        Type::Fun(..) => true,
+        _ => false,
+    }
+}
+
+// Takes a list of function types, returns those which have a function type in their argument type
+fn identify_function_types_with_functions_in_args(func_returns: Vec<Type>) -> Vec<Type> {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs:27]: Because this function a list of function types, could we call the param `func_types` or even just `types`? Not clear from the local context why this param is called `func_returns`.

File: third_party/move/move-compiler-v2/src/env_pipeline/unused_params_checker.rs [hunk 2]
```diff
@@ -55,12 +55,16 @@ fn used_type_parameters_in_fields(struct_env: &StructEnv) -> BTreeSet<u16> {
 fn used_type_parameters_in_ty(ty: &Type) -> BTreeSet<u16> {
     match ty {
         Type::Primitive(_) => BTreeSet::new(),
-        Type::Struct(_, _, tys) => tys.iter().flat_map(used_type_parameters_in_ty).collect(),
+        Type::Tuple(tys) | Type::Struct(_, _, tys) => {
+            tys.iter().flat_map(used_type_parameters_in_ty).collect()
+        },
         Type::TypeParameter(i) => BTreeSet::from([*i]),
         Type::Vector(ty) => used_type_parameters_in_ty(ty),
+        Type::Fun(t1, t2) => [t1, t2]
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/unused_params_checker.rs:63]: This may not be the right behavior:

Here, we detect unused (non-phantom) type params and suggest that they be made phantom. But the ability requirement enforcement may be different for struct `S<T>` that has a field with type `T`, vs. a struct `S<T>` that has a field with type `|T|` (i.e., a function that consumes an `T` and returns nothing). That is, we could still make `T` a phantom type, because it is not "directly" used in making up the type's representation.

**Review by vineethk — COMMENTED** [review]
Looking good, can approve once the comment in `unused_params_checker.rs` is addressed.

File: third_party/move/move-compiler-v2/src/env_pipeline/unused_params_checker.rs (hunk 2 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/env_pipeline/unused_params_checker.rs:63]: edit: after thinking about this again, I realized this should be okay, because we are complaining about unused type params here and not identifying ability requirements, which I was conflating in the write up above.

**Review by vineethk — APPROVED** [review]

**Review by rahxephon89 — APPROVED** [review]
