### PR TITLE
[Compiler-V2] [Bugfix] Improve cyclic instantiation checker error messages

### LINKED ISSUE #12903: [Bug][Compiler-v2] cyclic instantiation error should be pointed to the call site
# 🐛 Bug

For the cyclic type instantiation error in [infinite_instantiations_invalid.exp](https://github.com/aptos-labs/aptos-core/pull/12763/files#diff-7c67313a100931c9aac28a127591b9e31a1d3655aa4772bd35c778c9ef708c92), V2 points to the function definition:

```
error: cyclic type instantiation: a cycle of recursive calls causes a type to grow without bound
  ┌─ tests/cyclic-instantiation-checker/v1-typing/infinite_instantiations_invalid.move:6:16
  │
6 │     public fun t<T>() {
  │                ^
  │
  = `t<T>` calls `t<X::Box<T>>` at tests/cyclic-instantiation-checker/v1-typing/infinite_instantiations_invalid.move:6
```

While V1 points to the function call:

```
error[E04019]: cyclic type instantiation
  ┌─ tests/move_check/typing/infinite_instantiations_invalid.move:7:9
  │
7 │         t<Box<T>>()
  │         ^^^^^^^^^^^
  │         │ │
  │         │ The type parameter 't::T' was instantiated with the type '0x42::X::Box<T>', which contains the type parameter 't::T'. This recursive call causes the instantiation to recurse infinitely
  │         Invalid call to '0x42::X::t'
```

### PR DESCRIPTION
**Pull request by fEst1ck**
## Description

For error messages like "f calls g at loc", the loc is previously the location of f, the caller, but it better be the location of g, the callee. See the updated test outputs for examples.

Fixes #12903.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

### CODE REVIEW

**Review by rahxephon89 — APPROVED** [review]
LGTM, thanks!

File: third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs [hunk 1]
```diff
@@ -173,30 +173,31 @@ impl<'a> CyclicInstantiationChecker<'a> {
...
             .collect_vec();
-        let (caller_loc, caller) = &callers_chain.last().expect("parent");
+        let (_caller_loc, caller) = &callers_chain.last().expect("parent");
+        let callee_loc = self.mod_env.env.get_node_loc(nid);
         labels.push(format!(
             "`{}` calls `{}` {}",
             self.display_call(caller, root),
             self.display_call(&callee, root),
-            caller_loc.display_line_only(self.mod_env.env)
+            callee_loc.display_line_only(self.mod_env.env)
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs:200]: Could we use `error_with_labels` (or `diag_with_primary_notes_and_labels`) instead, where the location and associated code gets displayed much more nicely and provides more context?

Comment (vineethk) [reply third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs:200]: See reference safety processor for some examples.

Comment (vineethk) [reply third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs:200]: It is also an odd one out as far as error messages are concerned: `display_line_only` is not really used anywhere in the compiler core.

Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs:200]: I worry that this will cause the errors to increase in size too much.  This is comparable to V1's errors, see tests/move_check/translated_ir_tests/move/generics/instantiation_loops/mutually_recursive_three_args_type_con_shifting.exp

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs (hunk 1 above)
Comment (fEst1ck) [reply third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs:200]: We explained this in the original PR. The problem with `error_with_labels` is that we don't control the order of the error messages. They are shown in the order of source location, instead of the order in the call chains. The resulting error messages are disastrous. But once `error_with_labels` can preserve the order of error messages as we added them, we should switch to that to provide more context.
