### PR TITLE
[Compiler-v2] fix name conflicts when multiple scripts have functions with the same name

### LINKED ISSUE #12951: [Bug][move-compiler-v2] move-cli test naming conflict between multiple script functions on V2, not V1
running
```
UB=1 MOVE_COMPILER_V2=true cargo test -p move-cli
```
shows an error on one test that doesn't occur with V1:
```
diff --git a/third_party/move/tools/move-cli/tests/sandbox_tests/build_modules_and_scripts/args.exp b/third_party/move/too
ls/move-cli/tests/sandbox_tests/build_modules_and_scripts/args.exp
index 8a9cdeb809..0aff0335ba 100644
--- a/third_party/move/tools/move-cli/tests/sandbox_tests/build_modules_and_scripts/args.exp
+++ b/third_party/move/tools/move-cli/tests/sandbox_tests/build_modules_and_scripts/args.exp
...
+Error: Module and/or script names found that would cause failures on case insensitive file systems when compiling package 'build_modules_and_scripts':
+The following modules and/or scripts would collide as 'script1' on the file system:
+       Script 'script1' at path './scripts/script1.move'
+       Script 'script1' at path './scripts/script2.move'
+Please rename these scripts and/or modules to resolve these conflicts.
```

third_party/move/tools/move-cli/tests/sandbox_tests/build_modules_and_scripts/scripts/script1.move and script2.move each defines a script with a single function `fun script1()`.

So V2 is handling functions in scripts differently than V1.  I suspect that V1 is randomly renaming scripts in some way that V2 is not also doing.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

The Move package in the test case [third_party/move/tools/move-cli/tests/sandbox_tests/build_modules_and_scripts](https://github.com/aptos-labs/aptos-core/blob/a1ae60836f987cacb6ed3f731e585df7c684c67e/third_party/move/tools/move-cli/tests/sandbox_tests/build_modules_and_scripts/scripts/script1.move) has two scripts `script1.move` and `script2.move` and both of them have a function called `script1`. When V1 parses the code, these two functions with the same name are renamed with `script1_0` and `script1_1` so that when generating the bytecode, they will have the different name field in `NamedCompiledScript`. However, V2 compiler will lose the information [here](https://github.com/aptos-labs/aptos-core/blob/7b01dfab790a60e0ba5e073c2945ec48e1b7e9f2/third_party/move/move-model/src/lib.rs#L394). 
This PR fixes this issue by adding back the suffix extracted from the name of the script module constructed earlier in [pseudo_script_name](https://github.com/aptos-labs/aptos-core/blob/d6483636c325f76c5207bb20f6160f0f395cba39/third_party/move/move-model/src/ast.rs#L2674).

Close #12951

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

1) Existing V2 tests do not fail;
2) When running the test mentioned in #12951, the error disappears.

## Key Areas to Review

Whether the change will break any implicit assumptions in the package system.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by brmataptos — APPROVED** [review]
LGTM

File: third_party/move/move-compiler-v2/src/file_format_generator/mod.rs [hunk 1]
```diff
@@ -54,7 +54,21 @@ pub fn generate_file_format(
                     name,
                     ..
                 } = main_handle.expect("main handle defined");
-                let name = Symbol::from(identifiers[name.into_index()].as_str());
+                // When two scripts have the same function name, we need to use
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/mod.rs:57]:
```suggestion
                // Because two scripts can have the same function name, we need to use
```

**Review by vineethk — APPROVED** [review]
LGTM (minor comment nit posted).
