### PR TITLE
[testing] Support for printing function values in transactional tests

### LINKED ISSUE #16225: [Bug] Transactional test crashes if a function value is returned
# 🐛 Bug

The following transactional test:
```move
//# publish
module 0xc0ffee::m {
    public fun test(): || {
        || {}
    }
}

//# run 0xc0ffee::m::test
```
crashes with:

```
test panicked: called `Option::unwrap()` on a `None` value
```

When you backtrace, you see that there is a corresponding TODO to support function values.

### PR DESCRIPTION
**Pull request by georgemitenkov**
## Description

This fixes multiple issues:
1. Fixes #16225 to allow returning function values in transactional test and printing them.
2. Fixes function value printing where an extra `:` was added between function name and type arguments.
3. Fixes function value capture argument printing because before they were not printed at all (wrong arity was passed).

For (3), after all capture arguments are printed, `..` is appended to indicate that there might be more non-captured arguments to follow. But it is not possible to check how many without knowing the arity of the captured function.

## How Has This Been Tested?

New transactional test.

## Key Areas to Review

N/A

## Type of Change

- [x] Bug fix
- [x] Tests

## Which Components or Systems Does This Change Impact?

- [x] Move/Aptos Virtual Machine

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by georgemitenkov** [comment]
* **#16538** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16538?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16538?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-core/types/src/function.rs [hunk 1]
```diff
@@ -156,15 +156,37 @@ impl ClosureMask {
...
-    pub fn merge_placeholder_strings(
-        &self,
-        arity: usize,
-        captured: Vec<String>,
-    ) -> Option<Vec<String>> {
-        let provided = (0..arity - captured.len())
-            .map(|_| "_".to_string())
-            .collect::<Vec<_>>();
-        self.compose(captured, provided)
+    pub fn merge_placeholder_strings(&self, captured: Vec<String>) -> Vec<String> {
```
Comment (vineethk) [inline third_party/move/move-core/types/src/function.rs:159]: Could we please add a doc string to this public function?

File: third_party/move/move-core/types/src/function.rs [hunk 2]
```diff
@@ -156,15 +156,37 @@ impl ClosureMask {
...
+        while mask != 0 {
+            if mask & 0x1 != 0 {
+                result.push(captured.next()?)
+            } else {
+                result.push("_".to_string())
+            }
+            mask >>= 1;
+        }
+
+        // We do not now arity information of the function, so the simplest option is to indicate
```
Comment (vineethk) [inline third_party/move/move-core/types/src/function.rs:181]:
```suggestion
        // We do not know arity information of the function, so the simplest option is to indicate
```

File: third_party/move/move-core/types/src/function.rs [hunk 3]
```diff
@@ -407,11 +429,7 @@ impl fmt::Display for MoveClosure {
             captured,
         } = self;
         let captured_str = mask
-            .merge_placeholder_strings(
-                mask.captured_count() as usize,
-                captured.iter().map(|v| v.1.to_string()).collect(),
-            )
-            .unwrap_or_else(|| vec!["*invalid*".to_string()])
+            .merge_placeholder_strings(captured.iter().map(|v| v.1.to_string()).collect())
             .join(",");
```
Comment (vineethk) [inline third_party/move/move-core/types/src/function.rs:433]:
```suggestion
            .join(", ");
```

Comment (vineethk) [reply third_party/move/move-core/types/src/function.rs:433]: I believe other "lists" are displayed as `a, b, c` and not `a,b,c`, so we might want to be consistent.

File: third_party/move/move-vm/types/src/values/function_values_impl.rs [hunk 4]
```diff
@@ -93,11 +93,7 @@ impl Display for Closure {
         let Self(fun, captured) = self;
         let captured = fun
             .closure_mask()
-            .merge_placeholder_strings(
-                captured.len(),
-                captured.iter().map(|v| v.to_string()).collect(),
-            )
-            .unwrap_or_else(|| vec!["*invalid*".to_string()]);
+            .merge_placeholder_strings(captured.iter().map(|v| v.to_string()).collect());
         write!(f, "{}({})", fun.to_stable_string(), captured.join(","))
```
Comment (vineethk) [inline third_party/move/move-vm/types/src/values/function_values_impl.rs:97]:
```suggestion
        write!(f, "{}({})", fun.to_stable_string(), captured.join(", "))
```

**Review by vineethk — APPROVED** [review]
Approving assuming comments are addressed, thanks!

File: third_party/move/move-core/types/src/function.rs (hunk 1 above)
Comment (georgemitenkov) [reply third_party/move/move-core/types/src/function.rs:159]: Added, also renamed to `format_arguments` so its clearer

File: third_party/move/move-core/types/src/function.rs (hunk 2 above)
Comment (georgemitenkov) [reply third_party/move/move-core/types/src/function.rs:181]: oops 🤦‍♂️

File: third_party/move/move-core/types/src/function.rs (hunk 3 above)
Comment (wrwg) [reply third_party/move/move-core/types/src/function.rs:441]: Also forgot ;-)

Comment (georgemitenkov) [reply third_party/move/move-core/types/src/function.rs:441]: Got it, added spaces then 👍
