### PR TITLE
[Compiler-v2] Fix issue 12077

### LINKED ISSUE #12077: [Bug][Compiler-v2] Checking return type for scripts is missing
# 🐛 Bug

For the following code, 

```
script {
// despite script functions no longer have any built in checks,
// scripts still do not support return values
fun main(): u64 {
    0
}
}
```

V1 will generate the following error while V2 only catches it in the bytecode verification phase.

```
Invalid 'script' function return type. The function entry point to a 'script' must have the return type '()'
```

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

This PR closes #12077 by adding a check on the return type of functions defined in a script.

### Test Plan

1) existing tests pass;
2) port the test `main_return_type_not_unit.move` from V1 to V2.

### CODE REVIEW

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 1]
```diff
@@ -3751,6 +3751,13 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
             if entry.module_id != self.module_id {
                 continue;
             }
+            // If the function is from a script, its return value must be unit.
+            if self.module_name.is_script() && !entry.result_type.is_unit() {
+                self.parent.error(
+                    &entry.loc,
+                    "The function entry point to a 'script' must have the return type '()'",
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:3758]:
```suggestion
                    "The function entry point to a `script` must have the return type `()`",
```

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 2]
```diff
@@ -3751,6 +3751,13 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
             if entry.module_id != self.module_id {
                 continue;
             }
+            // If the function is from a script, its return value must be unit.
+            if self.module_name.is_script() && !entry.result_type.is_unit() {
+                self.parent.error(
+                    &entry.loc,
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:3757]: Using `name_loc` instead of `loc` might be nicer here for UX here, otherwise, we may end up showing a very large function's source only to say its return type is wrong.

**Review by vineethk — APPROVED** [review]
Couple of minor comments, LGTM otherwise.

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 2 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: done

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: done
