### PR TITLE
[move-2] Allow variables and functions be called `match` in Move-2

### LINKED ISSUE #14038: [Bug][CLI] CLI v3.5.0 breaks parsing for functions named `match`
# 🐛 Bug

@davidiw @wrwg
CLI v3.5.0 apparently interprets `match` as a keyword and thus does not (backwards-compatibly) support compilation for code that includes functions called `match`.

## To reproduce

From inside https://github.com/econia-labs/econia/tree/main/src/move/econia:

```sh
aptos move compile --named-addresses econia=0xace
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Econia
error[E01013]: unsupported language construct
     ┌─ /Users/alex/repos/econia/src/move/econia/sources/market.move:3865:17
     │
3865 │             ) = match(
     │                 ^^^^^ Move 2 language construct is not enabled: match expression

error[E01002]: unexpected token
     ┌─ /Users/alex/repos/econia/src/move/econia/sources/market.move:3866:26
     │
3866 │                 market_id,
     │                          ^
     │                          │
     │                          Unexpected ','
     │                          Expected ')'

{
  "Error": "Move compilation failed: Compilation error"
}
```

## Expected Behavior

This compilation succeeds for CLI v3.4.1

### PR DESCRIPTION
**Pull request by wrwg**
## Description

Fixes #14038.

The introduction of the `match (exp) { .. }` expression accidentally disabled the `match` name to be used for functions or variables. This PR adds context sensitivity to the parser to distinguish, for example, `match(x, y)` (a function call) from `match (e) { .. }`. As we are using a LL(2) parser, this is achieved by factoring out the common prefix. There is no function call `match(e) {` possible, so we know it is a match expression once we see `{`.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Added a number of test cases to the Move 2 testsuite. The parsers for language v1 and v2 are the same, so this also covers use cases for compiler v1 and compiler v2/language version v1.

### CODE REVIEW

File: third_party/move/move-compiler/src/parser/syntax.rs [hunk 1]
```diff
@@ -1464,21 +1467,80 @@ fn parse_for_loop(context: &mut Context) -> Result<(Exp, bool), Box<Diagnostic>>
 
 // Match = "match" "(" <Exp> ")" "{" ( <MatchArm> ","? )* "}"
 // MatchArm = <Bind> ( "if" <Exp> )? "=>" <Exp>
+// If called, we know we are looking at `match (`.
 fn parse_match_exp(context: &mut Context) -> Result<Exp, Box<Diagnostic>> {
+    // We cannot uniquely determine this is actually a match expression
+    // until we have seen the `match (exp) {` prefix. We parse the parts and
```
Comment (vineethk) [inline third_party/move/move-compiler/src/parser/syntax.rs:1473]: Ah - requiring `if` and `while` conditions have `()` around them saves us from `if match() {} else {}`.

I think it would be worth adding a test case with `fun match() {}`: it parses fine (because we are not in an expression matching context).

**Review by vineethk — APPROVED** [review]
Some other tests that might be worth having:
- `match` as module name
- `match(match()) { ... }` (inner `match()` is a function call expression)

All of these seem to work fine, btw.

File: third_party/move/move-compiler-v2/tests/checking/variants/variants_parse_err4.exp [hunk 2]
```diff
@@ -7,4 +7,4 @@ error: unexpected token
    │               ^^^^
    │               │
    │               Unexpected 'self'
-   │               Expected '('
+   │               Expected ';'
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/variants/variants_parse_err4.exp:10]: Perhaps, but I do not see a feasible way to avoid this. Only `match (` is now recognized as a prefix for a potential match statement. Its actually logical because `match; self` can be valid code.

File: third_party/move/move-compiler/src/parser/syntax.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler/src/parser/syntax.rs:1473]: Added the test

Comment (wrwg) [reply third_party/move/move-compiler/src/parser/syntax.rs:1473]: BTW, if we would not have the `if (..)` nonsense, we would not have a problem -- we could easily identify `match e` because there is no juxtaposition in expressions ...

**Review by rahxephon89 — APPROVED** [review]
