### PR TITLE
[Compiler-v2] Track live var info in spec blocks by default

### LINKED ISSUE #14762: [Bug][Compiler-v2][Prover] CALL_BORROWED_MUTABLE_REFERENCE_ERROR is raised when there is an inline spec
# 🐛 Bug

When adding to the following spec block after the while loop in the inline function `vector::find`

```
        spec {
           assert find ==> f(self[found_index]);
        };
```

compiler v2 will generate the following error when compiling the aptos-framework code:

bug: bytecode verification failed with unexpected status code `CALL_BORROWED_MUTABLE_REFERENCE_ERROR`. This is a compiler bug, consider reporting it.
    ┌─ /Users/tengzhang/aptos-core/aptos-move/framework/aptos-framework/sources/jwks.move:582:26
    │
582 │             option::some(vector::remove(&mut jwks.entries, index))
    │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

Currently, live var analysis only tracks the live var info in specs when `track_all_usages` is set. This leads to the issue in #14762 because variables that appear in spec block but are not alive anymore will not be dropped in the generated bytecode. This PR resolves the issue by tracking the live var info by default.

Close #14762 

## How Has This Been Tested?

1) Existing tests pass;
2) Add tests for compiler-v2 and prover.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rahxephon89** [comment]
* **#14890** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14890?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rahxephon89 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-prover/tests/sources/functional/ModifiesErrorTest.v2_exp [hunk 1]
```diff
@@ -1,64 +1,4 @@
 Move prover returns: exiting with verification errors
-warning: Unused assignment to `x0`. Consider removing or prefixing with an underscore: `_x0`
```
Comment (rahxephon89) [inline third_party/move/move-prover/tests/sources/functional/ModifiesErrorTest.v2_exp:2]: Warnings are removed because these variables appear in the spec, which is consistent with the behavior of the prover when using V1 compiler.

File: third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs [hunk 2]
```diff
@@ -373,12 +371,12 @@ impl<'a> TransferFunctions for LiveVarAnalysis<'a> {
...
-            Prop(id, _, exp) if self.track_all_usages => {
+            Prop(id, _, exp) => {
                 for idx in exp.used_temporaries() {
                     state.insert_or_update(idx, self.livevar_info(id, offset), true);
                 }
             },
-            SpecBlock(id, spec) if self.track_all_usages => {
+            SpecBlock(id, spec) => {
                 for idx in spec.used_temporaries() {
                     state.insert_or_update(idx, self.livevar_info(id, offset), true);
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs]: done

**Review by vineethk — APPROVED** [review]

File: third_party/move/move-prover/tests/sources/functional/bug_14762.exp [hunk 3]
```diff
@@ -0,0 +1,9 @@
+Move prover returns: exiting with model building errors
+error: invalid transfer of references
+   ┌─ tests/sources/functional/bug_14762.move:45:26
+   │
+39 │         let (found, index) = find(&s.entries, |obj| {
+   │                                   ---------- It is still being borrowed by this reference
```
Comment (brmataptos) [inline third_party/move/move-prover/tests/sources/functional/bug_14762.exp:6]: This error seems overly conservative.  Shouldn't this reference `&s.entries` not outlive the call to `find` ?

Comment (rahxephon89) [reply third_party/move/move-prover/tests/sources/functional/bug_14762.exp:6]: It is generated by V1 compiler. Do we want to take care of this?

**Review by wrwg — APPROVED** [review]
