### PR TITLE
[compiler-v2][trivial] Fix a bug in the replacer of exp rewriter in lambda lifter

### LINKED ISSUE #16407: [Bug] Compiler ICE when repeatedly applying a function value
# 🐛 Bug

Consider the following transactional test:
```
//# publish
module 0xc0ffee::m {
    fun apply_repeatedly(f: |u64|u64 has copy + drop, times: u64): |u64|u64 has copy + drop {
        |x| {
            for (i in 0..times) {
                x = f(x);
            };
            x
        }
    }

    public fun test(): u64 {
        apply_repeatedly(|x| x + 1, 10)(1)
    }
}
```

It fails with this internal compiler error:
```
Error: compilation errors:
 bug: Tried to replace symbol `x` with expression `$t2` in an `Assign` expression in `ExpRewriter`
  ┌─ TEMPFILE:6:17
  │
6 │                 x = f(x);
  │                 ^
```

But this should compile and run successfully.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

#16036 introduced a bug to the replacer in lambda lifter that maps lambda parameters to temp indices, which only works in the spec context. This PR fixes this change by reverting back to the original replacer for lambda body and having a separate replacer for the spec block.

Close #16407 

## How Has This Been Tested?

existing tests and a new test. 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs [hunk 1]
```diff
@@ -628,6 +628,16 @@ impl<'a> ExpRewriterFunctions for LambdaLifter<'a> {
 
         // Rewrite references to Temporary in the new functions body (#12317)
         let mut replacer = |id: NodeId, target: RewriteTarget| {
+            if let RewriteTarget::Temporary(temp) = target {
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:631]: Bring back the original definition of `replacer` before #16036

File: third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs [hunk 2]
```diff
@@ -628,6 +628,16 @@ impl<'a> ExpRewriterFunctions for LambdaLifter<'a> {
...
+                let new_temp = param_index_mapping.get(&temp).cloned().unwrap_or(temp);
+                return Some(ExpData::Temporary(id, new_temp).into_exp());
+            }
+            None
+        };
+        let body = ExpRewriter::new(env, &mut replacer).rewrite_exp(body.clone());
+        let fun_id = FunId::new(fun_name);
+        // Spec rewriter needs to map parameters to temporary indices in the spec
+        let mut spec_replacer = |id: NodeId, target: RewriteTarget| {
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs:640]: Add a separate replacer for rewriting the spec.

**Review by vineethk — APPROVED** [review]

**Review by wrwg — APPROVED** [review]
