### PR TITLE
[Compiler-v2] Fix issue 12198

### LINKED ISSUE #12198: [Bug][Compiler-v2] Unpacking a reference to struct leads to UNPACK_TYPE_MISMATCH_ERROR
# 🐛 Bug

When compiling the following code:

```
module 0x42::pack_unpack_ref {
    struct S {
        f: u64,
        g: u64
    }

    fun unpack_ref(s: &S): (u64, u64) {
        let S{f, g} = s;
        (*f, *g)
    }

}
```

The following error is generated by the bytecode verifier:

```
bug: BYTECODE VERIFICATION FAILED
   ┌─ tests/file-format-generator/pack_unpack_ref.move:1:1
   │
 1 │ ╭ module 0x42::pack_unpack_ref {
 2 │ │     struct S {
 3 │ │         f: u64,
 4 │ │         g: u64
   · │
11 │ │
12 │ │ }
   │ ╰─^ ICE failed bytecode verifier: VMError {
    major_status: UNPACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    message: None,
    exec_state: None,
    location: Module(
        ModuleId {
            address: 0000000000000000000000000000000000000000000000000000000000000042,
            name: Identifier(
                "pack_unpack_ref",
            ),
        },
    ),
    indices: [
        (
            FunctionDefinition,
            0,
        ),
    ],
    offsets: [
        (
            FunctionDefinitionIndex(0),
            1,
        ),
    ],
}
```

The reason can be seen in the bytecode below. At Instr 1, the type should be `&S` instead of `S`

```
module 42.pack_unpack_ref {
struct S {
	f: u64,
	g: u64
}

unpack_ref(Arg0: &S): u64 * u64 /* def_idx: 0 */ {
L0:	loc1: &u64
B0:
	0: MoveLoc[0](Arg0: &S)
	1: Unpack[0](S)
	2: StLoc[1](loc0: &u64)
	3: StLoc[2](loc1: &u64)
	4: MoveLoc[2](loc1: &u64)
	5: ReadRef
	6: MoveLoc[1](loc0: &u64)
	7: ReadRef
	8: Ret
}
}
```

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

This PR closes #12198 by generating the borrow_field instruction for each field when unpacking a reference to a struct.

### Test Plan

Added one unit test and one transactional test to validate the fix.

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 1]
```diff
@@ -1152,6 +1152,48 @@ impl<'env> Generator<'env> {
...
+    fn gen_borrow_field_for_unpack_ref(
+        &mut self,
+        id: &NodeId,
+        str: &QualifiedInstId<StructId>,
+        arg: TempIndex,
+        temps: Vec<TempIndex>,
+        ref_kind: ReferenceKind,
+    ) {
+        let struct_env = self.env().get_struct(str.to_qualified_id());
+        let mut temp_filed_offsets = BTreeMap::new();
```
Comment (wrwg) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:1166]: temp_to_field_offsets

**Review by wrwg — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 2]
```diff
@@ -1152,6 +1152,48 @@ impl<'env> Generator<'env> {
...
+        for (field, input_temp) in struct_env.get_fields().zip(temps.clone()) {
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:1167]: You don't actually need `temp_filed_offsets` (or `temp_to_field_offsets`), as field names should already be unique, and you only use it once:
```
for (field_offset, temp) in struct_env.get_fields().zip(temps.clone()) {
    self.with-reference_mode(|s, entering| {
        ...
```

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: done

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 2 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs:1167]: @brmataptos, I have tried using one loop to do it but there was a borrow issue.
