### PR TITLE
[move-vm] Some fixes for runtime checks

### LINKED ISSUE #17156: [Bug] Paranoid mode does not check if references are being captured when packing a closure
# 🐛 Bug

Consider the following masm transactional test:
```
//# publish --verbose
module 0xc0ffee::m

public fun f(): ||u64
    local x: u64
    ld_u64 0
    st_loc x
    borrow_loc x
    // we are capturing a reference
    pack_closure g, 1
    ret

public fun g(x: &u64): u64
    move_loc x
    read_ref
    ret

public fun h(): u64
    call f
    call_closure<|&u64|u64>
    ret

//# run --verbose
script
use 0xc0ffee::m

fun main()
    call m::h
    pop
    ret
```

If we turn off the static bytecode verifier, then the paranoid mode does not check that references are captured when packing a closure. Instead, we get an invariant violation error in type layout converter.

### PR DESCRIPTION
**Pull request by wrwg**
## Description

- The captured argument types are now checked _before_ the LazyFunction is constructed, which requires to construct layouts. Thus a more descriptive error will be produced than failure in layout construction.
- Types of returned values of a function are checked explicitly. Before, those types would have been checked at some later point implicitly, when the returned values are used. Though the current behavior isn't wrong, the adjusted behavior is more aligned with what the bytecode verifier does.

Closes #17156

## How Has This Been Tested?

New tests, all tests change behavior

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [x] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [ ] Other (specify)

### CODE REVIEW

**Comment by wrwg** [comment]
* **#17157** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17157?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17157?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#17147** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-vm/runtime/src/interpreter.rs [hunk 1]
```diff
@@ -1664,6 +1695,15 @@ impl Stack {
         Ok(args)
     }
 
+    fn last_n_tys_mut(&mut self, n: usize) -> PartialVMResult<&mut [Type]> {
+        if self.value.len() < n {
```
Comment (georgemitenkov) [inline third_party/move/move-vm/runtime/src/interpreter.rs]: You should check `self.types.len()` here, if for whatever reason stacks becomes unbalanced, this may panic otherwise

File: third_party/move/move-vm/runtime/src/interpreter.rs [hunk 2]
```diff
@@ -682,6 +686,33 @@ where
...
+        let expected_ret_tys = current_frame.function.return_tys();
+        if expected_ret_tys.is_empty() {
+            return Ok(());
+        }
+        let given_ret_tys = self.operand_stack.last_n_tys_mut(expected_ret_tys.len())?;
+        for (expected, given) in expected_ret_tys.iter().zip(given_ret_tys) {
+            let ty_args = current_frame.function.ty_args();
+            if ty_args.is_empty() {
+                given.paranoid_check_assignable(expected)?;
+                *given = expected.clone()
```
Comment (georgemitenkov) [inline third_party/move/move-vm/runtime/src/interpreter.rs]: So now we clone a type each time we return something? Why do we even want this at runtime? If we return something, and then do a call using this returned type, we will 1) do type susbstitution => reclone this type again, so below lines are wasteful 2) type check

File: third_party/move/move-vm/runtime/src/interpreter.rs [hunk 3]
```diff
@@ -682,6 +686,33 @@ where
...
+            } else {
+                let expected_inst = self
```
Comment (georgemitenkov) [inline third_party/move/move-vm/runtime/src/interpreter.rs:712]: This is duplicated with function call check for param tys. I am not convinced we need this replacement if all callers check assignability anyway?

File: third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.masm [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+
+//# run --verbose 0x66::ok::assignable
+
+//# publish
+module 0x66::not_ok
+use 0x66::helpers
+
+fun assignable(): (|u64|u32, |u64|u32 has copy+drop)
+    call helpers::f_copy_drop_store
+    call helpers::f
```
Comment (georgemitenkov) [inline third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.masm]: So without your change this is not detected? I think the main issue is that `assignable` here is an entry point, and we do not type final return:
```
// in interpreter.rs for ExitCode::Return
} else {
    return Ok(self.operand_stack.value);
}
```
so seems like we just need to type check there, not? Otherwise if it is not the last frame next user type checks assignability.

File: third_party/move/move-vm/runtime/src/interpreter.rs (hunk 3 above)
Comment (wrwg) [reply third_party/move/move-vm/runtime/src/interpreter.rs:712]: We've discussed that we don't feel comfortable with current treatment, though it (might) still be ok. Consider:

```
fun f(): |u64|u32 { action /* has copy+drop */ }
fun g(x: |u64|u32 has copy+drop)
...
g(f())
```

This passes runtime checks, so caller does _not_ check the constraint of `f` return type. It would if there is a local for the return value of `f`, but this doesn't have to be like this. While it might not be harmful (at least as far as we know, and as of today), it's weird.

File: third_party/move/move-vm/runtime/src/interpreter.rs [hunk 5]
```diff
@@ -682,6 +686,33 @@ where
         }
     }
 
+    // Check whether the values on the operand stack have the expected return types.
+    // The given types will also be replaced by the expected type, thus if a given
+    // type is more specific (assignable) then expected, it will be replaced by the
```
Comment (vineethk) [inline third_party/move/move-vm/runtime/src/interpreter.rs]:
```suggestion
    // type is more specific (assignable) than expected, it will be replaced by the
```

File: third_party/move/move-vm/runtime/src/interpreter.rs [hunk 6]
```diff
@@ -682,6 +686,33 @@ where
...
+    // type known for the value in the caller context.
+    fn check_and_replace_return_tys(&mut self, current_frame: &mut Frame) -> PartialVMResult<()> {
+        let expected_ret_tys = current_frame.function.return_tys();
+        if expected_ret_tys.is_empty() {
```
Comment (vineethk) [inline third_party/move/move-vm/runtime/src/interpreter.rs:703]: Even if we expect the function return no values (based on the function's type signature), we should check that the operand stack is of the expected height (that the function is not adding return values on the stack, which it can do if bytecode verifier is disabled)?

This can also be an issue when there are expected return values: the function could return more than what the type signature says, and those additional return values are not runtime type checked?

File: third_party/move/move-vm/runtime/src/interpreter.rs (hunk 3 above)
Comment (georgemitenkov) [reply third_party/move/move-vm/runtime/src/interpreter.rs:712]: My question is the following: when we call a function, here, `g`, we do

```rust
let ty = self.operand_stack.pop_ty()?;
let expected_ty = &function.local_tys()[i];
if !ty_args.is_empty() {
    let expected_ty = self
        .vm_config
        .ty_builder
        .create_ty_with_subst(expected_ty, ty_args)?;
    // For parameter to argument, use assignability
    ty.paranoid_check_assignable(&expected_ty)?;
} else {
    // Directly check against the expected type to save a clone here.
    ty.paranoid_check_assignable(expected_ty)?;
}
```
so my question was why return of `f` (i.e argument to `g`) not type checked here?

File: third_party/move/move-vm/runtime/src/interpreter.rs (hunk 6 above)
Comment (wrwg) [reply third_party/move/move-vm/runtime/src/interpreter.rs:703]: I do not see a way how we can do that. We only know the expected number of returned values`N` from the functions return type, and we can see whether there are `N` types on the type stack. If there are less, we error, but if there are more, we cannot know whether they belong to some outer invocation. The type stack or operand stack is global and not per call frame.

However, what we can do is add a check at the top level (main) entry point, and I've done this now.

File: third_party/move/move-vm/runtime/src/interpreter.rs (hunk 3 above)
Comment (wrwg) [reply third_party/move/move-vm/runtime/src/interpreter.rs:712]: It is type checked. However, as I showed in the above example, the actual return value of `f` might be `bool` and `g` is in fact expecting a `bool` so that check succeeds. Nevertheless, `f` might have been _declared_ to have type `u64`, which is simply ignored here. While we didn't found a way how this can be exploited it feels brittle and problematic for potential future changes. We don't want to allow `f` to return something else as declared.

File: third_party/move/move-vm/runtime/src/interpreter.rs (hunk 6 above)
Comment (vineethk) [reply third_party/move/move-vm/runtime/src/interpreter.rs:703]: While we can't do it by just looking at the shared operand stack, if we want to do this check, we could do it by "enter function" setting the expected length of the operand stack, and "exit function" checking it.

Comment (wrwg) [reply third_party/move/move-vm/runtime/src/interpreter.rs:703]: Well, lets does this in another PR then. This PR can't be in 1.34 if we don't get it in soon. This here is time critical and this is an orthogonal concern you are raising to the original one, checking return types, to also now check stack balancing. FWIW, in the unlikely case that type checks all succeed with unbalanced stacks, I check now balancing at the top-level entrypoint, which I think is functionally equivalent.

File: third_party/move/move-vm/types/src/loaded_data/runtime_types.rs [hunk 7]
```diff
@@ -433,6 +433,22 @@ impl Type {
         }
     }
 
+    /// Returns true if the type is variant and can be subject of the assignability rule.
+    /// Currently, this is only the case for function types and immutable references to
+    /// function types.
+    pub fn is_variant(&self) -> bool {
```
Comment (vineethk) [inline third_party/move/move-vm/types/src/loaded_data/runtime_types.rs]: I don't think this is used anywhere? The name can be a bit misleading because of struct variants (although the doc string is clear about what this function does). Consider removing.

Comment (wrwg) [reply third_party/move/move-vm/types/src/loaded_data/runtime_types.rs]: Removed

File: third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.masm (hunk 4 above)
Comment (wrwg) [reply third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.masm]: No, we never type check return, whether entry point or not. We only check if the returned value is stored in a local or passed to some other functions. But the function can declare a very different return type then we check, and we simply ignore this type.
