### PR TITLE
[compiler-v2] Fixes a bug in borrow graph shrinking

### LINKED ISSUE #11221: [Bug][compiler v2] Returned reference flagged as error
Given the following code:

```
   public fun borrow_with_default<Element>(t: &Option<Element>, default_ref: &Element): &Element {
        let vec_ref = &t.vec;
        if (vector::is_empty(vec_ref)) default_ref
        else vector::borrow(vec_ref, 0)
    }
    spec borrow_with_default {
        pragma opaque;
        aborts_if false;
        ensures result == (if (spec_is_some(t)) spec_borrow(t) else default_ref);
    }
```

... reference safety produces the wrong error:

```
error: cannot return a reference derived from local `vec_ref` since it is not a parameter
    ┌─ /Users/wrwg/aptos-core/aptos-move/framework/move-stdlib/sources/option.move:119:9
    │  
119 │ ╭         if (vector::is_empty(vec_ref)) default_ref
120 │ │         else vector::borrow(vec_ref, 0)
    │ │              -------------------------- previous call result
    │ ╰───────────────────────────────────────^ returned here

```

### PR DESCRIPTION
**Pull request by wrwg**
Closes #11221.

When a temporary goes out of scope, nodes related to that temporary are removed from the graph, provided they are not borrowed. This process recursively continues, visiting nodes representing other temporaries, cleaning up large parts of the graph. There was a significant bug in this cleanup, namely ignoring whether a node and a related temporary are also referenced from the outside. This is for example the case if the temporary is used later in the program. It appears this bug only hits if different control flows contribute to the graph, as is in the test case `return_borrowed.move`.

Notice the better error messages in other .exp files come from that previously parts of the graph have been removed. Its the same errors, only with more secondary info from the corrected borrow graph.

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs [hunk 1]
```diff
@@ -52,6 +52,18 @@ pub struct LiveVarInfoAtCodeOffset {
     pub after: BTreeMap<TempIndex, LiveVarInfo>,
 }
 
+impl LiveVarInfoAtCodeOffset {
+    /// Creates a set of the temporaries alive before this program point.
+    pub fn before_set(&self) -> BTreeSet<TempIndex> {
+        self.before.keys().cloned().collect()
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs:58]: Should you check whether the bound value is a non-empty set here?
```
self.before.entries().filter_map(|(k, v) if (!v.usages.is_empty()) { Some(k) } else { None }).cloned().collect()
```
Or is it guaranteed that the set is non-empty if the entry exists?  If the latter is the case, please document it in LiveVarInfo below.

Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs:58]: Why would we need a guarantee for non-emptiness? If the set is empty its empty, which is a valid scenario. (There are program points indeed where no variable is in this set.)

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs:58]: Ah I see what you mean. Yes, it is guaranteed that this set is not empty.

Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs:58]: Done, documented.

**Review by brmataptos — APPROVED** [review]
