### PR TITLE
Add some unit tests and bug fixes for compiler v2

### LINKED ISSUE #10883: [Bug][Compiler-v2] a pure move function treated as an impure one in the spec
# 🐛 Bug

When compiling the following code:

```
module 0x42::move_function_in_spec {
    struct TypeInfo has copy, drop, store {
        account_address: address,
    }
    public native fun type_of<T>(): TypeInfo;

    fun foo<T>() {
        let type_info = type_of<T>();
        let account_address = type_info.account_address;
        spec {
            assert account_address == type_of<T>().account_address;
        };
    }
}
```

the compiler will generate `error: calling impure function move_function_in_spec::type_of is not allowed` while `type_of` is a move function that does not change the global storage.

### LINKED ISSUE #10920: [Bug][Compiler-v2] unexpected type error is raised when generating bytecode
# 🐛 Bug

When compiling the following code:

```
module 0x42::option {
    use std::vector;
    struct Option<Element> has copy, drop, store {
        vec: vector<Element>
    }
    public fun is_none<Element>(t: &Option<Element>): bool {
        vector::is_empty(&t.vec)
    }
    public fun destroy_none<Element>(t: Option<Element>) {
        assert!(is_none(&t), 0x40000);
        let Option { vec } = t;
        vector::destroy_empty(vec)
    }
}
```

the compiler generates the following message:

```
bug: unexpected type: ?7
   ┌─ tests/file-format-generator/option.move:12:5
   │
12 │ ╭     public fun destroy_none<Element>(t: Option<Element>) {
13 │ │         assert!(is_none(&t), 0x40000);
14 │ │         let Option { vec } = t;
15 │ │         vector::destroy_empty(vec)
16 │ │     }
   │ ╰─────^
```

### LINKED ISSUE #10960: [Bug][Compiler-v2] Cannot compile old(...) expressions in the inline spec block
# 🐛 Bug

When compiling the following code:

```
module 0x42::m {
    public fun foo(vec: &mut vector<bool>) {
        spec {
            assert forall k in 0..len(vec): vec[k] == old(vec)[k];
        };
    }
}
```

the following message will be generated:

```
error: invalid old(..) expression in inline spec block
  ┌─ tests/checking/specs/inline_spec_old.move:4:13
  │
4 │             assert forall k in 0..len(vec): vec[k] == old(vec)[k];
  │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │             │                                             │
  │             │                                             this expression is not a function parameter
  │             only a function parameter is allowed in old(..) expressions in inline spec block
```

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

This PR 
- adds test cases for the issue #9330,  #10883, #10884, #10920 and #10960 
- add fix to close #10883, close #10920 and close #10960.

### CODE REVIEW

File: third_party/move/move-model/bytecode/src/lib.rs [hunk 1]
```diff
@@ -49,6 +49,9 @@ pub fn print_targets_with_annotations_for_test(
     let mut text = String::new();
     writeln!(&mut text, "============ {} ================", header).unwrap();
     for module_env in env.get_modules() {
+        if !module_env.is_target() {
```
Comment (rahxephon89) [inline third_party/move/move-model/bytecode/src/lib.rs:52]: prevent panic from `targets.get_targets` below when the module is not the target module

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 2]
```diff
@@ -1549,7 +1549,11 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
                     let ty =
                         self.check_type_with_order(expected_order, loc, &ty, &expected_type, "");
                     let id = self.new_node_id_with_type_loc(&ty, loc);
-                    Pattern::Struct(id, struct_id, args)
+                    let mut std = struct_id;
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/exp_builder.rs:1552]: fix #10920

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 3]
```diff
@@ -114,7 +114,10 @@ pub enum SpecBlockContext<'a> {
     Struct(QualifiedSymbol),
     Function(QualifiedSymbol),
     FunctionCode(QualifiedSymbol, &'a SpecInfo),
-    FunctionCodeV2(QualifiedSymbol, BTreeMap<Symbol, (Loc, Type)>),
+    FunctionCodeV2(
+        QualifiedSymbol,
+        BTreeMap<Symbol, (Loc, Type, Option<TempIndex>)>,
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/module_builder.rs:119]: Option<TempIndex> is necessary to recognize function parameters in the inline spec block

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 4]
```diff
@@ -849,9 +852,9 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
             self.def_ana_constant(&name, def, compiled_module);
         }
 
-        // Analyze all functions.
+        // Analyze all functions in the spec mode
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/module_builder.rs:855]: Separate spec mode and move function mode to fix #10883

File: third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack.exp [hunk 5]
```diff
@@ -9,11 +9,11 @@ module 0x8675309::M {
     }
     private fun t0() {
         {
-          let M::Box<?2>{ f1: f1: u64, f2: f2: u64 } = M::new<u64>();
+          let M::Box<?1>{ f1: f1: u64, f2: f2: u64 } = M::new<u64>();
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack.exp:12]: These `?1` types are pretty poor.  I've filed an issue https://github.com/aptos-labs/aptos-core/issues/10994 to fix this output to be more readable, and hopefully deterministic.  (But don't try to fix it here.)

**Review by brmataptos — COMMENTED** [review]
It would be better to submit a PR for each bug, rather than rolling them all together, though your comments did help to focus attention.

Someone who can read bytecode/disassembly needs to carefully check the outputs, unless we have some tests for it.

File: third_party/move/move-compiler-v2/tests/checking/typing/move_from_type_argument.exp [hunk 6]
```diff
@@ -0,0 +1,7 @@
+
+Diagnostics:
+error: The type argument to `exists` and `global` must be a struct type but `?0` is not
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/move_from_type_argument.exp:3]: The corresponding move file contains the issue number: #10884. The compiler V2 is not able to infer the implicit type parameter for the `move_from` call, leading to this error.

File: third_party/move/move-compiler-v2/tests/checking/specs/move_function_in_spec.move [hunk 7]
```diff
@@ -0,0 +1,26 @@
+// issue 10883
```
Comment (wrwg) [inline third_party/move/move-compiler-v2/tests/checking/specs/move_function_in_spec.move:1]: Just add `#` and it will be linked

File: third_party/move/move-compiler-v2/tests/checking/typing/move_from_type_argument.exp (hunk 6 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/typing/move_from_type_argument.exp:3]: This is resolved anyway in #11010 so no need to stuck on this.

File: third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack.exp (hunk 5 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack.exp:12]: @brmataptos I don't quite get why you are complaining about error messages which this PR doesn't change at all, it just adds new test cases which produce new errors. Can we please focus on the PR at hand? If you have concerns about error messages, can you open issues instead?

**Review by wrwg — APPROVED** [review]

**Review by vineethk — APPROVED** [review]
Nice work! I have a few minor comments, otherwise LGTM.
