### PR TITLE
[compiler-v2] Refactoring of ability instrumentation and checking

### LINKED ISSUE #11223: [Bug][move-compiler-v2] LiveVarAnalysis seems to not properly handle values with non-mut references taken
# 🐛 Bug

Currently, in function `guess_flips_break2` in test case `bug_9717_looponly.move`, on input to LiveVarAnalysis, the last basic block looks like:
```
 37: label L1
     # at tests/checking/inlining/bug_9717_looponly.move:18:18+10
 38: $t18 := copy($t0)
     # at tests/checking/inlining/bug_9717_looponly.move:18:13+2
 39: $t17 := infer($t18)
     # at tests/checking/inlining/bug_9717_looponly.move:20:13+3
 40: $t19 := infer($t0)
     # at tests/checking/inlining/bug_9717_looponly.move:6:60+474
 41: return ()
}
```

On output, it looks like:
```
 40: label L1
     # at tests/checking/inlining/bug_9717_looponly.move:18:18+10
     # live vars:
 41: $t18 := copy($t0)
     # at tests/checking/inlining/bug_9717_looponly.move:18:13+2
     # live vars:
 42: $t17 := move($t18)
     # at tests/checking/inlining/bug_9717_looponly.move:20:13+3
     # live vars:
 43: $t19 := move($t0)
     # at tests/checking/inlining/bug_9717_looponly.move:6:60+474
     # live vars:
 44: return ()
}
```
because the 2 `infer` assignments turn into `move` because the source locations look dead.

This leads to a VM error MOVELOC_EXISTS_BORROW_ERROR failure [in the VM in abstract_state.rs:334](https://github.com/aptos-labs/aptos-core/blob/a1a8dd77e3bad1743a4421a12e0a5e197cae5429/third_party/move/move-bytecode-verifier/src/reference_safety/abstract_state.rs#L334) at instruction 43, since the value t0 is moved away while there is a pending reference in another local (`$t4`, not shown above).

Arguably, it's a bug in the VM that we get a VM error in this case, since all the values should be dead in this case (When bug 9717 was raised we noticed that the VM paranoid mode may be overly conservative in cases like this; there's an issue somewhere else to fix that).  However, PR https://github.com/aptos-labs/aptos-core/pull/11228 has a new test cases illustrating this problem by generating clearly wrong code if the hack introduced there is disabled: [third_party/move/move-compiler-v2/transactional-tests/tests/inlining/bug_11223.move](https://github.com/aptos-labs/aptos-core/pull/11228/commits/80334bd66943ee7e832f5173a15b1d24daae2356#diff-ed0322def2b20cf3c1c4012d25c7e994db5290e1c93972399b4eddb15afef789).

We need to:

1. Refine LiveVarAnalysis to treat use of a var through a reference as use of the underlying var.  Writes of a complete value through a mutable reference might also act as an assignment to "kill" the var.
2. Add a dead-code elimination pass to remove dead assignments and borrows.
3. Optionally, overwrite all references when they first become dead to make safety checking easier for the VM.
4. undo the hack in `CopyTransformation::transform_bytecode` in `livevar_analysis_processor.rs` which references this issue once this is fixed.

### LINKED ISSUE #11671: [Bug][Prover] Annotation for borrow analysis is not available for unreachable code
# 🐛 Bug

The following bytecode will cause panic in [memory instrumentation](https://github.com/aptos-labs/aptos-core/blob/c7375b86ff492862f49ee56e994fed9c8af71709/third_party/move/move-prover/bytecode-pipeline/src/memory_instrumentation.rs#L157):

```
abort_1() /* def_idx: 0 */ {
B0:
	0: LdU64(1)
	1: Abort
B1:
	2: Ret
}
``` 

The reason is that the analysis assumes that the borrow info exists at all code offset but `Ret` does not have the info because it is unreachable.

### LINKED ISSUE #11806: [Bug][move-compiler-v2] copy propagation interaction with drop
# 🐛 Bug

While trying to understand what's going on with constant vectors, I happened to notice some apparent problems with drop:
```
108: $t45 := [104, 101, 108, 108, 111]
109: $t46 := [104, 101, 108, 108, 111]
110: drop($t45)
111: drop($t46)
112: $t44 := ==($t45, $t46)
113: if ($t44) goto 114 else goto 116
```
This is on the transactional-test folding_values.move test, in 8_CopyPropagation.bytecode and on.  The drop is inserted earlier, but CopyPropagation adds uses after the drop operations.  You may want to cherry-pick and/or approve https://github.com/aptos-labs/aptos-core/pull/11804 so you can use the MOVE_COMPILER_DUMP variable to make it easier to generate the .bytecode files (albeit in an awkward place: they show up in transactional-tests/.tmp...).

A sample command line to generate this:
```
UB=1 MOVE_COMPILER_DEBUG=1 MOVE_COMPILER_DUMP=1 MOVE_TEST_DEBUG=1 cargo test -p move-compiler-v2-transactional-tests -- --nocapture folding_values >& test.out
```
then look at `third_party/move/move-compiler-v2/transactional-tests/.tmp*_8_CopyPropagation.bytecode`.  Once you've run it once you may have to select among multiple files matching that `*`.

### LINKED ISSUE #11924: [Bug][compiler-v2] Missing ability checks
# 🐛 Bug

Compiler v2 does not throw an error on certain ability checks, thus causing bytecode verification errors on compilation.

## To reproduce

We should report ability errors on these files (being added in PR https://github.com/aptos-labs/aptos-core/pull/11923): 
`third_party/move/move-compiler-v2/tests/ability-checker/failing/fields.move`
`third_party/move/move-compiler-v2/tests/ability-checker/failing/operators.move`

But we currently do not.

### PR DESCRIPTION
**Pull request by wrwg**
This refactors instrumentation of copy and drop instructions, and checking of abilities in general, closing #11223, which lead us to generate unnecessary copies. Copy instrumentation is now moved after reference safety as borrow information is needed to compute it. The existing ability checking and explicit drop processors have been marged into a new `ability_processor` which deals with instrumenting copies and drops as well as checking ability conformance.

The PR also fixes a bug in safety analysis regarding diverging edges, see the new content at the end of file header.

Closes #11223
Closes #11806
Closes #11671
Closes #11924

### CODE REVIEW

**Comment by wrwg** [comment]
Connect ExitStateAnalysis with last commit. @fEst1ck

File: third_party/move/move-compiler-v2/src/pipeline/exit_state_analysis.rs [hunk 1]
```diff
@@ -70,40 +70,25 @@ impl Display for ExitStatus {
...
-
-impl ExitStateAtCodeOffset {
-    pub fn new(before: ExitState, after: ExitState) -> Self {
-        Self { before, after }
-    }
-}
-
-#[derive(Clone)]
-pub struct ExitStateAnnotation(BTreeMap<CodeOffset, ExitStateAtCodeOffset>);
+pub struct ExitStateAnnotation(BTreeMap<CodeOffset, ExitState>);
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/exit_state_analysis.rs:74]: Mention that this is the exit state before the instruction at the code offset.

File: third_party/move/move-compiler-v2/src/experiments.rs [hunk 2]
```diff
@@ -26,4 +26,7 @@ impl Experiment {
     /// A flag which allows to turn off safety checks, like reference safety.
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/experiments.rs:26]: This comment says reference safety is a permanent part of no-safety experiment, but this PR makes reference safety unconditional (not dependent on this flag).

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 3]
```diff
@@ -239,23 +227,23 @@ impl TestConfig {
                 dump_for_only_some_stages: None,
             }
         } else if path.contains("/copy-propagation/") {
+            pipeline.add_processor(Box::new(LiveVarAnalysisProcessor {}));
+            pipeline.add_processor(Box::new(ReferenceSafetyProcessor {}));
+            pipeline.add_processor(Box::new(ExitStateAnalysisProcessor {}));
+            pipeline.add_processor(Box::new(AbilityProcessor {}));
             pipeline.add_processor(Box::new(AvailCopiesAnalysisProcessor {})); // 0
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/testsuite.rs:234]:
```suggestion
            pipeline.add_processor(Box::new(AvailCopiesAnalysisProcessor {})); // 4
```

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 4]
```diff
@@ -239,23 +227,23 @@ impl TestConfig {
...
             pipeline.add_processor(Box::new(CopyPropagation {})); // 1
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/testsuite.rs:235]:
```suggestion
            pipeline.add_processor(Box::new(CopyPropagation {})); // 5
```

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 5]
```diff
@@ -239,23 +227,23 @@ impl TestConfig {
...
-            pipeline.add_processor(Box::new(LiveVarAnalysisProcessor {
-                with_copy_inference: false,
-            }));
+            pipeline.add_processor(Box::new(LiveVarAnalysisProcessor {}));
             pipeline.add_processor(Box::new(DeadStoreElimination {})); // 3
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/testsuite.rs:237]:
```suggestion
            pipeline.add_processor(Box::new(DeadStoreElimination {})); // 7
```

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 6]
```diff
@@ -239,23 +227,23 @@ impl TestConfig {
...
+            pipeline.add_processor(Box::new(LiveVarAnalysisProcessor {}));
             Self {
                 stop_before_generating_bytecode: false,
                 dump_ast: false,
                 pipeline,
                 generate_file_format: false,
                 dump_annotated_targets: true,
                 // Only dump with annotations after these pipeline stages.
-                dump_for_only_some_stages: Some(vec![0, 1, 3]),
+                dump_for_only_some_stages: Some(vec![2, 3, 4, 5]),
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/testsuite.rs:246]:
```suggestion
                dump_for_only_some_stages: Some(vec![4, 5, 7]),
```

File: third_party/move/move-model/bytecode/src/stackless_bytecode.rs [hunk 7]
```diff
@@ -475,15 +475,13 @@ impl Bytecode {
             Bytecode::Ret(..)
                 | Bytecode::Jump(..)
                 | Bytecode::Abort(..)
+                | Bytecode::Branch(..)
```
Comment (vineethk) [inline third_party/move/move-model/bytecode/src/stackless_bytecode.rs:478]: It is confusing (and incorrect, IMO) to call a `Branch` with two targets that depends on a condition an "unconditional branch".

File: third_party/move/move-model/bytecode/src/stackless_bytecode.rs [hunk 8]
```diff
@@ -475,15 +475,13 @@ impl Bytecode {
...
                 | Bytecode::Call(_, _, Operation::Stop, _, _)
         )
     }
 
     pub fn is_conditional_branch(&self) -> bool {
-        matches!(
-            self,
-            Bytecode::Branch(..) | Bytecode::Call(_, _, _, _, Some(_))
-        )
+        matches!(self, Bytecode::Call(_, _, _, _, Some(_)))
```
Comment (vineethk) [inline third_party/move/move-model/bytecode/src/stackless_bytecode.rs:484]: Same comment as above: why is `Branch` not a conditional branch?

File: third_party/move/move-model/src/ty.rs [hunk 9]
```diff
@@ -2209,14 +2223,15 @@ where
...
+                        ty_arg,
+                        constraints,
+                        is_phantom_position,
+                        ty_arg_abilities,
+                        loc,
+                        on_err,
+                    );
                 }
                 if is_phantom_position {
                     // phantom type parameters don't participte in ability derivations
```
Comment (vineethk) [inline third_party/move/move-model/src/ty.rs:2237]:
```suggestion
                    // phantom type parameters don't participate in ability derivations
```

File: third_party/move/move-model/bytecode/src/stackless_bytecode.rs (hunk 7 above)
Comment (brmataptos) [reply third_party/move/move-model/bytecode/src/stackless_bytecode.rs:478]: It is however true that `Branch` ends a basic block, as there is no fall-through control flow.  Perhaps `is_unconditional_branch` could be renamed to `always_redirects_control_flow` and and `is_conditional_branch` could be renamed to `may_redirect_control_flow`.

File: third_party/move/move-compiler-v2/src/experiments.rs [hunk 10]
```diff
@@ -4,7 +4,7 @@
 
 /// Container for experiments in the compiler. Those can be activated
 /// via the `--experiment=<name>` flag. One can also use the env var
-/// `MOVE_COMPILER_EXP=<comma list>` to activate those flags.
+/// `MVC_EXP=<comma list>` to activate those flags.
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/experiments.rs:7]: If you change compiler controls, please update the best doc we have currently: https://www.notion.so/aptoslabs/Move-Compiler-Debugging-Tips-322ae742b44846da840eec0f4e195a0b#023e370ac7264eebb4215d42d3e545b7

which should be cleaned up and put into a README, I guess.  (I filed an issue to track that https://github.com/aptos-labs/aptos-core/issues/12163).

File: third_party/move/move-compiler-v2/tests/testsuite.rs (hunk 3 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/tests/testsuite.rs:234]: @vineethk You know, this mechanism would be less risky if you (1) added a parameter to `add_processor` for the index, and (2) check that you wind up with a contiguous set.

**Review by brmataptos — COMMENTED** [review]
Haven't looked at ability_processor yet.

File: third_party/move/move-model/src/ty.rs (hunk 9 above)
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Done

File: third_party/move/move-model/bytecode/src/stackless_bytecode.rs (hunk 7 above)
Comment (wrwg) [reply third_party/move/move-model/bytecode/src/stackless_bytecode.rs:478]: Renamed

File: third_party/move/move-compiler-v2/tests/testsuite.rs (hunk 5 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/testsuite.rs]: Done

File: third_party/move/move-compiler-v2/tests/testsuite.rs (hunk 6 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/testsuite.rs]: Done

File: third_party/move/move-compiler-v2/src/experiments.rs (hunk 10 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/experiments.rs:7]: Really should be in markdown than this would be smoother. In any case, the document is in `experiment.rs` and has been updated, the other doc should just point to it I think.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs [hunk 11]
```diff
@@ -0,0 +1,656 @@
...
+        let exit_state = self.exit_state.get_state_at(offset);
+        // Only non-primitive types need a copy
+        let type_needs_copy = |temp: &TempIndex| {
+            let ty = self.target.get_local_type(*temp);
+            !ty.is_primitive()
+        };
+        // Only temps which are used after or borrowed need a copy
+        let temp_needs_copy =
+            |temp| live_var.after.contains_key(temp) || lifetime.before.is_borrowed(*temp);
+        // References always need to be dropped to satisfy bytecode verifier borrow analysis, other values
```
[the remark this answers is not in the document]
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:163]: Fair enough.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs [hunk 12]
```diff
@@ -0,0 +1,656 @@
...
+                } else {
+                    state.moved.insert(*src);
+                }
+            },
+            Assign(_, _, src, AssignKind::Move) => {
+                state.moved.insert(*src);
+            },
+            Call(_, _, _, srcs, ..) => {
+                // For arguments, we also need to check the case that a src is not used after this program point
+                // but again in the argument list. Also, in difference to assign, we only need to copy the
```
[the remark this answers is not in the document]
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:181]: I thought this was referring to the code: `temp_needs_copy(src) || srcs[i + 1..].contains(src)`. I suggested "or" because of this. Re-reading this, I think both would be fine. Ok to leave this as is.

File: third_party/move/move-compiler-v2/tests/testsuite.rs (hunk 3 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/tests/testsuite.rs]: @brmataptos Instead of manually adding index and then checking for contiguity, we could just have a boolean param to indicate whether or not to dump based on this processor. I will follow up with a refactor after these PRs land.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs [hunk 13]
```diff
@@ -0,0 +1,656 @@
...
+            _ => self.check_and_emit_bytecode(code_offset, bc.clone()),
+        }
+        // Insert any drops needed after this program point
+        self.add_implicit_drops(code_offset, &bc)
+    }
+
+    fn check_and_emit_bytecode(&mut self, _code_offset: CodeOffset, bc: Bytecode) {
+        use Bytecode::*;
+        #[allow(clippy::single_match)]
+        match &bc {
```
[the remark this answers is not in the document]
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:280]: Gotcha. I think it would make sense to globally disable if we are frequently adding such exceptions.

I have not tested this, but from reading the lint rule (https://rust-lang.github.io/rust-clippy/master/#/single_match), it seems like if you add any comment in the other match arm (_), then the lint wont complain. That might be another way to go.

**Review by vineethk — APPROVED** [review]
LGTM. Note: I have not carefully reviewed all the test outputs, especially given changes here combined with the other PR this is diffed against.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs]: its the 'not used after but...' where you scanned 'used after or ..'. I changed it to avoid the confusion.

**Review by wrwg — COMMENTED** [review]
This PR has been rebased and aligned with the downstream changes. PTAL

**Comment by fEst1ck** [comment]
Not sure if I missed something. But `ability-check/operators.move` is empty? I tried the original `operators.move` and `fields.move` but https://github.com/aptos-labs/aptos-core/issues/11924 is still not fixed?

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs [hunk 14]
```diff
@@ -0,0 +1,653 @@
+// Copyright © Aptos Foundation
+// SPDX-License-Identifier: Apache-2.0
+
+//! The ability processor checks conformance to Move's ability system as well as instruments
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:4]: Using "instrument" here is confusing.  To "instrument" is to "equip (something) with measuring instruments".  It especially gets confusing below since "instrumentation" (in software, anyway) can mean either the thing adding instruments, or the instruments themselves.

If you love "instrument", then on line 7, you *must* change it to "instrumentation process" or "instrumenter" or something to distinguish the processor from the things inserted.

But I think you should change it to "<something> inference".  Here we are inferring the Copy, Move, and Drop operations which are implicit in the source code.  I wish there were a single name that encapsulated those 3 attributes, but in discussions I've found of Rust, there is some argument that:
- Every assignment is a Move
- An object which has Copy trait just leaves a copy behind

Extending that to Move, 
- By default, every assignment is either a Move or a Copy depending on whether type has Copy
- This analysis simply infers needed Drop operations:
   - a Copy assignment followed by a Drop of the source simplifies to a Move assignment
   - in other situations, we need an explicit Drop operation.

But this doesn't quite jive with Move, which has explicit "move" and "copy" assignments.  The docs even refer to "a move or a copy would be inserted by the compiler".  But calling this "Drop inference"  or "AssignmentDrop inference" would be best for us implementers.

See https://aptos.dev/move/book/variables/#move-and-copy

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs [hunk 15]
```diff
@@ -0,0 +1,656 @@
...
+                    Unpack(mod_id, struct_id, insts) | Pack(mod_id, struct_id, insts) => {
+                        self.check_struct_inst(*id, *mod_id, *struct_id, insts);
+                    },
+                    BorrowGlobal(mod_id, struct_id, insts)
+                    | Exists(mod_id, struct_id, insts)
+                    | MoveFrom(mod_id, struct_id, insts)
+                    | MoveTo(mod_id, struct_id, insts) => {
+                        self.check_key_for_struct(*id, *mod_id, *struct_id, insts)
+                    },
+                    Drop => self.check_drop(*id, srcs[0], || {
```
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:296]: It's not in the parser.  You can always write a function to do it.

**Review by brmataptos — COMMENTED** [review]
Looks good.  A few naming and comment nits.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:296]: Who does the "you" refer to in the final sentence? Is it the developer? If so, I do not quite understand - if you drop something in a function, and call that function, that does not result in a `Drop` bytecode here ...

Also, clarifying that there is no action item for the PR here, I just wanted to understand @brmataptos' comment.

[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:296]: "you" = "the developer".  Yes, there is apparently no way to create a `Drop` bytecode from Move source language.  The *effect* of a `Drop` bytecode can be achieved by a function call that takes a ref parameter and implicitly drops it, though that won't work for an `inline` function.

File: third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp [hunk 16]
```diff
@@ -162,14 +162,6 @@ fun m::some2($t0: &mut m::R, $t1: &mut m::R) {
   0: return ()
 }
 
-
-Diagnostics:
-error: implicit copy of mutable reference in local `x` which is used later in argument list
-   ┌─ tests/live-var/mut_ref.move:41:9
-   │
-41 │         some2(x, x); // expected error because multiple use
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp:170]: We seem to be losing this error in multiple test cases.

**Review by brmataptos — COMMENTED** [review]
Ok, I checked all the tests except the copy-propagation tests which are seemingly all problematic.

We have a few problematic missing errors, notably `foo(t1, t2)` where both params are `&mut s`.

File: third_party/move/move-compiler-v2/src/experiments.rs (hunk 10 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/experiments.rs:7]: Your irony doesn't make a lot of sense here. The source of truth is documentation on code or markdown files. Experiments are a standard concept of our compiler and they are documented in this file. There is not need to go of thousands of lines of code since this here has only a few dozens here.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs (hunk 14 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:4]: Ok. I've seen instrumentation in this context many times, not just for measuring, but I changed it to "transform" since it seems important to you.

File: third_party/move/move-compiler-v2/tests/ability-check/bad_inst.exp [hunk 17]
```diff
@@ -0,0 +1,13 @@
+
+Diagnostics:
+error: type `test::T` is missing ability `drop`
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/bad_inst.exp:3]: This will be fixed with #12036

File: third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.exp [hunk 18]
```diff
@@ -0,0 +1,9 @@
+
+Diagnostics:
+error: cannot move local `r` since it is still used
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.exp:3]: Later is not always correct, that is why I changed this. It can now be also used because it has been previously borrowed and still is.

File: third_party/move/move-compiler-v2/tests/ability-check/invalid_struct_def.exp [hunk 19]
```diff
@@ -1,55 +1,55 @@
...
-  ┌─ tests/ability-checker/invalid_struct_def.move:4:15
+error: missing ability `key`
+  ┌─ tests/ability-check/invalid_struct_def.move:4:15
   │
 4 │     struct Bar { x: Foo<u8> }
   │                  ^
 
-error: Invalid instantiation
-  ┌─ tests/ability-checker/invalid_struct_def.move:6:18
+error: missing ability `key`
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/invalid_struct_def.exp:9]: With #12036 this should be fixed. The problem is really that the location is wrong which this bug addresses.

File: third_party/move/move-compiler-v2/tests/ability-check/operators.move
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/operators.move:1]: Merge issue, fixed

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_global.exp [hunk 20]
```diff
@@ -0,0 +1,14 @@
+
+Diagnostics:
+error: cannot immutably borrow since mutable references exist
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_global.exp:3]: https://github.com/aptos-labs/aptos-core/issues/12214

File: third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp (hunk 16 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp:170]: Livevar doesn't longer check this, so its legit.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 21]
```diff
@@ -710,27 +733,56 @@ impl LifetimeState {
     fn roots(&self, label: &LifetimeLabel) -> BTreeSet<LifetimeLabel> {
         let mut roots = BTreeSet::new();
         let mut todo = self.node(label).parents.iter().cloned().collect::<Vec<_>>();
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:735]: Don't micro-optimize my code please, for a couple of nano seconds. I prefer the more readable version.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 22]
```diff
@@ -710,27 +733,56 @@ impl LifetimeState {
...
+                }
             }
         }
         roots
     }
 
+    /// Returns the transitive children of this node.
+    fn transitive_children(&self, label: &LifetimeLabel) -> BTreeSet<LifetimeLabel> {
+        // Helper function to collect the target nodes of the children.
+        let get_children =
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:761]: Because the lambda is more concise since of inference, its rather idiomatic.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 23]
```diff
@@ -710,27 +733,56 @@ impl LifetimeState {
...
+            |label: &LifetimeLabel| self.node(label).children.iter().map(|e| e.target);
+        let mut result = BTreeSet::new();
+        let mut todo = get_children(label).collect::<Vec<_>>();
+        if todo.is_empty() {
+            result.insert(*label);
+        } else {
+            while let Some(l) = todo.pop() {
+                if !result.insert(l) {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:769]: I like it how it is. Please do not insert your personal taste in code reviews.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 24]
```diff
@@ -1258,7 +1326,16 @@ impl<'env, 'state> LifetimeAnalysisStep<'env, 'state> {
             match kind {
                 AssignKind::Move => self.state.move_ref(dest, src),
                 AssignKind::Copy => self.state.copy_ref(dest, src),
-                _ => panic!("assign kind expected to be Move or Copy"),
+                AssignKind::Inferred => {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1329]: is_borrowed is a public function on the annotation not the analysis state.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 25]
```diff
@@ -1492,11 +1568,17 @@ impl<'env> TransferFunctions for LifeTimeAnalysis<'env> {
...
 
-        // Check borrow safety of the currently active borrow graph for read ref, write ref, and function calls.
+        // Preprocessing: check borrow safety of the currently active borrow graph for read ref,
+        // write ref, and function calls.
         #[allow(clippy::single_match)]
         match instr {
+            // Only handle operations which can take references
             Call(_, _, oper, srcs, ..) => match oper {
-                Operation::ReadRef | Operation::WriteRef | Operation::Function(..) => {
+                Operation::ReadRef
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1577]: I know this and use it all the time, decided to do it like this.

Please do not micromanage my code.

File: third_party/move/move-compiler-v2/tests/ability-check/globals.move
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/globals.move:1]: Merge issue, done

File: third_party/move/move-model/bytecode/src/stackless_bytecode.rs (hunk 8 above)
Comment (wrwg) [reply third_party/move/move-model/bytecode/src/stackless_bytecode.rs:488]: Done

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_mutual_borrows_invalid.exp [hunk 26]
```diff
@@ -47,37 +43,24 @@ error: cannot mutably borrow since immutable references exist
    │         │      mutable borrow attempted here
    │         requirement enforced here
 
-error: same mutable reference in local is also used in other local in same argument list
-   ┌─ tests/reference-safety/v1-tests/call_mutual_borrows_invalid.move:23:9
-   │
-13 │     fun t0(s1: &mut S, _s2: &mut S) {
-   │            -- previous mutable local borrow
-   ·
-23 │         mut_mut(s1, s1);
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_mutual_borrows_invalid.exp:56]: https://github.com/aptos-labs/aptos-core/issues/12214

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_global.exp (hunk 20 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_global.exp:3]: Attributed the bug wrongly. The errors are different between v1 and v2, this is legit in the logic of v2.

**Comment by wrwg** [comment]
Comments addressed, PTAL

**Comment by wrwg** [comment]
> Not sure if I missed something. But `ability-check/operators.move` is empty? I tried the original `operators.move` and `fields.move` but #11924 is still not fixed?

Result of a merge conflicts, brought them back

File: third_party/move/move-compiler-v2/tests/ability-check/invalid_struct_def.exp (hunk 19 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/invalid_struct_def.exp:9]: This is not a test failure, please look closer. This replaces the error message 'invalid instantiation' with 'missing ability `key`', which is certainly better than before. The problem is that this should have pointed to `u8` not to `x`, as I tried to say above.

And this is covered by #12036. Once this is implemented, we will migrate those tests into the frontend and then re-inspect them.

File: third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.exp (hunk 18 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.exp:3]: Done

File: third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp (hunk 16 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp:170]: It is now in reference_safety/multiple_use_invalid, and also a bit more extensively tested, specifically involving reference aliasing.

**Comment by wrwg** [comment]
Comments addressed, PTAL

File: third_party/move/move-compiler-v2/tests/ability-check/ability_violation.exp [hunk 27]
```diff
@@ -0,0 +1,75 @@
...
+   │         ^^^^^^^^^^^^^^^^^^ required because of storage operation here
+   ·
+14 │         move_from_no_key<Impotent>(addr);
+   │         -------------------------------- from a call inlined at this callsite
+
+error: value of type `ability::Impotent` does not have the `drop` ability
+   ┌─ tests/ability-check/ability_violation.move:4:3
+   │
+ 4 │         move_from<T>(addr);
+   │         ^^^^^^^^^^^^^^^^^^ implicitly dropped here since not longer used
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/ability-check/ability_violation.exp:16]: Sorry to keep nitpicking, but "since not longer used" is painful.  "since it is no longer used" (best) or (at least) "since no longer used", please.

File: third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.exp (hunk 18 above)
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.exp]: Nice.

File: third_party/move/move-compiler-v2/tests/ability-check/operators.move
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-compiler-v2/tests/ability-check/operators.move:1]: Still seems missing.

File: third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp (hunk 16 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp:170]: Ok.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs (hunk 25 above)
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1577]: Don't worry, no one is micromanaging your code.  I'm offering a potentially helpful fact about Rust.  If you already know it you can just say so.

**Review by brmataptos — COMMENTED** [review]
Please double-check that you're not missing an .exp file or two.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs [hunk 28]
```diff
@@ -0,0 +1,653 @@
...
+        }
+        // Insert any drops needed after this program point
+        self.add_implicit_drops(code_offset, &bc)
+    }
+
+    fn check_and_emit_bytecode(&mut self, _code_offset: CodeOffset, bc: Bytecode) {
+        use Bytecode::*;
+        #[allow(clippy::single_match)] // For handling of future cases
+        match &bc {
+            Call(id, _, op, srcs, _) => {
```
Comment (fEst1ck) [inline third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:281]: Where did we check drop abilities for eq/neq operations? Or we don't check it here?

**Review by brmataptos — APPROVED** [review]
Nothing crucial.  It would be good if we can clean up the error messages a tad, but up to you.

File: third_party/move/move-compiler-v2/tests/ability-check/ability_violation.exp (hunk 27 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/ability_violation.exp:16]: Done

File: third_party/move/move-compiler-v2/tests/ability-check/operators.move
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/ability-check/operators.move:1]: There are no errors so the exp isn't produced.

File: third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs (hunk 28 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs:281]: There is nothing special about eq/neq, they behave like every other function. See also `CopyDropAnalysis::execute`

**Comment by wrwg** [comment]
I added a fix for #11924, and addressed the error message naming.  For clarity, there are now independent tests covering this bug: `alive_since_borrowed.move` and `operator_drop`.  Thank you for pushing the issue with equalities @fEst1ck : this is actually interesting since this function behaves logical like every other (consumes arguments) but has this additional error so the user does not shoot in there foot. This is bad devx and the function should instead automatically take references for the arguments. We can change the language here perhaps later.
