### PR TITLE
[sdk][typescript] fix unthrottled requests in `waitForTransactionWithResult`

### LINKED ISSUE #3553: [Bug] [sdk][typescript]`waitForTransactionWithResult` doesn't sleep on pending transaction
# 🐛 Bug

The method `waitForTransactionWithResult` of `AptosClient` is skipping the sleep, causing many requests per second.

## To reproduce
Send a transaction using `AptosClient` and wait for the result, there will be many requests in the console

## Expected Behavior
The transaction is checked once per second

### PR DESCRIPTION
**Pull request by hardsetting**
### Description
`AptosClient.waitForTransactionWithResult` is skipping the sleep, causing many requests per second.
This fixes it

### Test Plan
Will test that polling is done once per second as expected

Closes #3553

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3554)

### CODE REVIEW

File: ecosystem/typescript/sdk/src/aptos_client.ts [hunk 1]
```diff
@@ -447,16 +447,11 @@ export class AptosClient {
...
-            continue;
-          }
-          if (e.status >= 400) {
-            throw e;
-          }
-        } else {
+        const isApiError = e instanceof Gen.ApiError;
+        const isErrorStatus = isApiError
+          && e.status !== 404
+          && e.status >= 400;
```
Comment (gregnazario) [inline ecosystem/typescript/sdk/src/aptos_client.ts:453]: You should probably retry on 500s

Comment (hardsetting) [reply ecosystem/typescript/sdk/src/aptos_client.ts:453]: Good point

**Review by leeric92 — APPROVED** [review]

**Review by gregnazario — APPROVED** [review]
