### PR TITLE
Fix another control flow structuring bug

### LINKED ISSUE #17087: [Bug] [Decompiler Bug] Incorrectly handled case during control flow structuring
# 🐛 Bug

The decompiler decompiles the following code (ref: decompiler test case `vector.move`)

```Move
public fun contains<Element>(self: &vector<Element>, e: &Element): bool {
        let i = 0;
        let len = length(self);
        while (i < len) {
            if (borrow(self, i) == e) return true;
            i = i + 1;
        };
        false
}
```
==>
```Move
public fun contains<Element>(self: &vector<Element>, e: &Element): bool {
        let _t2;
        _t2 = 0;
        while (!(!(_t2 < length<Element>(self)) || borrow<Element>(self, _t2) == e)) _t2 = _t2 + 1;
        true
    }
``` 

The function will always return `true`, deviating from the original code. There are many similar cases. This bug is attributed to some issues in the initial control flow structuring.

### PR DESCRIPTION
**Pull request by junxzm1990**
## Description
The decompiler, during control flow structuring, does not consider the impacts of newly inserted loops on previously generated `LoopCont` expressions. See #17087 for an example. This PR fixes this issue.

Close #17087.

## How Has This Been Tested?
- Existing decompiler test cases

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [x] Other (Move Decompiler)

### CODE REVIEW

**Comment by junxzm1990** [comment]
* **#17120** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17120?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#17140](https://github.com/aptos-labs/aptos-core/pull/17140) <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17140?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#17141](https://github.com/aptos-labs/aptos-core/pull/17141) <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17141?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#17111** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17111?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17111?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#17099** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17099?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#17086** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17086?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-model/bytecode/src/astifier.rs [hunk 1]
```diff
@@ -878,6 +881,58 @@ impl Generator {
...
+    /// Loop_n {
+    ///     ...
+    ///   Loop_1 {
+    ///     Loop_0 {
+    ///       LoopCont[x]
+    ///     }
+    ///   }
+    /// }
+    /// and assuming we insert a new block `Loop_t`
+    /// - 0 <= `t` <= n, and is represented by the function argument `idx` below.
```
Comment (wrwg) [inline third_party/move/move-model/bytecode/src/astifier.rs:896]: Did you mean t > x that you keep things?

Comment (junxzm1990) [reply third_party/move/move-model/bytecode/src/astifier.rs:896]: Here I order the loops, from outest to most inner, as `Loop_n`, ..., `Loop_t`, ... `Loop_0`. `LoopCont[x]` exits inside `Loop_0`. Only when `x >= t`, `LoopCont` breaks out or continues into a loop outside of `Loop_t`, and that's when we need to make adjustments.

File: third_party/move/move-model/src/ast.rs [hunk 2]
```diff
@@ -1319,6 +1319,31 @@ impl ExpData {
         LoopNestRewriter {
             loop_depth: 0,
             delta,
+            rewrite: Self::default_nest_rewrite,
+        }
+        .rewrite_exp(self.clone().into_exp())
+    }
+
+    fn default_nest_rewrite(exp: Exp, _: usize, nest: usize, cont: bool, delta: isize) -> Exp {
```
Comment (vineethk) [inline third_party/move/move-model/src/ast.rs:1327]: Would be good to explain the params.

File: third_party/move/move-model/src/ast.rs [hunk 3]
```diff
@@ -1853,18 +1878,14 @@ impl ExpRewriterFunctions for ExpRewriter<'_> {
 struct LoopNestRewriter {
     loop_depth: usize,
     delta: isize,
+    rewrite: fn(Exp, usize, usize, bool, isize) -> Exp, // args: expression, current loop depth, nest of the loop-cont, whether it is a continue, delta to be adjusted on the nest
```
Comment (vineethk) [inline third_party/move/move-model/src/ast.rs]: nit: make the comment a field comment with `///` appearing in the line before this field

**Review by vineethk — APPROVED** [review]
Minor comments, LGTM otherwise.
