### PR TITLE
[compiler] fix issue 18335

### LINKED ISSUE #18335: [Bug][compiler] Compiler panics or reports inconsistent errors when using return inside lambdas (map / for_each)
# 🐛 Bug

## To reproduce

Using `return` inside a lambda passed to `map` or `for_each` on a vector can lead to inconsistent compiler errors or a compiler crash.

### Code snippet to reproduce

```move
public fun return_2(): (bool, u64) {
    let t = T { value: vector[42u8] };

    t.value.map(|e| {
        return 1;
    });

    (false, 0)
}
```

Compiler error:
```
error: Return not currently supported in function-typed arguments (lambda expressions)
  ┌─ /Users/logan/test_code_temp/sources/test.move:327:13
  │
327 │             return 1
  │             ^^^^^^^^
```
This behavior is expected.

⸻

Changing the return value to a tuple:
```move
public fun return_2(): (bool, u64) {
    let t = T { value: vector[42u8] };

    t.value.map(|e| {
        return (true, 42u64);
    });

    (false, 0)
}
```
Compiler error:
```
error: tuple type `(bool, u64)` is not allowed as a type argument
  ┌─ /Users/logan/test_code_temp/sources/test.move:323:9
  │
323 │ ╭         t.value.map(|e|{
324 │ │             return (true, 42u64)
325 │ │         });
    │ ╰──────────^
    │
  ┌─ /Users/logan/.move/.../vector.move:545:36
  │
545 │     public inline fun map<Element, NewElement>(
    │                                    ---------- declaration of type parameter `NewElement`
    │
    = required by instantiating type parameter `NewElement` of function `map`

```
⸻

Using for_each causes the compiler to panic:
```move
public fun return_2(): (bool, u64) {
    let t = T { value: vector[42u8] };

    t.value.for_each(|e| {
        return (true, 42u64);
    });

    (false, 0)
}
```
Stack trace / error message
```
thread 'main' panicked at third_party/move/move-model/src/ty.rs:3073:25:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Expected behavior
	•	return inside lambdas should be consistently rejected with a clear compiler error if unsupported.
	•	The compiler should not panic or crash in any case.

System information
	•	Aptos Core Version:
	•	Rust Version:
	•	Computer OS:

Additional context
	•	The error message for tuple return inside map is confusing and appears unrelated.
	•	The panic when using for_each indicates a compiler bug.

### PR DESCRIPTION
**Pull request by junxzm1990**
## Description
This PR fixes issue #18335.

At the high level, the bug lies in error reporting during type resolution. When reporting an error, `message_with_hints_and_labels` (https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-model/src/ty.rs#L3245) relies on both `ErrorMessageContext` and `TypeUnificationError` to report the error. However, the `ErrorMessageContext` may not match the actual context where `TypeUnificationError` happens, leading to confusing err msgs or even panics in rare cases.

Below is an example simplified from the case reported in the issue:
```Move
1. module 0x99::bug_18335 {
2.    struct S has drop {
3.        x: u64,
4.    }
5.
6.    fun receiver(self: &S, f: |u64|) {
7.        f(self.x);
8.    }
9.
10.    fun test(x: u64) {
11.        let s = S { x: 42 };
12.        let func = |x| {
13.            (x, 1u64)
14.        };
15.        s.receiver(func); // type error happens here, as `func` (of type `|u64|(u64, u64)`) does not match function type `|u64|`
16.    }
17.}
```

When translating line 15 `s.receiver(func)`, type resolution
* sets `ErrorMessageContext` to `ReceiverArgument` (https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-model/src/builder/exp_builder.rs#L4966) 
* checks `func` against `type |u64|` , which recursively goes deeper to check `func`'s arg types and return types (https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-model/src/ty.rs#L2297)
* when checking return types of `func`, the error message context is in principle no longer `ReceiverArgument` of `s.receiver(func)`, but the current code does not care.
* eventually, it will see that the return types of `func` , being `(u64, u64)` and not matching the expected `()`, throwing an `ArityMismatch` error.
* the error reporter will report this error under the context `ReceiverArgument` and error type `ArityMismatch` (https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-model/src/ty.rs#L3038). 
* in usual cases, the message will say `the receiver function takes xx arguments but yy were provided`, which is confusing.
* in the case above, a panic due to int underflow will happen at https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-model/src/ty.rs#L3078. Why: the `expected` , representing the number of return values by `f: |u64|`, is 0. Minus 1 from it will underflow.

To fundamentally fix the problem, we may need a redesign to ensure `ErrorMessageContext` always match the actual context where `TypeUnificationError` happens. This is non-trivial, requiring long-term plans.

This PR provides a temporary fix, which introduces two new error codes `FunArgArityMismatch` and `FunResultArityMismatch`, capturing arity mismatch on arguments and return values of function types. The PR also adapts the reporting function to report the two errors directly under the context of function types, ignoring the external `ErrorMessageContext`.

Close #18335

## How Has This Been Tested?
- Existing compiler tests
- New compiler tests: `third_party/move/move-compiler-v2/tests/checking-lang-v2.2/bug_18335.move`

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

---

> [!NOTE]
> Resolves incorrect error context during function-type unification and eliminates an underflow panic.
> 
> - Introduces `FunArgArityMismatch` and `FunResultArityMismatch` and maps them in `map_to_fun_*` to report arg/return arity errors directly for function types
> - Adds `pluralize_be` and updates messages to use correct singular/plural: e.g., `the function takes N arguments but M was/were provided`
> - Adjusts `ErrorMessageContext::arity_mismatch` and related formatting to use `pluralize_be`
> - Adds regression test `tests/checking-lang-v2.2/bug_18335.move` and updates expected outputs across existing tests to the new wording
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0db7b53e68f9d7c77d36f0f9122267d2a21ff9e6. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by junxzm1990** [comment]
* **#18411** <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/18411?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/18411?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-model/src/ty.rs [hunk 1]
```diff
@@ -3278,6 +3290,28 @@ impl TypeUnificationError {
                 vec![],
                 vec![],
             ),
+            TypeUnificationError::FunArgArityMismatch(actual, expected) => (
+                format!(
+                    "expected function type has {} {} but {} {} provided",
+                    expected,
+                    pluralize("argument", *expected),
+                    actual,
+                    if *actual == 1 { "was" } else { "were" }
```
Comment (vineethk) [inline third_party/move/move-model/src/ty.rs]: nit: we might want to make this a function (similar to `pluralize`), and apply it to various messages in the `ErrorMessageContext::arity_mismatch` method as well.

Comment (junxzm1990) [reply third_party/move/move-model/src/ty.rs]: Done!
