### PR TITLE
[move-compiler] Add the name of the file if there is an error during clean, and also clean any files

### LINKED ISSUE #14519: [Bug][move-compiler-v2] stray file in build directory leads to compiler failure
# 🐛 Bug

If the build directory has a file, e.g., `build/.DS_Store`, then the `aptos move build` will cause a failure with a cryptic error:
```
{
  "Error": "Move compilation failed: Not a directory (os error 20)"
}
```
This happens in `BuildPlan::clean()` (called from `BuildPlan::compile_with_driver()`, called from `BuildPlan::compile_no_exit()`, called from `BuildConfig::compile_package_no_exit()`, called from `BuiltPackage::build()`.

The function `BuildPlan::clean()` cleans the build directory of files not built as part of the current build, but it does so with the assumption that every item in the build directory is itself a directory (using `std::fs::remove_dir_all`).  This should be changed to ignore non-directory entries, or perhaps delete files as files.

### PR DESCRIPTION
**Pull request by brmataptos**
## Description

Tolerate a file in the build/ directory during builds.  Add the filename to any errors.

Fixes #14519.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [x] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Some manual testing.

## Key Areas to Review

Trivial change.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/tools/move-package/src/compilation/build_plan.rs [hunk 1]
```diff
@@ -455,7 +455,19 @@
         for dir in std::fs::read_dir(build_root)? {
             let path = dir?.path();
             if !keep_paths.iter().any(|name| path.ends_with(name.as_str())) {
-                std::fs::remove_dir_all(&path)?;
+                if path.is_dir() {
+                    std::fs::remove_dir_all(&path).map_err(|e| {
```
Comment (wrwg) [inline third_party/move/tools/move-package/src/compilation/build_plan.rs:459]: I think you can just use `with_context` on the result see the example here:
https://docs.rs/anyhow/latest/anyhow/trait.Context.html

**Review by wrwg — APPROVED** [review]
Please check the comment

**Review by vgao1996 — APPROVED** [review]
