### PR TITLE
[compiler] fix reference safety checker v3 for non-reference Call destinations

### LINKED ISSUE #19394: [Bug] STLOC_UNSAFE_TO_DESTROY_ERROR caued by missing ref safety check for non-reference Call destinations
# 🐛 Bug

```move
//# publish
module 0xA::M {
    fun foo(): (u64, u64) { (1, 2) }

    fun t1(): u64 {
        let x: u64 = 0;
        let r = &x;
        (x, _) = foo();
        *r
    }
}
```

Compiling this gives:

```
bug: bytecode verification failed with unexpected status code `STLOC_UNSAFE_TO_DESTROY_ERROR`:
Error message: none
  ┌─ .../sources/test.move:8:18
  │
8 │         (x, _) = foo();
  │                  ^^^^^
  │
```

If compile with `MVC_EXP=reference-safety-v3=off`, this will be correctly rejected by:
```
error: cannot assign to borrowed local `x`
  ┌─ .../sources/test.move:8:18
  │
7 │         let r = &x;
  │                 -- previous local borrow
8 │         (x, _) = foo();
  │                  ^^^^^ attempted to assign here
9 │         *r
  │         -- conflicting reference `r` used here
```

Analysis from Claude Code:

`third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs`: `call_operation()` loop over dests only handles reference-typed destinations; non-reference destinations fall through with no borrow check.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

Fixes #19394.

When a non-reference local with an active borrow was assigned to via a tuple call (e.g. `(x, _) = foo()` where `r = &x` is still live), the reference safety checker v3 silently accepted the code. The bytecode verifier then rejected it with `STLOC_UNSAFE_TO_DESTROY_ERROR` — an internal crash rather than a user-facing error.

**Root cause — `call_operation` in `reference_safety_processor_v3.rs`:**

The loop over destination locals only called `replace` (which internally calls `drop` to check for active borrows) for reference-typed destinations. Non-reference destinations fell through with no borrow check:

```rust
for dest in dests {
    let ty = self.ty(*dest);
    if ty.is_mutable_reference() {
        ...
        self.replace(*dest, AbstractValue::Reference(id))
    } else if ty.is_reference() {
        ...
        self.replace(*dest, AbstractValue::Reference(id))
    }
    // non-reference: nothing — borrow check silently skipped
}
```

**Fix:**

After processing reference-typed destinations, release all consumed input references, then `replace` each non-reference destination with `AbstractValue::NonReference`. The ordering is important: input references must be released *before* checking the non-reference destinations. This ensures that a local passed by reference as a call argument (e.g. `(y, _) = foo(&y)`) is not incorrectly flagged — the borrow from the argument is consumed by the call itself. Any remaining borrow after that release represents a genuine use-after-borrow.

## How Has This Been Tested?

- `tests/reference-safety/bug_19394.move` — new regression test: `(x, _) = foo()` with an active `r = &x` used after the call now produces a clear compile-time error: `cannot drop local 'x' which is still borrowed`, with hints pointing to the borrow site and the conflicting use.
- `tests/reference-safety/write_ref_dest_err.exp` — updated baseline: `test_call` (which had the same pattern) now also correctly gets a "cannot drop" error (it was previously missed by the same bug).
- `(y, _) = foo(&y)` — valid pattern where the local is only borrowed by the call's own argument continues to compile without error.

Full `move-compiler-v2` test suite (2220 tests) passes with no regressions.

## Key Areas to Review

- `call_operation` in `reference_safety_processor_v3.rs` — the restructuring moves input-reference release before the non-reference destination drop check. This mirrors the approach in `reference_safety_processor_v2.rs` where `release_refs_not_alive_after()` is called before `check_write_local` for all destinations.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

---

> [!NOTE]
> **Medium Risk**
> Touches core borrow/lifetime checking around function calls; ordering changes could affect which programs are accepted/rejected, though the change is localized and backed by new regression tests.
> 
> **Overview**
> Fixes a hole in reference-safety checker v3 where `Call` destinations with *non-reference* types were not being dropped/checked, allowing code like `(x, _) = foo()` to overwrite a still-borrowed local and only fail later in the bytecode verifier.
> 
> `call_operation` now releases consumed input reference IDs first, then explicitly `replace`s (drops) any non-reference destination locals so active borrows are reported as user-facing compile errors; test baselines are updated and a new regression test (`bug_19394`) is added to lock in the correct diagnostic.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 4db6b66b390169e7b4e04d11835bd6125ebf4f25. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by rahxephon89** [comment]
* **#19409** <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/19409?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/19409?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs [hunk 1]
```diff
@@ -928,10 +928,22 @@ impl LifetimeAnalysisStep<'_, '_> {
             }
         }
 
-        // Release all input references
+        // Release all input references before checking non-reference destinations.
+        // This ensures that a local passed by reference as an argument (e.g.
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs]: can we make these new comments added more succint/not-specific to a particular bug?

**Review by vineethk — APPROVED** [review]
nice!

**Review by wrwg — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety/reference_safety_processor_v3.rs]: updated the comments
