### PR TITLE
[Compiler-v2] Fix type checking issue due to name conflicts between built-in functions and local variables

### LINKED ISSUE #11737: [Bug][Compiler-v2] Name conflicts between local variables and built-in functions
# 🐛 Bug

`len` is a built-in function used in the specification. When compiling the following code:

```
    fun f(gallery: &vector<u64>) {
        let len = 5;
        spec {
            assert len(gallery) >= 0;
        };
    }
```

The following error will be generated:

```
- error: expected `|vector<u64>|?0` but found `u64`
-   ┌─ tests/checking/specs/len.move:5:20
-   │
- 5 │             assert len(gallery) >= 0;
```

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

This PR closes #11737 by returning none in `translate_fun_call_special_cases` in the spec mode when the function call is a built-in function such that no type checking will be performed between the function and a local variable with the same name.

### Test Plan

1) Existing tests pass;
2) Add three unit tests to show the behavior of name conflict in different cases and validate the fix;
3) Compilation of DPN will not show the error in #11737.

### CODE REVIEW

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 1]
```diff
@@ -1943,6 +1943,15 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
                 if n.value.as_str() == "update_field" {
                     return Some(self.translate_update_field(expected_type, loc, generics, args));
                 }
+                let builtin_module = self.parent.parent.builtin_module();
+                let full_name = QualifiedSymbol {
+                    module_name: builtin_module,
+                    symbol: self.symbol_pool().make(&n.value),
+                };
+                // For other built-in functions, type check is performed in translate_call
+                if self.parent.parent.spec_fun_table.get(&full_name).is_some() {
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/exp_builder.rs:1952]:
```suggestion
                if self.parent.parent.spec_fun_table.contains_key(&full_name) {
```

**Review by vineethk — APPROVED** [review]
Minor comment, LGTM otherwise.

**Comment by wrwg** [comment]
I added a comment to the bug, but I think this error is correct behavior.

**Comment by brmataptos** [comment]
You need a test case for each of the following also **used in a spec**:
- user-defined function len 
- user-defined variable len
and enough context to discern how the prover is interpreting it.

**Comment by rahxephon89** [comment]
> You need a test case for each of the following also **used in a spec**:
> 
> * user-defined function len
> * user-defined variable len
>   and enough context to discern how the prover is interpreting it.

Two more tests are added.

**Review by brmataptos — APPROVED** [review]
