### PR TITLE
[compiler][trivial] fix remap of TransformedCodeChunk in peephole optimization

### LINKED ISSUE #17393: [Bug] Code chunk offset out of bounds in peephole optimizer
# 🐛 Bug

```
//# publish
module 0xCAFE::Module0 {
    struct S has copy, drop ;
    enum E has copy, drop {
        V1 { f1: u8, f2: S, },
        V2,
    }
    public fun f() {
         match (E::V2) {
            E::V1 { f2: S, .. } => &(*(&true) && true),
            _ => &(*(&true) && true),
        };
    }
}
```

Compiling this would cause a panic:

```
thread 'main' panicked at third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/optimizers.rs:61:44:
index out of bounds: the len is 35 but the index is 35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Removing `E::V1.f1` or `E::V2` or simplifying `&(*(&true) && true)` will make it compile.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

In peephole optimization, the API `optimize` takes a code block `input` in and generates optimized code block `output` together with `original_offsets` where `output[i]` corresponds to the `input[original_offsets[i]]`. This PR closes #17393 by removing redundant remap call in the method `optimize`.

## How Has This Been Tested?

Added a new test

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs [hunk 1]
```diff
@@ -62,7 +63,7 @@ impl BasicBlockOptimizerPipeline {
                 // Number of basic blocks changed, re-run the basic-block
                 // optimization pipeline again on the new basic blocks.
                 cfg = optimized_cfg;
-                code_chunk = optimized_code_chunk.remap(code_chunk.original_offsets);
+                code_chunk = optimized_code_chunk.remap(original_offsets.clone());
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs]: I am not convinced this is the right fix: each round remaps to the original based on the previous round, so always remapping with original may not be correct. Let me come up with an example.

Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs]: peephole

Consider the attached figure, which shows 2 rounds of optimization of bytecode: 
`[a, b, c, d, e]` -> (delete `d`)
`[a, b, c, e]` ->  (delete `e`)
`[a, b, e]`. 

The first column is the original offsets of the transformed chunk, the second column gives the index for ease of reasoning, the third column is the bytecode.

After the first round, where `d` is deleted, the original offsets are: `[0, 1, 2, 4]`. These are remapped based on the previous, which are the original, leading to keeping them as `[0, 1, 2, 4]`.

In the second round, where `c` is deleted, the optimized code chunk is: `[a, b, e]`, with its original offsets being `[0, 1, 3]` (because instruction at index 2, `e`, was at index `3` in `[a, b, c, e]`). This `[0, 1, 3]` needs to be remapped based on the previous round, for which we should use `[0, 1, 2, 4]`, not the original offsets at the beginning `[0, 1, 2, 3, 4]`.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs]: thanks for the detailed example, @vineethk! I think the actual issue is redundant remapping in the function `optimize`. Updated the PR.

Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs]: The new fix seems correct, thanks!

Given that it is easy to introduce changes here without seemingly introducing any test failures, and because this has happened a couple of I think it is worth adding some unit tests here. I can add them, would be great if you can land this PR soon.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs]: @vineethk, the PR is landed
