### PR TITLE
[compiler-v2] Improvements in type unification error messages

### LINKED ISSUE #9861: [Bug] [Compiler-v2] error messages are unclear
# 🐛 Bug

The v2 compiler is currently producing error messages like the following, which are technically true descriptions of conflicts in a set of type constraints describing the program, but are not intuitive to less expert developers.  We should re-visit these error messages and see if they can be clarified.  Fortunately, most of these are now tagged with "(from assignment context)".

```
third_party/move/move-compiler-v2/tests/checking/typing/bind_wrong_type.exp:

error: expected `()` but found `integer` (from assignment context)
   ┌─ tests/checking/typing/bind_wrong_type.move:12:13
   │
12 │         let () = 0;
   │             ^^

error: expected `()` but found `u64` (from assignment context)
   ┌─ tests/checking/typing/bind_wrong_type.move:19:13
   │
19 │         let (): u64 = ();
   │      

error: expected 4 item(s), found 3
   ┌─ tests/checking/typing/bind_wrong_type.move:20:47
   │
20 │         let (x, b, R{f}): (u64, bool, R, R) = (0, false, R{f: 0});
   │    

error: expected 4 item(s), found 3
   ┌─ tests/checking/typing/bind_wrong_type.move:20:13
   │
20 │         let (x, b, R{f}): (u64, bool, R, R) = (0, false, R{f: 0});
   │                                                    ^^^^^^^^^^^^^^^^^^^
```

### LINKED ISSUE #9863: [Bug] [compiler-v2] Discuss and resolve the "invalid call" language with a larger group to get closure
# 🐛 Bug

Compiler v2 is currently emitting error messages like

```
error: invalid call of `+`: expected `integer` but found `address` for argument 2
   ┌─ tests/checking/typing/binary_add_invalid.move:15:9
   │
15 │         1 + false + @0x0 + 0;
   │         ^^^^^^^^^^^^^^^^
```

which I object to because '+' is not a function to be called, it's an operator.  Wolfgang disagrees.  To not waste time, I shelved the issue but we should at least discuss it with some potential developers.

## To reproduce

See 
third_party/move/move-compiler-v2/tests/checking/typing/binary_add_invalid.exp

in this PR: https://github.com/aptos-labs/aptos-core/pull/9792/

## Previous discussion may still be available here:

https://github.com/aptos-labs/aptos-core/pull/9792#discussion_r1307842989

### LINKED ISSUE #11055: [Bug][move-compiler-v2] Error messages about expressions inside lambdas are apparently misattributed to the lambda
# 🐛 Bug

PR https://github.com/aptos-labs/aptos-core/pull/11046 corrects some types but produces some confusing error messages.

For example,i third_party/move/move-compiler-v2/tests/checking/typing/lambda.exp, we see: 

```
error: invalid call of `M::foreach`: expected `integer` but found `&?19` for argument 2
   ┌─ tests/checking/typing/lambda.move:67:21
   │
67 │         foreach(&v, |e| sum = sum + e) // expected to cannot infer type
   │                     ^^^^^^^^^^^^^^^^^
```

In some earlier code (commit f8d673f3c8, just after PR #10890) we saw  messages like this:

```
error: invalid call of `+`: expected `integer` but found `&integer` for argument 2
   ┌─ tests/checking/typing/lambda.move:67:37
   │
67 │         foreach(&v, |e| sum = sum + e) // expected to cannot infer type
   │                                     ^

```

which was more informative.  We need to recapture that.

### LINKED ISSUE #11867: [Bug][Compiler-v2] Unclear message for type checking errors
# 🐛 Bug

The error message in [lambda_cast_err](https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler-v2/tests/checking/inlining/lambda_cast_err.exp) is not clear:

```
Diagnostics:
error: invalid call of `vector::fold`: expected `integer` but found `vector<u8>` for argument 3
  ┌─ tests/checking/inlining/lambda_cast_err.move:7:53
  │
7 │         vector::fold(gas_schedule_blob, (0 as u64), |sum, addend| sum + (addend as u64))
  │        
```

The relationship between `vector<u8>` and `argument 3` is indirect.

Related to the PR #11834.

### LINKED ISSUE #11963: [Bug][move-compiler-v2] Lambda parameter return type mismatch yields a confusing error message (make sure it doesn't happen in v2)
# 🐛 Bug

Error message for a lambda parameter with an inconsistent return type is confusing.  For example:

```
    struct VectorExample has key {
        inner: vector<u64>
    }
    
    entry fun remove_vector(caller: &signer, input: vector<u64>) acquires VectorExample {
        let mut_ref = mut_resource<VectorExample>(caller);
        vector::for_each(input, |item| {
            vector::remove(&mut mut_ref.inner, item)
        })
    }
```
Yields the following error in V1:
```
error[E04007]: incompatible types
    ┌─ /opt/git/daily-move/snippets/storage/sources/storage_examples.move:39:9
    │  
 21 │           inner: vector<u64>
    │                         --- Given: 'u64'
    ·  
 39 │ ╭         vector::for_each(input, |item| {
 40 │ │             vector::remove(&mut mut_ref.inner, item)
 41 │ │         })
    │ ╰──────────^ Invalid call of '(std=0x1)::vector::for_each'. Invalid argument for parameter 'f'
    │  
    ┌─ /Users/greg/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/../aptos-stdlib/../move-stdlib/sources/vector.move:264:64
    │
264 │     public inline fun for_each<Element>(v: vector<Element>, f: |Element|) {
    │                                                                --------- Expected: '()'
```

### LINKED ISSUE #12118: [Bug][Compiler-v2] add more context to the error message
# 🐛 Bug

When compiling the following code:

```
script {

fun main() {
    let x: u64;
    x = false
}
}
```

V2 will generate the following error:

```
error: expected `u64` but found `bool` (from assignment or declaration context)
  ┌─ tests/checking/typing/v1-commands/assign_wrong_type.move:6:5
  │
6 │     x = false
  │     ^
```

This message gives very little context on why `u64` is expected. More context info is useful.

### LINKED ISSUE #12234: [compiler-v2] Better error messages for equality ops
With #12162 we brought back the use of operator overloading for dealing with equality on references. This leads to not that nice error messages, e.g.:

```
Diagnostics:
error: no matching declaration of `==`
   ┌─ tests/checking/typing/eq_invalid.move:13:9
   │
13 │         (0: u8) == (1: u128);
   │         ^^^^^^^^^^^^^^^^^^^^
   │
   = outruled candidate `==(&#0, &#0): bool` (expected `&?3` but found `u8` for argument 1)
```

... instead of

```
Diagnostics:
error: invalid call of `==`: expected `u8` but found `u128` for argument 2
   ┌─ tests/checking/typing/eq_invalid.move:13:21
   │
13 │         (0: u8) == (1: u128);
   │                     ^
```

This should be fixed, either by special casing errors for equality, or generally analyzing outruled candidates for better messages.

### PR DESCRIPTION
**Pull request by wrwg**
This overall improves error messages around type unification:

- A new `ErrorMessageContext` is passed into displaying unification errors. This gives more context on why the type error happens. For the resulting variations of error messages see the new test folder `checking/error_context`.
- When a critical pair is detected unification, we now lift it to the top level types. This leads to more consistent messages in each particular context. For instance, if the type of a lanbda is wrong, we now show the full function type and not some confusing sub-context. 
- No more printing of type variables unless actually needed. 
- Various other bug fixes.

This proposes to close the following bugs which have been individually verified, and instead open new more specific bugs as needed for remaining issues:

Closes #9861
Closes #11055
Closes #11867
Closes #11963
Closes #12118
Closes #12234
Closes #9863

### CODE REVIEW

**Review by vineethk — APPROVED** [review]
LGTM (my comments are mostly minor). Let's try to get this in soon!

**Review by rahxephon89 — APPROVED** [review]
LGTM, thanks!

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 1]
```diff
@@ -2999,15 +3001,7 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
-                et.check_type(
-                    loc,
-                    &ty,
-                    &entry.type_,
-                    &format!(
-                        "for `{}` included from schema",
-                        name.display(et.symbol_pool())
-                    ),
-                );
+                et.check_type(loc, &ty, &entry.type_, ErrorMessageContext::General);
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/module_builder.rs:3004]: You've lost some functionality here, at least add a TODO so you know where to insert it in a later PR.

It may be easier to add it now: a new enum value `ErrorMessageContext::InSchema(et)` which can include the appropriate message.

File: third_party/move/move-model/src/ty.rs [hunk 2]
```diff
@@ -1656,31 +1880,25 @@ impl TypeUnificationError {
...
+                error_context.type_mismatch(display_context, actual, expected)
             },
-            TypeUnificationError::ArityMismatch(item, a1, a2) => {
-                format!("{} have different arity ({} != {})", item, a1, a2)
+            TypeUnificationError::ArityMismatch(actual, expected) => {
+                error_context.arity_mismatch(*actual, *expected)
             },
             TypeUnificationError::CyclicSubstitution(t1, t2) => {
+                let context_with_vars = display_context.with_type_vars();
                 format!(
```
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-model/src/ty.rs:1894]: I agree with Vineeth.  This becomes more clear with a few more test cases to show what this looks like in more complex cases:
```
    let (x, y);
    (x, y) = (y, x);
```
or
```
    struct S<T> {
        foo: T,
        bar: (T, T),
    }
    fun t4() {
        let z;
        let q: u64;
        z = S { foo: z, bar: S { foo: z, bar: q } };
    }
```
These yield the following error messages before this PR, and I don't see a good way to make them clear without making them less specific:
```
+error: type unification cycle check failed (`?5 =?= (?5, integer)`, try to annotate type) (from assignment or declaration context)
+   ┌─ tests/checking/typing/recursive_local.move:15:13
+   │
+15 │         (x, y) = (y, (x, 0));
+   │             ^
+
+error: type unification cycle check failed (`?14 =?= (?14, integer)`, try to annotate type) (from assignment or declaration context)
+   ┌─ tests/checking/typing/recursive_local.move:16:13
+   │
+16 │         (x, y) = (y, (x, 0));
+   │             ^
```
and 
```
+error: type unification cycle check failed (`?3 =?= M::S<?3>`, try to annotate type) (from assignment or declaration context)
+   ┌─ tests/checking/typing/recursive_local.move:27:9
+   │
+27 │         z = S { foo: z, bar: S { foo: z, bar: q } };
+   │         ^
+
+error: expected `(?4, ?4)` but found `u64`
+   ┌─ tests/checking/typing/recursive_local.move:27:47
+   │
+27 │         z = S { foo: z, bar: S { foo: z, bar: q } };
+   │                                               ^
+
+error: expected `(?3, ?3)` but found `M::S<?4>`
+   ┌─ tests/checking/typing/recursive_local.move:27:30
+   │
+27 │         z = S { foo: z, bar: S { foo: z, bar: q } };
+   │                              ^^^^^^^^^^^^^^^^^^^^
```
The best we can do may be "Unable to infer type due to cyclic type constraints: try declaring a type."

File: third_party/move/move-compiler-v2/tests/checking/inlining/lambda.exp [hunk 3]
```diff
@@ -43,7 +43,7 @@ module 0x42::LambdaTest2 {
           }
         }
     }
-    spec fun $foreach<T>(v: &vector<#0>,action: |&#0|());
+    spec fun $foreach<T>(v: &vector<#0>,action: |&#0|);
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/inlining/lambda.exp:46]: Any chance we can show the type parameter `T` in these types here?

File: third_party/move/move-compiler-v2/tests/checking/inlining/shadowing_unused.exp [hunk 4]
```diff
@@ -61,8 +61,8 @@ module 0x42::Test {
           }
         }
     }
-    spec fun $foo(f: |(u64, u64)|(),z: u64);
-    spec fun $quux(f: |(u64, u64)|(),_z: u64);
+    spec fun $foo(f: |(u64, u64)|,z: u64);
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/inlining/shadowing_unused.exp:64]: Please file a bug to add a space after comma in these specs.

File: third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp [hunk 5]
```diff
@@ -1,24 +1,24 @@
...
 
-error: expected `S` but found `M::S`
+error: cannot adapt `S` to annotated type `S`
   ┌─ tests/checking/naming/generics_shadowing_invalid.move:8:20
   │
 8 │         let s: S = S {};
   │                    ^^^^
 
-error: invalid call of `M::bar`: expected `M::S` but found `S` for argument 1
+error: cannot pass `S` to a function which expects argument of type `S`
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp:15]: This is no good.  File a new issue if we don't fix it here.

File: third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp [hunk 6]
```diff
@@ -1,24 +1,24 @@
...
   ┌─ tests/checking/naming/generics_shadowing_invalid.move:9:13
   │
 9 │         bar(s1);
   │             ^^
 
-error: expected `S` but found `M::S`
+error: cannot return `S` from a function with result type `S`
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp:21]: Here, too.

File: third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp [hunk 7]
```diff
@@ -12,37 +12,37 @@ error: no function named `not_declared` found
...
 
-error: expected `(num, bool)` but found `bool`
+error: cannot return `bool` from a function with result type `(num, bool)`
    ┌─ tests/checking/specs/expressions_err.move:27:7
    │
 27 │       false // Wrong result type tuple.
    │       ^^^^^
 
-error: invalid call of `M::wrongly_typed_callee`: expected `bool` but found `u256` for argument 2
+error: cannot use `u256` with an operator which expects a value of type `bool`
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp:33]: Using "operator" here is awkward.  Perhaps we can distinguish `Operation::MoveFunction` from other operations?  Also, we've lost the argument number.

File: third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp [hunk 8]
```diff
@@ -12,37 +12,37 @@ error: no function named `not_declared` found
...
    ┌─ tests/checking/specs/expressions_err.move:32:31
    │
 32 │       wrongly_typed_callee(1, 1) // Wrongly typed function application
    │                               ^
 
-error: invalid call of `M::wrongly_typed_fun_arg_callee`: expected `num` but found `bool` for argument 1
+error: cannot use `|num|bool` with an operator which expects a value of type `|num|num`
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp:39]: Nitpick: This error could use the word "type" somewhere before `|num|bool` to make it very clear that it's not an expression.  Perhaps the format pattern could be
```
"value of type `{}` provided for an argument of type `{}`"
```
which would avoid the call/function/operator distinction.

**Review by brmataptos — COMMENTED** [review]
A few error messages need to be fixed or have issues filed.

File: third_party/move/move-model/src/ty.rs [hunk 9]
```diff
@@ -1350,6 +1381,43 @@ impl Substitution {
         }
     }
 
+    /// A version of unification which lifts the critical pair of type mismatch to the top-level types.
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs:1387]: Its a standard notion in type unification. If you look at S<c> and S<d>, and s != d, than this is the critical pair. Added an explanation.

File: third_party/move/move-model/src/ty.rs [hunk 10]
```diff
@@ -1350,6 +1381,43 @@ impl Substitution {
...
+    /// NOTE: we may consider to store both critical pair and context type in the unification error
+    /// for better messages. However, the majority pf type expressions is not very large in Move
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Done

File: third_party/move/move-model/src/ty.rs [hunk 11]
```diff
@@ -1634,13 +1696,175 @@ impl TypeUnificationAdapter {
...
+    Binding,
+    /// The error appears in an assignment, where the rhs is not assignable to the lhs.
+    Assignment,
+    /// The error appears in the argument list of a function.
+    Argument,
+    /// The error appears in the argument of an operator.
+    OperatorArgument,
+    /// The error appears in a type annotation.
+    TypeAnnotation,
+    /// The errors appears in the return expression of a function.
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Done

File: third_party/move/move-model/src/ty.rs [hunk 12]
```diff
@@ -1634,13 +1696,175 @@ impl TypeUnificationAdapter {
...
+    Return,
+    /// The errors appears a general generic context.
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Done

File: third_party/move/move-model/src/ty.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Ok, removed the types and replaced with wording similar as suggested.

File: third_party/move/move-model/src/ty.rs [hunk 13]
```diff
@@ -2088,16 +2322,22 @@ impl<'a> fmt::Display for TypeDisplay<'a> {
                     self.context.subs_opt.and_then(|s| s.constraints.get(idx))
                 {
                     if ctrs.is_empty() {
-                        write!(f, "?{}", idx)
+                        if self.context.display_type_vars {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Done

File: third_party/move/move-model/src/ty.rs [hunk 14]
```diff
@@ -2118,7 +2358,14 @@ impl<'a> TypeDisplay<'a> {
                 struct_env.module_env.get_name().display(env),
                 struct_env.get_name().display(env.symbol_pool())
             )
+        };
+        if let Some(mname) = &self.context.module_name {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs:2388]: Yes, it should also consider `use` declarations, currently doesn't.

File: third_party/move/move-model/src/ty.rs [hunk 15]
```diff
@@ -2118,7 +2358,14 @@ impl<'a> TypeDisplay<'a> {
...
+            let s = format!("{}::", mname.name().display(self.context.env.symbol_pool()));
+            if str.starts_with(&s) {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs]: Done

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 16]
```diff
@@ -417,7 +419,7 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
             self.error(
                 &loc,
                 &format!(
-                    "unable to infer type: `{}`",
+                    "unable to infer instantiation of type `{}` (consider providing type arguments are annotating the type)",
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs]: Done

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 17]
```diff
@@ -2690,14 +2807,17 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
                     } else {
                         None
                     };
+                    let context = if matches!(cand.get_operation(), Operation::MoveFunction(..)) {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs]: Good catch, done.

**Review by wrwg — COMMENTED** [review]
Addressed all comments. Accidentally force pushed.

PTAL

File: third_party/move/move-compiler-v2/tests/checking/inlining/lambda.exp (hunk 3 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/inlining/lambda.exp:46]: In the debug output, the number is more useful IMO.

File: third_party/move/move-compiler-v2/tests/checking/inlining/shadowing_unused.exp (hunk 4 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/inlining/shadowing_unused.exp:64]: For the debug output?

File: third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp (hunk 5 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp:15]: Fixed, the display is now aware of the name clash and does not shorten the name if so.

File: third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp (hunk 6 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing_invalid.exp:21]: Fixed

File: third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp (hunk 7 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp]: Haven't you seen that its distinguishing this all over the place already? Only spec functions where forgotten.

File: third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp (hunk 8 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp]: As I said, pleass go and change all those messages async. I assume you have seen the one central file which defines them now (`ty.rs`).
