### PR TITLE
[Compiler-v2] Check recursive definition for constants

### LINKED ISSUE #14648: [Bug][move-compiler-v2] constants should not be able to refer to other constants
# 🐛 Bug

See the test outputs:
- third_party/move/move-compiler/tests/move_check/typing/constant_allowed_but_not_supported.exp
- third_party/move/move-compiler-v2/tests/checking/typing/constant_allowed_but_not_supported.exp
V2 does not complain about the use of const names in other consts.

In PR #14578 I'm adding a new test case
- third_party/move/move-compiler/tests/move_check/typing/recursive_constant.exp
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp
which shows totally unexpected code generated by V2 in the case of recursive constants.

This needs to be fixed.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR

1) adds checks to only allow referring other constants in constant definition when the language version is at least 2.0.
2) rejects recursive definition of constants.

close #14648

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

1) Update existing test cases;
2) Add a new test to `checking-lang-v1`

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rahxephon89** [comment]
* **#14741** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14741?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rahxephon89 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-compiler/src/expansion/ast.rs [hunk 1]
```diff
@@ -548,6 +548,44 @@ pub enum Exp_ {
 }
 pub type Exp = Spanned<Exp_>;
 
+impl Exp_ {
+    /// Get all names from an expression
+    /// only recursively check on expression types supported in constant definition.
+    pub fn get_names_for_const_exp(&self) -> HashSet<Name> {
```
Comment (vineethk) [inline third_party/move/move-compiler/src/expansion/ast.rs:554]: Could we please use a `BTreeSet` instead? Looks like we iterate through this hashset later, and such iteration order is not deterministic.

File: third_party/move/move-compiler/src/expansion/ast.rs [hunk 2]
```diff
@@ -548,6 +548,44 @@ pub enum Exp_ {
...
+                add_names(exp2);
+            },
+            Self::Block(seq) => {
+                for s in seq.iter() {
+                    if let SequenceItem_::Seq(exp) = &s.value {
+                        add_names(exp);
+                    }
+                }
+            },
+            _ => {},
```
Comment (vineethk) [inline third_party/move/move-compiler/src/expansion/ast.rs:583]: Assuming this is only called in the context of const expressions, would it be better to have an internal error/ICE here?

File: third_party/move/move-compiler/src/expansion/ast.rs (hunk 1 above)
Comment (vineethk) [reply third_party/move/move-compiler/src/expansion/ast.rs]:
```suggestion
    pub fn get_names_from_const_exp(&self) -> HashSet<Name> {
```

File: third_party/move/move-compiler/src/expansion/ast.rs [hunk 3]
```diff
@@ -548,6 +548,44 @@ pub enum Exp_ {
...
+            for n in set.iter() {
+                names.insert(*n);
+            }
+        };
+        match self {
+            Self::Name(access, _) => {
+                names.insert(*access.value.get_name());
+            },
+            Self::Call(_, _, _, exp_vec) | Self::Vector(_, _, exp_vec) => {
+                let _ = exp_vec.value.iter().map(&mut add_names);
```
Comment (vineethk) [inline third_party/move/move-compiler/src/expansion/ast.rs:567]: Is `for_each()` perhaps better suited here?

File: third_party/move/move-compiler/src/expansion/ast.rs (hunk 2 above)
Comment (vineethk) [reply third_party/move/move-compiler/src/expansion/ast.rs:583]: If you decide to go the route of adding an error, then the `Block` case has some silently skipped conditions too.

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 4]
```diff
@@ -875,6 +875,95 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+            )
+        }
+    }
+
+    fn analyze_constant(
+        &mut self,
+        key: &PA::ConstantName,
+        constant_map: &UniqueMap<PA::ConstantName, EA::Constant>,
+        visiting: &mut HashSet<PA::ConstantName>,
+        visited: &mut HashSet<PA::ConstantName>,
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:895]: Might be good to add a brief note about params like `visiting`, `visited`.

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 5]
```diff
@@ -875,6 +875,95 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+        visiting.insert(*key);
+        if let Some(exp) = constant_map.get(key) {
+            let names = exp.value.value.get_names_for_const_exp();
+            for name in names {
+                let const_name = PA::ConstantName(name);
+                let qsym = self.qualified_by_module_from_name(&name);
+                if !self.parent.const_table.contains_key(&qsym) {
+                    continue;
+                }
+                self.check_language_version(
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:921]: Do we have this feature mentioned in the Move book (i.e., since 2.0)?

File: third_party/move/move-compiler/src/expansion/ast.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-compiler/src/expansion/ast.rs]: done

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp [hunk 6]
```diff
@@ -1,9 +1,7 @@
...
-    public fun get_x(): u64 {
-        false
-    }
-    public fun get_y(): u64 {
-        false
-    }
-} // end 0x42::M
+
+Diagnostics:
+error: Found recursive definition of a constant
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp:3]: Is it possible to add all the elements of the recursive cycle, by using notes/labels?

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 7]
```diff
@@ -875,6 +875,95 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+    ) {
+        let qsym = self.qualified_by_module_from_name(&key.0);
+        let loc = self
+            .parent
+            .const_table
+            .get(&qsym)
+            .expect("constant declared")
+            .loc
+            .clone();
+        if visited.contains(key) {
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:906]: You can use `||` to combine these two checks.

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 8]
```diff
@@ -875,6 +875,95 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+            return;
+        }
+        visiting.insert(*key);
+        if let Some(exp) = constant_map.get(key) {
+            let names = exp.value.value.get_names_for_const_exp();
+            for name in names {
+                let const_name = PA::ConstantName(name);
+                let qsym = self.qualified_by_module_from_name(&name);
+                if !self.parent.const_table.contains_key(&qsym) {
+                    continue;
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:919]: Why is this a continue and not an error?

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 9]
```diff
@@ -875,6 +875,95 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+                }
+                self.check_language_version(
+                    &loc,
+                    "referring to other constants",
+                    LanguageVersion::V2_0,
+                );
+                if visited.contains(&const_name) {
+                    return;
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:927]: Why would do this early return? Should we not continue instead, and see if the other names lead to errors? For example:

```
const X: u64 = 1;
const Y: u64 = X + Y;
```

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 10]
```diff
@@ -875,6 +875,95 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+                }
+                if visiting.contains(&const_name) {
+                    self.parent
+                        .env
+                        .error(&loc, "Found recursive definition of a constant");
+                    return;
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:933]: Perhaps add a comment that we return early here before exploring other names to limit such errors to one per const definition?

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp [hunk 11]
```diff
@@ -1,9 +1,7 @@
...
+  ┌─ tests/checking/typing/recursive_constant.move:4:5
+  │
+4 │     const Y: u64 = X;
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp:6]: Could we add some more tests for the recursive check?
- self recursion
- recursion with a more complicated cycle involving expressions

File: third_party/move/move-compiler/src/expansion/ast.rs [hunk 12]
```diff
@@ -548,6 +548,44 @@ pub enum Exp_ {
...
+            Self::UnaryExp(_, exp) => {
+                add_names(exp);
+            },
+            Self::BinopExp(exp1, _, exp2) => {
+                add_names(exp1);
+                add_names(exp2);
+            },
+            Self::Block(seq) => {
+                for s in seq.iter() {
+                    if let SequenceItem_::Seq(exp) = &s.value {
```
Comment (vineethk) [inline third_party/move/move-compiler/src/expansion/ast.rs:578]: Interesting that we allow sequences in const defintions. Is there any use case for this? Should it be disallowed?

Can this sequence contain local bindings that could clash with the const names?

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 8 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:919]: In `def_ana_constant`, `is_valid_for_constant` is called which can give a better error message.

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 5 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:921]: no, in the move book we are still saying it is not supported.

File: third_party/move/move-compiler/src/expansion/ast.rs (hunk 2 above)
Comment (rahxephon89) [reply third_party/move/move-compiler/src/expansion/ast.rs]: I moved the function internally into `analyze_constant` to make sure it will not be called by other functions. Then, all other cases will be handled by `is_valid_for_constant`.

File: third_party/move/move-compiler/src/expansion/ast.rs (hunk 3 above)
Comment (rahxephon89) [reply third_party/move/move-compiler/src/expansion/ast.rs]: done

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 4 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: done

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp (hunk 6 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp]: done

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 9 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: done

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp (hunk 11 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp:10]: done

File: third_party/move/move-model/src/constant_folder.rs [hunk 13]
```diff
@@ -328,9 +328,17 @@ impl<'env> ConstantFolder<'env> {
                     O::Neq => val0
                         .equivalent(val1)
                         .map(|equivalence| V(id, Bool(!equivalence)).into_exp()),
-                    _ => self.constant_folding_error(id, |_| {
```
Comment (rahxephon89) [inline third_party/move/move-model/src/constant_folder.rs:331]: The error can be raised when a constant is not evaluated. Thus modify the error here.

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 14]
```diff
@@ -875,6 +875,137 @@
...
+            .const_table
+            .get(&qsym)
+            .expect("constant declared")
+            .loc
+            .clone();
+        if let Some(index) = visiting.iter().position(|r| r.0 == *key) {
+            self.parent.env.diag_with_labels(
+                Severity::Error,
+                &loc,
+                &format!("Found recursive definition of a constant {}", key),
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:951]:
```suggestion
                &format!("Found recursive definition of a constant `{}`", key),
```

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 15]
```diff
@@ -875,6 +875,137 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+                visiting[index..]
+                    .to_vec()
+                    .iter()
+                    .map(|(name, loc)| (loc.clone(), format!("{} is defined", name)))
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/module_builder.rs:955]:
```suggestion
                    .map(|(name, loc)| (loc.clone(), format!("`{}` is defined here", name)))
```

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 14 above)
Comment (vineethk) [reply third_party/move/move-model/src/builder/module_builder.rs:951]: nit: Also may be add: "; cycle formed by definitions below" or similar.

**Review by vineethk — APPROVED** [review]
LGTM, left minor comments.

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 16]
```diff
@@ -875,6 +875,137 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+                loc,
+                &format!(
+                    "not supported before language version `{}`: {}",
+                    version_min, feature
+                ),
+            )
+        }
+    }
+
+    fn analyze_constant(
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/module_builder.rs:890]: Can we have some documentation of this function?  Also, `analyze_constants`.  These names are painfully generic.

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 8 above)
Comment (brmataptos) [reply third_party/move/move-model/src/builder/module_builder.rs:967]: Is it really a better error message?  I think it would be better if we could say something like "Z is not a constant", rather than 
```
error: Invalid expression in `const`. Constant folding failed due to incomplete evaluation
  ┌─ tests/checking/typing/recursive_constant.move:8:8
  │
8 │        Z + A
  │        ^^^^^
```
I regret that I never realized that the constant names were getting inlined into the code as `Value`, rather than having a more explicit lookup of a constant.  I was too new when I did the constant folding.

Or, as V1 does:
```
error[E04013]: invalid statement or expression in constant
   ┌─ tests/move_check/typing/constant_unsupported_exps.move:45:9
   │
45 │         FLAG;
   │         ^^^^ Other constants are not supported in constants
```

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.move [hunk 17]
```diff
@@ -3,6 +3,13 @@ module M {
     const X: u64 = Y;
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.move:3]: We have `const F: u64 = F;` below

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 8 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:967]: In this test case, both `Z` and `A` are constants but we cannot compute the value because of cyclic dependency. So I think this error message makes sense to me.

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 16 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: done

File: third_party/move/move-compiler-v2/tests/checking-lang-v1/v1-typing/refer_other_constants.exp [hunk 18]
```diff
@@ -0,0 +1,7 @@
+
+Diagnostics:
+error: not supported before language version `2.0`: referring to other constants
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking-lang-v1/v1-typing/refer_other_constants.exp]: done

**Review by brmataptos — APPROVED** [review]
LGTM
