### PR TITLE
[compiler-v2] Auto-freeze arguments of relational operators

### LINKED ISSUE #14060: [Bug][move-compiler-V2] V2 comparing copied mutable references triggers EQUALITY_OP_TYPE_MISMATCH_ERROR
# 🐛 Bug

```
module 0xCAFE::Module0 {
    public fun f() {
        let x = &mut 0u8;
        let y = &mut 1u8;
        x != copy y;
    }
}
```

V1 compiles fine.

V2 fails the bytecode verifier:
```
bug: bytecode verification failed with unexpected status code `EQUALITY_OP_TYPE_MISMATCH_ERROR`. This is a compiler bug, consider reporting it.
  ┌─~/debug_package/sources/repro.move:5:9
  │
5 │         x != copy y;
  │         ^^^^^^^^^^^
```

### LINKED ISSUE #14096: [Bug][move-compiler-v2] Copy mutable ref twice for ==
# 🐛 Bug

```
module 0xCAFE::Module0 {
    public fun function2() {
        let x = &mut 0u8;
        (copy x == copy x);
    }
}
```

This compiles with V1, but V2 will report:
```
error: mutable reference in local `x` requires exclusive access but is borrowed
  ┌─ ~/debug_package/sources/repro.move:4:20
  │
4 │         (copy x == copy x);
  │         -----------^^^^^^-
  │         │          │
  │         │          requirement enforced here
  │         conflicting reference used here

error: same mutable reference in value is also used in other value in argument list
  ┌─ ~/debug_package/sources/repro.move:4:9
  │
3 │         let x = &mut 0u8;
  │                 -------- previous mutable local borrow
4 │         (copy x == copy x);
  │         ^^^^^^^^^^^^^^^^^^ requirement enforced here
```

The operations are safe so probably just a difference in V1/V2's ref safety algorithm.

### PR DESCRIPTION
**Pull request by wrwg**
## Description

Operators like Eq and Neq need to have their reference arguments frozen. This happened until now only for arguments of regular function calls.
    
Fixes #14060
Fixes #14096

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Existing tests updated.

### CODE REVIEW

**Comment by wrwg** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14282?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14282** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14282?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#14280** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14276** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14276?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wrwg and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 1]
```diff
@@ -791,12 +791,14 @@ impl<'env> Generator<'env> {
...
-            Operation::Neq => self.gen_op_call(targets, id, BytecodeOperation::Neq, args),
-            Operation::Lt => self.gen_op_call(targets, id, BytecodeOperation::Lt, args),
-            Operation::Gt => self.gen_op_call(targets, id, BytecodeOperation::Gt, args),
-            Operation::Le => self.gen_op_call(targets, id, BytecodeOperation::Le, args),
-            Operation::Ge => self.gen_op_call(targets, id, BytecodeOperation::Ge, args),
+            Operation::Eq => self.gen_op_call_auto_freeze(targets, id, BytecodeOperation::Eq, args),
+            Operation::Neq => {
+                self.gen_op_call_auto_freeze(targets, id, BytecodeOperation::Neq, args)
+            },
+            Operation::Lt => self.gen_op_call_auto_freeze(targets, id, BytecodeOperation::Lt, args),
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:798]: Why do we need "auto freeze" for `Lt`, `Gt`, `Ge`, `Le`? I don't think references even be arguments to these operations.

I understand that we need it for `==` and `!=`, based on the description here: https://aptos.dev/en/build/smart-contracts/book/equality#typing-with-references.

Comment (wrwg) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs:798]: They might be in the future, once we introduce comparison as a general operator on arbitrary types. Here I anticipated this to avoid subtle errors once this change happens.

**Review by vineethk — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 1 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs:798]: That still isn't a good argument.  Unless we want to allow pointer arithmetic and deterministic field ordering in objects, we have no reason to ever allow anything except `==` and `!=` on references.

But, it probably doesn't hurt anything, so fine.

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs:798]: I'm not quite following. In Rust all comparison operators work on references via the basic `Cmp` trait.
