### PR TITLE
[compiler-v2] Fix file format codegen bug when writing to the same destination again

### LINKED ISSUE #12052: [Bug][compiler-v2] Miscompilation from stackless bytecode to fileformat bytecode
# 🐛 Bug

Certain stackless bytecode can cause miscompilation when being translated to file format bytecode, resulting in silent but serious errors.

The following stackless bytecode (which returns 2):
```
 $t2 := 1
 $t2 := 2
 return $t2
```

produces the following file format bytecode (which incorrectly returns 1):
```
0: LdU64(1)
1: LdU64(2)
2: StLoc[0](loc0: u64)
3: StLoc[0](loc0: u64)
4: MoveLoc[0](loc0: u64)
5: Ret
```

It may take certain optimization orders for such stackless bytecode to be produced (but it may happen otherwise too?). Here is a simple way to reproduce this bug:

1. Checkout the branch `vk/ffgen-bug` of `aptos-core` (https://github.com/aptos-labs/aptos-core/tree/vk/ffgen-bug).
2. `cd third_party/move/move-compiler-v2/transactional-tests`
3. `MVC_EXP=optimize MVC_LOG=debug cargo nextest run ffgen_bug --no-capture`

This runs the compiler on the code (in ffgen_bug.move), producing the above stackless bytecode and ff bytecode:
```
    fun test(): u64 {
        let t = 1;
        t = 2;
        t
    }
```

### PR DESCRIPTION
**Pull request by vineethk**
## Description

Fixes #12052.

When the file format generator is generating code from stackless bytecode, an abstract stack is maintained, that contains locals already pushed onto it. When processing a stackless bytecode instruction that writes to a local (but does not consume it from the stack), if the same local already exists on the abstract stack, then the local needs to be flushed. Otherwise, there will be more than one instance of the local on the abstract stack, and when they gets flushed eventually, the local will be written to in the wrong order (this causes very subtle but dangerous semantic bug, as demonstrated by the newly added test `dead_store_calls_2.move` previously returning incorrect results).

In addition to adding tests specific to these changes (`dead_store_calls_*.move`), I have also added 47 other transactional tests (addressing @brmataptos comment - https://github.com/aptos-labs/aptos-core/pull/12357#pullrequestreview-1944109769e). This required going over all previous copy prop and variable coalescing tests and appropriately converting them into transactional tests by adding asserts and other minor modifications. All these tests now pass.

## Type of Change
- [x] Bug fix

## Which Components or Systems Does This Change Impact?
- [x] Move compiler v2

## How Has This Been Tested?

All existing tests pass.
Added new tests as described above, they also pass.

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 1]
```diff
@@ -649,6 +649,11 @@ impl<'a> FunctionGenerator<'a> {
 
     /// Generate code for the load instruction.
     fn gen_load(&mut self, ctx: &BytecodeContext, dest: &TempIndex, cons: &Constant) {
+        if let Some(pos) = self.stack.iter().position(|e| e == dest) {
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:652]: This file could really use some documented invariants, which would make it easier to reason logically about the code without deep understanding.  Using pattern-matching instead, I note a discrepancy between `gen_load` and other instruction implementations that makes me suspect that this is not the right solution.

Notably, `gen_call()` ends with a call 
```
        self.abstract_push_result(ctx, dest);`
```
while `gen_load()` ends with
```
        self.abstract_push_result(ctx, vec![*dest]);
```
and I don't see why these are not identical.  What's the difference?

**Review by brmataptos — COMMENTED** [review]
We also need a better way to reproduce this bug.  The instructions on the issue are not reproducible as written.  Perhaps we can introduce more test directives to select compiler passes for tests?  I guess also in transactional tests.

**Comment by vineethk** [comment]
> We also need a better way to reproduce this bug. The instructions on the issue are not reproducible as written. Perhaps we can introduce more test directives to select compiler passes for tests? I guess also in transactional tests.

@brmataptos They should be now, I used an personal alias command, which I have now expanded. If it is still not, can you please add a comment in the issue?

**Comment by vineethk** [comment]
> Perhaps we can introduce more test directives to select compiler passes for tests? I guess also in transactional tests.

@brmataptos As I mention in the PR description, in order to reproduce this bug, we would not only need to create a separate compilation pipeline, but also keep an old version of the dead store elimination code. Even with this, it would be very brittle, as other changes in the compiler could easily break this reproduction. It is only after considering all the tradeoffs that I created this PR.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 1 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:652]: > This file could really use some documented invariants, which would make it easier to reason logically about the code without deep understanding.

Agree, but I think it is out of scope for this PR for me to add invariants throughout the file.

> I don't see why these are not identical. What's the difference?

Look at the types of `dest` in those two usages: one is a `&TempIndex`, the other is a `&[TempIndex]`.

**Comment by brmataptos** [comment]
Can you check whether this PR fixes `big_ugly_vector.move` (from https://github.com/aptos-labs/aptos-core/pull/12593/) ?  It's generating incorrect output and I'm suspicious that it's related.

**Comment by vineethk** [comment]
> Can you check whether this PR fixes `big_ugly_vector.move` (from #12593) ? It's generating incorrect output and I'm suspicious that it's related.

I checked and I don't think they are related.

I think it is more related to this bug: https://github.com/aptos-labs/aptos-core/issues/11447#issuecomment-2008278801

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:652]: I mentioned already a few times, as early as end of last year, that this module needs to be extensively rewritten, if not replaced by a different design. (E.g. generating naive stack code, then running a per-block level optimization on the stack  bytecode). Lets not try to improve fundamentals of deprecated code.

There are two problems with this code:

- complexity and henceforth buginess
- very mediocre generated stack code, we have multiple bugs open with examples.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 2]
```diff
@@ -649,6 +649,11 @@ impl<'a> FunctionGenerator<'a> {
...
+            // If `dest` is already on the stack, we need to flush it out (dead store)
+            // before we can reload the constant into `dest`.
+            self.abstract_flush_stack_before(ctx, pos);
```
Comment (wrwg) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:655]: Nice and clear fix.

I wonder whether this could also apply to other assignments, e.g: 

```
  r <- call(f, ..)
  r <- call(g, ..)
```

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 3]
```diff
@@ -649,6 +649,11 @@ impl<'a> FunctionGenerator<'a> {
 
     /// Generate code for the load instruction.
     fn gen_load(&mut self, ctx: &BytecodeContext, dest: &TempIndex, cons: &Constant) {
+        if let Some(pos) = self.stack.iter().position(|e| e == dest) {
+            // If `dest` is already on the stack, we need to flush it out (dead store)
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:653]: You don't actually need to flush it.  You just need to kill it so you can ignore it later.  Perhaps one could overwrite any previous occurrence of `dests` in `self.stack` with a special `TempIndex` which is ignored in `abstract_flush_stack` (which would happen naturally if it is not pinned).  Actually, this suggests that you can restrict your hack to the case where `self.pinned.contains(dest)`.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 2 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:655]: Indeed, it looks like that is necessary.  Perhaps `abstract_push_args` could take `dests` and do the right thing for those (either flush or kill as I mentioned above).

**Comment by brmataptos** [comment]
Oops, I started a review before you marked it as a draft.  You need some test cases for the other `gen_*` operations, such as `gen_call`, this seems simplest:
```
fun t1() { 1 }
fun t2() { 2 }
fun test(): u64 {
    let t = t1();
    t = t2();
    t
}
```
though a case that also uses some sources might be useful, too.

**Review by brmataptos — COMMENTED** [review]
Need some other test cases for some other operations, as Wolfgang mentioned.

I do think we would be better with a way to kill overwritten dests on the stack, rather than having to pop the stack down to them each time.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 3 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:653]: Flush, in case of a dead store ends up just doing a pop, which is why I used `abstract_flush_stack_before`. Not sure if you mean some thing else by "kill it".

**Comment by vineethk** [comment]
> Oops, I started a review before you marked it as a draft. You need some test cases for the other `gen_*` operations, such as `gen_call`, this seems simplest:
> 
> ```
> fun t1() { 1 }
> fun t2() { 2 }
> fun test(): u64 {
>     let t = t1();
>     t = t2();
>     t
> }
> ```
> 
> though a case that also uses some sources might be useful, too.

@brmataptos Thanks for the suggestion. I actually came up with the exact same test case, in addition to some others, based on further exploration trying to address @wrwg's comment. I thought I had analyzed these cases, but realized from my notes that I had only done them from the perspective of flushing sources, not destinations (hence I marked it as draft as soon as I realized it).

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 2 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:655]: There are additional nuances because of which this is not going to be sufficient - because of slightly different patterns when translating different stackless bytecodes.

But I agree with the general point here that we need to catch all the cases.

**Comment by vineethk** [comment]
@wrwg @brmataptos Thank you for the previous round of review. PTAL, I believe I have caught all instances of this bug pattern.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 4]
```diff
@@ -798,6 +805,27 @@ impl<'a> FunctionGenerator<'a> {
...
+        &mut self,
+        ctx: &BytecodeContext,
+        dests: &[TempIndex],
+        sources: &[TempIndex],
+    ) {
+        let dests = BTreeSet::from_iter(dests.iter());
+        let sources = BTreeSet::from_iter(sources.iter());
+        let conflicts = dests.difference(&sources).collect::<BTreeSet<_>>();
+        if let Some(pos) = self.stack.iter().position(|t| conflicts.contains(&t)) {
+            self.abstract_flush_stack_before(ctx, pos);
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:825]: I wonder why coverage warning shows 825 isn't covered?

**Review by brmataptos — APPROVED** [review]
We should file an issue to revisit this at some point, as it's pretty far from optimal.

**Review by wrwg — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 4 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:825]: As I had mentioned in a previous iteration of this PR, reproducing this bug is difficult, unless we keep around other bugs. There were two other bug fixes/improvements that were merged in: variable coalescing and its interaction with certain dead stores (https://github.com/aptos-labs/aptos-core/pull/12571), improved transitive dead store elimination (https://github.com/aptos-labs/aptos-core/pull/12357). With both of these merged in, unfortunately the tests I added here do not reproduce the bug (I had tested the reproduction independently before one or more of those were in).

Based on the issue this PR addresses, I have created these two simple commits to:
1. Showcase the bug: https://github.com/aptos-labs/aptos-core/commit/a634e036dc510f97a480197ffb91cce5ad8b7497. See comment at the end on how to reproduce it.
2. The fix provided in this PR actually does fix the reproducible bug above: https://github.com/aptos-labs/aptos-core/commit/1800749c79b0858cbde1bfc064b7d0cbcc2b9453

Handcrafting the stackless bytecode is one option if we really want to keep around a test that is not fickle, but that is too cumbersome right now, and may only be relevant until we fix many other things/rewrite file format generator.

For now, not taking any further action because of reasons provided above.

**Comment by vineethk** [comment]
> We should file an issue to revisit this at some point, as it's pretty far from optimal.

It it unclear to me whether "this" and "it's" above refer to the specific fix provided here, or various things done by file format generator in general.

If the latter, there are now multiple issue filed about it:
- https://github.com/aptos-labs/aptos-core/issues/9598
- https://github.com/aptos-labs/aptos-core/issues/12540
- https://github.com/aptos-labs/aptos-core/issues/12404

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 4 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:825]: Yeah, an "asm/mvir" primitive that stitches in some specified stackless bytecode at bytecode gen time might be neat, but handling types would make it really hard to implement.
