### PR TITLE
 [compiler v2] Release locals which are introduced but die in the same instruction

### LINKED ISSUE #11483: [Bug][Compiler-v2] BORROWLOC_EXISTS_BORROW_ERROR in the module ristretto255
# 🐛 Bug

The test case [test_scalar_neg_assign](https://github.com/aptos-labs/aptos-core/blob/cd044e81402de0d84163fd0167c4d168bf43097d/aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.move#L1178) and [test_scalar_mul_assign](https://github.com/aptos-labs/aptos-core/blob/cd044e81402de0d84163fd0167c4d168bf43097d/aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.move#L1206) in the module ristretto255 will lead to the following bytecode verification error when using V2:

```
┌── test_scalar_neg_assign ──────
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::ristretto255 rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: BORROWLOC_EXISTS_BORROW_ERROR, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("ristretto255") }), indices: [(FunctionDefinition, 115)], offsets: [(FunctionDefinitionIndex(115), 14)] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::ristretto255,
│     indices: [(FunctionDefinition, 115)],
│     offsets: [(FunctionDefinitionIndex(115), 14)],
│     exec_state: None,
│ }
```

```
┌── test_scalar_mul_assign ──────
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::ristretto255 rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: BORROWLOC_EXISTS_BORROW_ERROR, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("ristretto255") }), indices: [(FunctionDefinition, 115)], offsets: [(FunctionDefinitionIndex(115), 14)] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::ristretto255,
│     indices: [(FunctionDefinition, 115)],
│     offsets: [(FunctionDefinitionIndex(115), 14)],
│     exec_state: None,
│ }
└──────────────────

```

### LINKED ISSUE #11487: [Bug][Compiler-v2] BORROWLOC_UNAVAILABLE_ERROR error in simple_map
# 🐛 Bug

When compiling the [borrow](https://github.com/aptos-labs/aptos-core/blob/f6d6f3d4f082e280992f02e5ff12477a1d4838ef/aptos-move/framework/aptos-stdlib/sources/simple_map.move#L54) function in the simple_map module, Compiler v2 will generate the following bytecode:

```
public borrow<Ty0: store, Ty1: store>(Arg0: &SimpleMap<Ty0, Ty1>, Arg1: &Ty0): &Ty1 {
L0:	loc2: u64
L1:	loc3: vector<Element<Ty0, Ty1>>
B0:
	0: MoveLoc[0](Arg0: &SimpleMap<Ty0, Ty1>)
	1: MoveLoc[1](Arg1: &Ty0)
	2: Call find<Ty0, Ty1>(&SimpleMap<Ty0, Ty1>, &Ty0): Option<u64>
	3: StLoc[2](loc0: Option<u64>)
	4: CopyLoc[2](loc0: Option<u64>)
	5: StLoc[3](loc1: Option<u64>)
	6: ImmBorrowLoc[3](loc1: Option<u64>)
	7: Call option::is_some<u64>(&Option<u64>): bool
	8: BrFalse(10)
B1:
	9: Branch(13)
B2:
	10: LdU64(2)
	11: Call error::invalid_argument(u64): u64
	12: Abort
B3:
	13: MutBorrowLoc[3](loc1: Option<u64>)
	14: Call option::extract<u64>(&mut Option<u64>): u64
	15: StLoc[4](loc2: u64)
	16: ImmBorrowLoc[5](loc3: vector<Element<Ty0, Ty1>>)
	17: MoveLoc[4](loc2: u64)
	18: VecImmBorrow(10)
	19: ImmBorrowFieldGeneric[0](Element.value: Ty1)
	20: Ret
}
```

This code will lead to the bytecode verification error `BORROWLOC_UNAVAILABLE_ERROR`. It seems that loc3 is borrowed without proper initialization.

```
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::simple_map rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: BORROWLOC_UNAVAILABLE_ERROR, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("simple_map") }), indices: [(FunctionDefinition, 0)], offsets: [(FunctionDefinitionIndex(0), 16)] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::simple_map,
│     indices: [(FunctionDefinition, 0)],
│     offsets: [(FunctionDefinitionIndex(0), 16)],
│     exec_state: None,
│ }
```

### LINKED ISSUE #11489: [Bug][Compiler-v2] CALL_BORROWED_MUTABLE_REFERENCE_ERROR in big_vector
# 🐛 Bug

When compiling the [remove](https://github.com/aptos-labs/aptos-core/blob/e91dde9526e06162d60d178bcc7addbbc3113632/aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.move#L128) function in the big_vector module, Compiler v2 will generate the following bytecode (truncated):

```
public remove<Ty0>(Arg0: &mut BigVector<Ty0>, Arg1: u64): Ty0 {
//...
B0:
	0: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	1: StLoc[2](loc0: &mut BigVector<Ty0>)
	2: MoveLoc[2](loc0: &mut BigVector<Ty0>)
	3: FreezeRef
	4: Call length<Ty0>(&BigVector<Ty0>): u64
	5: StLoc[3](loc1: u64)
	6: CopyLoc[1](Arg1: u64)
	7: MoveLoc[3](loc1: u64)
	8: Lt
	9: BrFalse(11)
B1:
	10: Branch(16)
B2:
	11: MoveLoc[0](Arg0: &mut BigVector<Ty0>)
	12: Pop
	13: LdU64(1)
	14: Call error::invalid_argument(u64): u64
	15: Abort
B3:
	16: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	17: ImmBorrowFieldGeneric[0](BigVector.buckets: TableWithLength<u64, vector<Ty0>>)
	18: Call table_with_length::length<u64, vector<Ty0>>(&TableWithLength<u64, vector<Ty0>>): u64
	19: StLoc[4](loc2: u64)
	20: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	21: ImmBorrowFieldGeneric[1](BigVector.bucket_size: u64)
	22: ReadRef
	23: StLoc[5](loc3: u64)
	24: CopyLoc[1](Arg1: u64)
	25: MoveLoc[5](loc3: u64)
	26: Div
	27: LdU64(1)
	28: Add
	29: StLoc[6](loc4: u64)
	30: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	31: MutBorrowFieldGeneric[0](BigVector.buckets: TableWithLength<u64, vector<Ty0>>)
	32: LdU64(1)
	33: StLoc[7](loc5: u64)
	34: CopyLoc[6](loc4: u64)
	35: MoveLoc[7](loc5: u64)
	36: Sub
	37: Call table_with_length::borrow_mut<u64, vector<Ty0>>(&mut TableWithLength<u64, vector<Ty0>>, u64): &mut vector<Ty0>
	38: StLoc[8](loc6: &mut vector<Ty0>)
	39: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	40: ImmBorrowFieldGeneric[1](BigVector.bucket_size: u64)
	41: ReadRef
	42: StLoc[9](loc7: u64)
	43: MoveLoc[1](Arg1: u64)
	44: MoveLoc[9](loc7: u64)
	45: Mod
	46: CopyLoc[8](loc6: &mut vector<Ty0>)
	47: StLoc[10](loc8: &mut vector<Ty0>)
	48: StLoc[11](loc9: u64)
	49: MoveLoc[10](loc8: &mut vector<Ty0>)
	50: MoveLoc[11](loc9: u64)
	51: Call vector::remove<Ty0>(&mut vector<Ty0>, u64): Ty0
	52: StLoc[12](loc10: Ty0)
	53: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	54: ImmBorrowFieldGeneric[2](BigVector.end_index: u64)
	55: ReadRef
	56: LdU64(1)
	57: Sub
	58: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	59: MutBorrowFieldGeneric[2](BigVector.end_index: u64)
	60: StLoc[13](loc11: &mut u64)
	61: CopyLoc[13](loc11: &mut u64)
	62: WriteRef
	63: MoveLoc[13](loc11: &mut u64)
	64: Pop
	65: MoveLoc[8](loc6: &mut vector<Ty0>)
	66: StLoc[14](loc12: &mut vector<Ty0>)
B4:
	67: CopyLoc[14](loc12: &mut vector<Ty0>)
	68: Pop
	69: CopyLoc[6](loc4: u64)
	70: CopyLoc[4](loc2: u64)
	71: Lt
	72: BrFalse(109)
B5:
	73: CopyLoc[0](Arg0: &mut BigVector<Ty0>)
	74: MutBorrowFieldGeneric[0](BigVector.buckets: TableWithLength<u64, vector<Ty0>>)
	75: CopyLoc[6](loc4: u64)
	76: Call table_with_length::borrow_mut<u64, vector<Ty0>>(&mut TableWithLength<u64, vector<Ty0>>, u64): &mut vector<Ty0>
	//...
}
```

This code will lead to the bytecode verification error CALL_BORROWED_MUTABLE_REFERENCE_ERROR. The reason is that at **instr 66**, a mutable reference is stored to **loc12** and it is not dropped at **instr 76**, where another mutable reference is passed to the function call table_with_length::borrow_mut<u64, vector<Ty0>>(&mut TableWithLength<u64, vector<Ty0>>, u64): &mut vector<Ty0>

```
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::big_vector rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: CALL_BORROWED_MUTABLE_REFERENCE_ERROR, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("big_vector") }), indices: [(FunctionDefinition, 12)], offsets: [(FunctionDefinitionIndex(12), 76)] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::big_vector,
│     indices: [(FunctionDefinition, 12)],
│     offsets: [(FunctionDefinitionIndex(12), 76)],
│     exec_state: None,
│ }
└──────────────────
```

### PR DESCRIPTION
**Pull request by wrwg**
Reference analysis did not correctly release temps which are assigned and die inn the same instruction.
    
The first commit shows the issue, the 2nd the solution. See also individual commit message.
  
This also modifies the disassembler to print the function definition index for easier debugging of failures.

This PR is compared against #11510.  There is an obsolete commit 'ristretto' which I can resolve once the other PR lands.

Close #11483, close #11487, close #11489

### CODE REVIEW

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 1]
```diff
@@ -1295,9 +1295,13 @@ impl<'env> TransferFunctions for LifeTimeAnalysis<'env> {
         }
         // After processing, release any locals which are dying at this program point.
         let after_set = alive.after_set();
-        for released in alive.before.keys() {
-            if !after_set.contains(released) {
-                state.release_local(*released, &after_set)
+        let mut release_cands = alive.before.keys().cloned().collect::<BTreeSet<_>>();
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1298]: I think maybe this code can be simplified, but maybe we're still missing a case.  The original loop can be simplified as follows, since the `dests` set should not overlap with the `alive_before` set:
```
for released in alive.before.keys().iter().chain(instr.dests().iter()) {
 ```

But could the `dests` set overlap with the `alive_before` set?

Consider that if local `x` is both a parameter and a dest for a `Bytecode`, then it can be alive before, (optionally) alive after, and also assigned at this point.  Is it possible that the same temporary can be both an operand and a destination of a `Bytecode`, such as:
```
      Assign(id, x, x, Inferred);
      Call(id, x, Opcode, [...x ]);
```
If `x` is alive after the instruction, then we may decide that the operand must be made a `Copy`.  But then the instruction itself will overwrite the input.  Are we handling (or forbidding) these cases?

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1298]: Actually one can have `<x is alive>; x := Call(x); <x is dead>`, that is why we need the set union here. If `x` is alive after the call (or used twice as an argument) then copy inference will have introduced a copy. Its unfortunate that we can't have SSA because of the reference semantics, it would make things clearer, but its not necessarilly needed. Livevar analysis in general works fine with `x := Call(x)`, which is the situation where x is both used and defined in the instruction. In this case, any usage of `x` after instruction is for the `x` we are defining here, whereas the argument to the call is the last use of the 'previous' `x` and thus will be moved into the call. So yes, I believe we are fine.

Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1298]: Well, if you need to consider overlap, it will in still be more efficient to avoid copying the alive.before.keys set:
```
for released in alive.before.keys().iter().chain(instr.dests().iter().filter(|x| !alive.before.contains_key(x)) {
```
or perhaps more readably, using [iter_set](https://docs.rs/iter-set/latest/iter_set/index.html)::[union](https://docs.rs/iter-set/latest/iter_set/fn.union.html#):
```
let dests_set: BTreeSet<_> = instr.dests().into_iter().collect();
for released in iter_set::union(alive.before_keys().iter(), dests_set.iter()) {
```
which allocates more memory (but just for the dests set) but is more readable and might even be more efficient.

File: third_party/move/move-compiler/tests/move_check/inlining/inline_accessing_constant.exp [hunk 2]
```diff
@@ -3,4 +3,48 @@ bug[ICE12001]: BYTECODE GENERATION FAILED
   │
 9 │ module 0xc0ffee::dummy2 {
   │                  ^^^^^^ IR ERROR: Missing constant definition for CC
+Backtrace: Backtrace [
```
Comment (brmataptos) [inline third_party/move/move-compiler/tests/move_check/inlining/inline_accessing_constant.exp:6]: Debugging output.  Better get rid of this to pass the tests.

Comment (wrwg) [reply third_party/move/move-compiler/tests/move_check/inlining/inline_accessing_constant.exp]: Done

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1298]: I think perf is really not an issue here since we are looking at collections which average some 2-4 elements, but I used your 1st solution.
