### PR TITLE
[Compiler-v2] check access for structs

### LINKED ISSUE #11014: [compiler v2] Visibility checker should become responsible to check for private field access
With #11010 field visibility checking does not fit into the type checker anymore, since field access is now handled via type unification which is decoupled from program metadata like visibilities. Instead, the existing bytecode-based visibility checker should handle private fields.

### LINKED ISSUE #12820: [Bug][compiler-v2] Internal complier bug "struct not defined" triggered
# 🐛 Bug

When we compile the following code in v2 (taken from `third_party/move/move-compiler-v2/tests/checking/inlining/resources_invalid.move`):

```
module 0x42::objects {

    struct ReaderRef<phantom T: key> has store {
        addr: address
    }

    public inline fun reader<T: key>(ref: &ReaderRef<T>): &T {
        borrow_global<T>(ref.addr)
    }
}

module 0x42::token {
    use 0x42::objects as obj;

    struct Token has key { val: u64 }

    public fun get_value(ref: &obj::ReaderRef<Token>): u64 acquires Token {
        obj::reader(ref).val
    }
}
```

We get an internal compiler bug "struct not defined".

If we use the v1 compiler, we get this error instead:
```
- Error: error[E14002]: Inlined code invalid in this context
-   ┌─ TEMPFILE:7:26
-   │
- 7 │         borrow_global<T>(ref.addr)
-   │                          ^^^ After inlining: invalid storage operation on external type `0x42::objects::ReaderRef`
```

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR adds the check to guarantee a struct can only be accessed within the module that defines it.

Close #11014 
Close #12820

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

1) Existing tests;
2) Migrated three V1 tests;
3) New tests

## Key Areas to Review

Whether all ways of accessing a struct are covered.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 1]
```diff
@@ -335,7 +335,7 @@ const TEST_CONFIGS: Lazy<BTreeMap<&str, TestConfig>> = Lazy::new(|| {
             include: vec!["/acquires-checker/"],
             exclude: vec![],
             exp_suffix: None,
-            options: opts.clone(),
+            options: opts.clone().set_experiment(Experiment::ACCESS_CHECK, false),
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/tests/testsuite.rs:338]: skip access check for acquires-checker so that the error messages remain the same.

File: third_party/move/move-compiler-v2/tests/v1.matched [hunk 2]
```diff
@@ -430,34 +433,3 @@ move-compiler/tests/move_check/typing/while_body.exp   move-compiler-v2/tests/ch
 move-compiler/tests/move_check/typing/while_body_invalid.exp   move-compiler-v2/tests/checking/typing/while_body_invalid.exp
 move-compiler/tests/move_check/typing/while_condition.exp   move-compiler-v2/tests/checking/typing/while_condition.exp
 move-compiler/tests/move_check/typing/while_condition_invalid.exp   move-compiler-v2/tests/checking/typing/while_condition_invalid.exp
-move-compiler/tests/move_check/parser/aptos_stdlib_attributes.exp   move-compiler-v2/tests/checking/attributes/aptos_stdlib_attributes.exp
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/tests/v1.matched:433]: After Brian's PR to fix the update tool is landed, these will be recovered.

File: third_party/move/move-compiler-v2/tests/v1.unmatched [hunk 3]
```diff
@@ -225,17 +222,3 @@ move-compiler/tests/move_check/verification/{
   single_module_invalid.move,
   single_module_valid.move,
 }
-move-compiler/tests/move_check/unit_test/{
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/tests/v1.unmatched:228]: After Brian's PR to fix the update tool is landed, these will be recovered.

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 4]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+                                format!(
+                                    "Invalid pack operation on external type {}",
+                                    struct_env.get_full_name_str()
+                                ),
+                            );
+                        }
+                    },
+                    _ => {},
+                },
+                ExpData::Assign(_, pat, _) | ExpData::Block(_, pat, _, _) => {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/function_checker.rs:131]: It seems like `Lambda` also has a pattern, is that a missing case?

File: third_party/move/move-compiler-v2/tests/checking/inlining/resources_invalid.exp [hunk 5]
```diff
@@ -1,20 +1,12 @@
...
-    public fun get_value(ref: &objects::ReaderRef<token::Token>): u64
-        acquires token::Token(*)
-     {
-        select token::Token.val<&token::Token>({
-          let (ref: &objects::ReaderRef<token::Token>): (&objects::ReaderRef<token::Token>) = Tuple(ref);
-          BorrowGlobal(Immutable)<token::Token>(select objects::ReaderRef.addr<&objects::ReaderRef<token::Token>>(ref))
-        })
-    }
-} // end 0x42::token
+
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/checking/inlining/resources_invalid.exp:1]: Could we add more inline tests, specifically, inline functions that do each of the restricted cases? We may then want to improve error messages for the inlined cases (like is done for visibility of calls).

File: third_party/move/move-compiler-v2/tests/testsuite.rs (hunk 1 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/tests/testsuite.rs:338]: Could you add this as a comment please?

**Review by vineethk — COMMENTED** [review]
Looking good so far.

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 6]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+                        if mid != caller_module_id {
+                            let qualified_struct_id = mid.qualified(sid);
+                            let struct_env = env.get_struct(qualified_struct_id);
+                            access_error(
+                                env,
+                                &fun_env.get_id_loc(),
+                                id,
+                                "called",
+                                format!(
+                                    "Invalid storage operation on external type `{}`",
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs:92]: Yeah, I think that's the case

File: third_party/move/move-compiler-v2/src/function_checker.rs (hunk 4 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs:131]: This check is performed after inlining. Do we still have Lambda then? cc @brmataptos

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 7]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
 
+fn access_error(env: &GlobalEnv, fun_loc: &Loc, id: &NodeId, oper: &str, msg: String) {
+    let call_details: Vec<_> = [*id]
+        .iter()
+        .map(|node_id| (env.get_node_loc(*node_id), format!("{} here", oper)))
+        .collect();
+    env.diag_with_labels(Severity::Error, fun_loc, &msg, call_details);
+}
+
+/// check a struct can only be accessed within the module that defines it.
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 8]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+}
+
 /// For all function in target modules:
 ///
 /// If `before_inlining`, then
 /// - check that all function calls involving inline functions are accessible;
 /// - warn about unused private functions
 /// Otherwise  (`!before_inlining`):
 /// - check that all function calls *not* involving inline functions are accessible.
+/// - check structs are not accessed across the module boundary.
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 9]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+    if let Some(fun_body) = fun_env.get_def() {
+        let caller_module_id = fun_env.module_env.get_id();
+        fun_body.visit_pre_order(&mut |exp: &ExpData| {
+            match exp {
+                ExpData::Call(id, oper, _) => match oper {
+                    Operation::Exists(_)
+                    | Operation::BorrowGlobal(_)
+                    | Operation::MoveFrom
+                    | Operation::MoveTo
+                        if env.get_node_instantiation(*id)[0].get_struct(env).is_some() =>
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 10]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+                            let qualified_struct_id = mid.qualified(sid);
+                            let struct_env = env.get_struct(qualified_struct_id);
+                            access_error(
+                                env,
+                                &fun_env.get_id_loc(),
+                                id,
+                                "called",
+                                format!(
+                                    "Invalid storage operation on external type `{}`",
+                                    struct_env.get_full_name_str()
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 11]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+                    Operation::Select(mid, sid, fid) if *mid != caller_module_id => {
+                        let qualified_struct_id = mid.qualified(*sid);
+                        let struct_env = env.get_struct(qualified_struct_id);
+                        access_error(
+                            env,
+                            &fun_env.get_id_loc(),
+                            id,
+                            "accessed",
+                            format!(
+                                "Invalid access of field `{}` on external type `{}`",
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 12]
```diff
@@ -56,13 +57,116 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+                        if *mid != caller_module_id {
+                            let qualified_struct_id = mid.qualified(*sid);
+                            let struct_env = env.get_struct(qualified_struct_id);
+                            access_error(
+                                env,
+                                &fun_env.get_id_loc(),
+                                id,
+                                "packed",
+                                format!(
+                                    "Invalid pack operation on external type {}",
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs (hunk 4 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done

File: third_party/move/move-compiler-v2/tests/checking/inlining/resources_invalid.exp (hunk 5 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/inlining/resources_invalid.exp:1]: done

File: third_party/move/move-compiler-v2/src/function_checker.rs [hunk 13]
```diff
@@ -56,13 +57,131 @@ pub fn check_for_function_typed_parameters(env: &mut GlobalEnv) {
...
+        "Invalid operation: {} can only be done within the defining module `{}`",
+        msg,
+        module_env.get_full_name_str()
+    );
+    env.diag_with_labels(Severity::Error, fun_loc, &msg, call_details);
+}
+
+/// check privileged operations on a struct such as storage operation, pack/unpack and field accesses
+/// can only be performed within the module that defines it.
+fn check_previleged_operations_on_structs(env: &GlobalEnv, fun_env: &FunctionEnv) {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/function_checker.rs:82]:
```suggestion
fn check_privileged_operations_on_structs(env: &GlobalEnv, fun_env: &FunctionEnv) {
```

**Review by vineethk — APPROVED** [review]
Very nice! LGTM.

note: I have a comment on a minor typo.

File: third_party/move/move-compiler-v2/src/function_checker.rs (hunk 13 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/function_checker.rs]: done
