### PR TITLE
[compiler] Fixing bug in variance of function types

### LINKED ISSUE #16401: [Bug][compiler] Compiler should not allow variance of vector elements
The following code passes the compiler but fails bytecode verification, since variance isn't allowed for nested vector elements:

```
//# publish
module 0x66::zz {

    public fun eval(_x: u64) {
        let a: |u64|u64 has drop = |x| x + 1;
        let b = vector[a];

        zzz(&b);
    }

    fun zzz(_a: &vector<|u64|u64>) {}
}
```

Results in:

```
processed 2 tasks

task 0 'publish'. lines 1-14:
Error: compilation errors:
 bug: bytecode verification failed with unexpected status code `CALL_TYPE_MISMATCH_ERROR`. This is a compiler bug, consider reporting it.
Error message: none
  ┌─ TEMPFILE:7:9
  │
7 │         zzz(&b);
  │         ^^^^^^^

```

### LINKED ISSUE #16403: [Bug] Compiler creates bytecode verification failure bug when using mut ref arg instead of immut ref
# 🐛 Bug

Consider the following transactional test:
```
//# publish
module 0x66::zz {
    fun apply(f: |&u64|) {
        let x = 0;
        f(&mut x);
    }

    fun test() {
        let func = |x| { *x + 1; };
        apply(func);
    }
}
```

It fails with this error:

```
Error: compilation errors:
 bug: bytecode verification failed with unexpected status code `CALL_TYPE_MISMATCH_ERROR`. This is a compiler bug, consider reporting it.
Error message: none
  ┌─ TEMPFILE:5:9
  │
5 │         f(&mut x);
  │         ^^^^^^^^^
```

However, we should be able to successfully run this (with an appropriate insertion of freezeref?) because of subtyping between `&mut` and `&`.

#### Addendum

We also get the same bytecode verification error in the following cases:

```
//# publish
module 0x66::zz {
    fun apply(f: |&mut u64|) {
        f(&mut 0);
    }

    fun test() {
        let func: |&u64| = |x| { *x + 1; };
        apply(func);
    }
}
```

and 

```
//# publish
module 0x66::zz {
    fun apply(f: |&mut u64|&u64) {
        f(&mut 0);
    }

    fun test() {
        let func: |&mut u64|&mut u64 = |x| { x };
        apply(func);
    }
}
```

### PR DESCRIPTION
**Pull request by wrwg**
## Description

The variance parameter was ignored on unification of function types, allowing variance where it shouldn't. This closes #16401. Moreover, arguments/results of a function type have been using variance which the VM doesn't. This fixes and the type rule is now that function types must match exactly except abilities. We may relax this in the future in lockstep with the VM. This closes #16403.

This also fix a bug in display of function, which had the wrong attempt compacting abilities when defaults are used. This does not work because we also need to represent empty abilities. Leads to some baseline changes.

## How Has This Been Tested?

New tests

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

### CODE REVIEW

**Comment by wrwg** [comment]
* **#16402** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16402?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/16402?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-model/src/ty.rs [hunk 1]
```diff
@@ -2424,44 +2424,42 @@ impl Substitution {
                     .map_err(TypeUnificationError::lift(order, t1, t2))?,
                 ));
             },
-            (Type::Fun(a1, r1, abilities1), Type::Fun(a2, r2, abilities2)) => {
+            (Type::Fun(a1, r1, abilities1), Type::Fun(a2, r2, abilities2))
```
Comment (vineethk) [inline third_party/move/move-model/src/ty.rs:2427]: Could we add the following test case to show that vectors are invariant (when they contain function types with reference parameters)?

```
//# publish
module 0x66::zz {
    fun apply(fv: vector<|&mut u64| has copy + drop>) {
        let x = 0;
        fv[0](&mut x);
    }

    fun test() {
        let func: |&u64| has copy + drop = |x| { *x + 1; };
        apply(vector[func]);
    }
}
```

It currently fails typecheck (as expected for vector invariance).

I filed a related bug https://github.com/aptos-labs/aptos-core/issues/16403, (likely not to be addressed as part of this PR, but linking here due to the relation).

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/move-model/src/ty.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-model/src/ty.rs:2427]: Have a fix in the next PR, also adding the additional example. That became a bit larger as expected, so separated.
