### PR TITLE
[Prover][Move-Model] fix #11532

### LINKED ISSUE #11532: [Prover][Bug] issue with the return type of `update_field`
The return type of `update_field` is supposed to be the type of the struct. However, it's set to be the type of the field in Prover currently.

### How to reproduce
Go to `aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/DPN`, and run `aptos move prove`

```
aptos move prove
error: expected `AccountLimits::Window<CoinType>` but found `u64` (update field)
    ┌─ /Users/jpark/Work/aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/AccountLimits.move:450:9
    │
450 │ ╭         update_field(update_field(receiving,
451 │ │             window_inflow, receiving.window_inflow + amount),
452 │ │             tracked_balance, receiving.tracked_balance + amount)
    │ ╰────────────────────────────────────────────────────────────────^
...
```

### Expected output

Prover proves it without such an error.

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

`update_field(x, f, val): X` is a built-in function in the prover where `x` is an instance of struct `X` , `f` is a field of `X` and `val` is a value that has the same type with `f`. It will return a new instance of `X` where all other fields keep the value of `x` and the field `f` takes the value `val`.

Currently, the function `translate_update_field` contains a constraint check for the field `f`, which is problematic because the expected type of `f` in this constraint is X instead of the type of `f`. 

This PR closes #11532 by fixing the expected type for the field.

### Test Plan

1) Manually check DPN test passes (this will be added to unit test soon);
2) Add two new tests to tests/checking/specs;
3) Existing tests still pass.

### CODE REVIEW

**Review by vineethk — APPROVED** [review]
Referring back to your PR description: are the checks that
1. `f` 's type is compatible with `val`s type, and 
2. `x` is compatible with `X`

both being discharged elsewhere? From a cursory look, it looks like this is the case, but wanted to see if you already had looked into this (to make sure we are not deleting some intended-but-currently-incorrect check in the code removed by this PR).

Also, what are DPN tests?

**Comment by rahxephon89** [comment]
> Referring back to your PR description: are the checks that
> 
> 1. `f` 's type is compatible with `val`s type, and
> 2. `x` is compatible with `X`
> 
> both being discharged elsewhere? From a cursory look, it looks like this is the case, but wanted to see if you already had looked into this (to make sure we are not deleting some intended-but-currently-incorrect check in the code removed by this PR).
> 
> Also, what are DPN tests?

DPN contains all smart contracts from Diem framework. We use this to make sure new changes to the prover/model will not break back-compatibility. @junkil-park will integrate this into the unit test soon.

**Comment by rahxephon89** [comment]
> Referring back to your PR description: are the checks that
> 
> 1. `f` 's type is compatible with `val`s type, and
> 2. `x` is compatible with `X`
> 
> both being discharged elsewhere? From a cursory look, it looks like this is the case, but wanted to see if you already had looked into this (to make sure we are not deleting some intended-but-currently-incorrect check in the code removed by this PR).
> 
> Also, what are DPN tests?

Thanks for double checking the type checking, @vineethk! I did go through the code to make sure the check you mentioned is done. And I don't think constraint check here is necessary. @wrwg

**Review by brmataptos — APPROVED** [review]
Presumably the remaining line
```
let value_exp = self.translate_exp(args[2], &field_type);
```
does the constraint check for field f?

**Comment by rahxephon89** [comment]
> Presumably the remaining line
> 
> ```
> let value_exp = self.translate_exp(args[2], &field_type);
> ```
> 
> does the constraint check for field f?

field_type is obtained from field_map, which already contains the type of f and this line checks `val` has the same type.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 1]
```diff
@@ -2480,18 +2480,6 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
         ) = &args[1].value
         {
             let field_name = self.symbol_pool().make(name.value.as_str());
-            let constraint =
```
Comment (wrwg) [inline third_party/move/move-model/src/builder/exp_builder.rs:2483]: You can't just remove this, because there will be no error reported anylonger if the field doesn't exist. See line 2490 assuming the error that the field does not exist would have been already reported.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 2]
```diff
@@ -2480,18 +2480,6 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
-                Constraint::SomeStruct([(field_name, expected_type.clone())].into_iter().collect());
-            if let Err(e) = self.subs.eval_constraint(
-                &self.unification_context,
-                loc,
-                expected_type,
```
Comment (wrwg) [inline third_party/move/move-model/src/builder/exp_builder.rs:2488]: The problem is that this expected type here is wrong. Instead of the expected type of the expression (which is the struct we are updating) we should put in here the expected type of the value of the field, which is the type of the last value parameter of update_field.

**Review by wrwg — CHANGES_REQUESTED** [review]

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 2 above)
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs:2488]: PS. Adding a few test cases to tests/checking/specs might also be helpful. We should test field wrongly named, field wrong type, etc.

Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:2488]: done

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:2483]: done

**Review by wrwg — APPROVED** [review]
