### PR TITLE
[move-prover][Claude] Fix $Arbitrary'T' to distinguish instances

### LINKED ISSUE #17911: [prover] `$Arbitrary'T'` needs to distinguishes its instances
The current way how `$Arbitrary'T'` is implemented creates an unknown but fixed value of the given type. However, this is unsound, since different uses of this constant in the same verification should be allowed to have different values. 

What we need here is to identify the syntactic instances, as done with the  translation of `choose`, where the source location is used to distinguish instances.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR fixes #17911 by generating $Arbitrary'T' function with node id information to distinguish instances. The main logic is implemented by Claude with minor manual modification on removing unnecessary template code.

## How Has This Been Tested?

Existing tests.

## Key Areas to Review

For comparing generic types and enum in fallback case, uninterpreted function `$Arbitrary_cmp_ordering'{}'(v1: {}, v2: {}): $1_cmp_Ordering` is generated, need to check whether this is sound or not.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [x] Move Prover

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

---

> [!NOTE]
> **Medium Risk**
> Touches Move Prover Boogie generation semantics for `abort`/cast fallback values and `cmp::compare` fallbacks, which can change verification outcomes and soundness. Risk is moderate because changes are localized to prover translation but affect many proofs.
> 
> **Overview**
> Makes Move Prover’s Boogie backend generate **unique uninterpreted `$Arbitrary_value_of` functions per expression node id** (instead of a single per-type function), so separate `abort`/fallback sites no longer accidentally share the same arbitrary value.
> 
> Updates bitvector downcast translation to model overflow explicitly: on overflow it returns a node-id-specific arbitrary value, otherwise it performs the proper truncation/extension.
> 
> Adjusts `cmp::compare` fallbacks for generics/enums to use a new uninterpreted `$Arbitrary_cmp_ordering'...' (v1, v2)` function, and removes/changes template-level `cmp` stubs in `prelude.bpl`/`aptos-natives.bpl` which previously relied on a global `$Arbitrary_value_of'$1_cmp_Ordering'()`.
> 
> Adds functional tests (`arbitrary.move`, `bv_cast.move`) which now correctly fail when assuming repeated arbitrary results are equal, demonstrating the new behavior.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 868e165d56105d8f94f63206665d2631b224082a. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: third_party/move/move-prover/boogie-backend/src/spec_translator.rs [hunk 1]
```diff
@@ -2077,9 +2138,50 @@ impl SpecTranslator<'_> {
                 Some(self.env.get_node_loc(arg.node_id())),
                 &source_type,
             );
-            emit!(self.writer, "$castBv{}to{}(", source_base, target_base);
-            self.translate_exp(&arg);
-            emit!(self.writer, ")");
+
+            // Get bit widths to determine cast direction
+            let target_bits: u32 = target_base.parse().unwrap();
```
Comment (junxzm1990) [inline third_party/move/move-prover/boogie-backend/src/spec_translator.rs]: u16 is enough?

File: third_party/move/move-prover/boogie-backend/src/spec_translator.rs [hunk 2]
```diff
@@ -2077,9 +2138,50 @@ impl SpecTranslator<'_> {
...
+                use num::{bigint::BigUint, One};
+                let max_val = if target_bits < 128 {
+                    ((1u128 << target_bits) - 1).to_string()
+                } else {
+                    // For u128 and u256, use BigUint to avoid overflow
+                    let max = (BigUint::one() << target_bits) - BigUint::one();
+                    max.to_string()
+                };
+
+                emit!(self.writer, "(if ($Gt'Bv{}'(", source_base);
```
Comment (junxzm1990) [inline third_party/move/move-prover/boogie-backend/src/spec_translator.rs:2341]: Maybe add a comment demoing the generated code for better readability?

File: third_party/move/move-prover/boogie-backend/src/spec_translator.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-prover/boogie-backend/src/spec_translator.rs]: done

**Comment by rahxephon89** [comment]
> I am not sure if the existing test cases cover the changed parts. So maybe add a few more test cases to verify?

two test cases are added

**Review by wrwg — APPROVED** [review]
