### PR TITLE
[move-model] fix internal assertion violation in definition analysis

### LINKED ISSUE #9064: [Bug] Internal assert failed in move-model
# 🐛 Bug

see https://github.com/move-language/move/issues/768

### PR DESCRIPTION
**Pull request by aalok-t**
### Description

Fix failing internal assert in move-model #9064. The assert is triggered because of duplicate declarations of a function name during definition analysis. This is fixed by raising an error explaining the duplicate declaration instead of an assertion violation. Close #9064 

### Test Plan
`move-prover/tests/sources/functional/duplicate_function_declarations.move`

### CODE REVIEW

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 1]
```diff
@@ -1319,16 +1321,34 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
+        name_loc: &Loc,
+        name_value: move_symbol_pool::Symbol,
+    ) {
+        if let Some(entry) = self.parent.spec_fun_table.get_mut(&full_name) {
+            if entry.is_empty() {
+                self.parent.error(
+                    name_loc,
+                    &format!("missing declaration of `{}`", name_value),
+                );
+            } else if entry.len() > 1 {
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/module_builder.rs:1337]: You could try to remove some code duplication by doing something like:
```                
                let error_msg = if entry.is_empty() {
                    "missing"
                } else {
                    "duplicate"
                };
                self.parent.error(
                    name_loc,
                    &format!("{} declaration of `{}` ", error_msg, name_value),
                );
```

**Review by rahxephon89 — CHANGES_REQUESTED** [review]

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 1 above)
Comment (aalok-t) [reply third_party/move/move-model/src/builder/module_builder.rs]: Done, thanks!

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 2]
```diff
@@ -1319,16 +1321,34 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
...
-                .map(|Parameter(n, ty)| Parameter(*n, ty.skip_reference().clone()))
-                .collect_vec();
-            e[0].result_type = e[0].result_type.skip_reference().clone();
-        });
+    fn deref_move_fun_types(
+        &mut self,
+        full_name: QualifiedSymbol,
+        spec_fun_idx: usize,
+        name_loc: &Loc,
+        name_value: move_symbol_pool::Symbol,
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/module_builder.rs:1329]: Maybe just use full_name in the error message? Then you don't need name_value.

**Review by junkil-park — COMMENTED** [review]
@aalok-t , could we add the reported test case to `move-prover/tests/sources/`? So, we can see that the case is fixed by your commit?

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 2 above)
Comment (aalok-t) [reply third_party/move/move-model/src/builder/module_builder.rs:1329]: `full_name` (QualifiedSymbol) does not have a value. An alternative is to pass the function to `deref_move_fun_types` but that creates some issues with borrowing.

Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:1329]: How about using `full_name.symbol` to retrieve name?

Comment (aalok-t) [reply third_party/move/move-model/src/builder/module_builder.rs:1329]: full_name.symbol would output the symbol, for example "Symbol(65)" instead of the name of the function. There is no way to extract the function name from the QualifiedSymbol AFAIK.

Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs:1329]: I see, could you try this: `self.symbol_pool().string(full_name.symbol).as_str()` or something similar?

File: third_party/move/move-prover/tests/sources/functional/duplicate_function_declarations.move [hunk 3]
```diff
@@ -0,0 +1,15 @@
+module 0x42::DuplicateFunction {
+    struct R0 { x: u8 }
+
+    spec R0 {
+        fun double(x: u8): u8 {
```
Comment (junkil-park) [inline third_party/move/move-prover/tests/sources/functional/duplicate_function_declarations.move:5]: Do you think this duplicated function is necessary to reproduce the problem? Otherwise, can we remove it to avoid the error above?

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 2 above)
Comment (aalok-t) [reply third_party/move/move-model/src/builder/module_builder.rs]: I just passed `name: FunctionName` instead and that simplifies the code.

File: third_party/move/move-prover/tests/sources/functional/duplicate_function_declarations.move (hunk 3 above)
Comment (aalok-t) [reply third_party/move/move-prover/tests/sources/functional/duplicate_function_declarations.move:5]: The duplicated function is neccessary to trigger the error.

**Review by rahxephon89 — APPROVED** [review]
Thanks!

**Review by junkil-park — APPROVED** [review]
LGTM. Thank you for fixing the bug, @aalok-t !
