### PR TITLE
[compiler] fix EXTRANEOUS_ACQUIRES_ANNOTATION

### LINKED ISSUE #14396: [Bug][move-compiler-v2] `EXTRANEOUS_ACQUIRES_ANNOTATION` becasue of unreachable function call
# 🐛 Bug

```
module 0xCAFE::Module0 {
    const ADDR: address = @0xBEEF;
    struct S has copy, drop, store, key { }

    public fun function1() acquires S {
        return;
        function2();
    }
    public fun function2() acquires S {
        borrow_global<S>(ADDR);
    }
}
```

Both V1 and V2 will fail bytecode verifier with `EXTRANEOUS_ACQUIRES_ANNOTATION`.

### LINKED ISSUE #17801: [Bug][compiler-v2][optimization] EXTRANEOUS_ACQUIRES_ANNOTATION is raised when turning on cfg simplification and full ast simplification at the same time
# 🐛 Bug

When trying to compile the following code:

```
module 0x8675309::M1 {
    

    struct R<phantom T> has key, store, copy, drop {
       x: u64
    }

    public fun extract<T>(r: &mut R<T>, y: u64): R<T> {
        let x = r.x - y;
        R {x}
    }

}

module 0x8675309::M {
    use 0x8675309::M1::R;
    use 0x8675309::M1::extract;

    struct R1<phantom T> has key {
       x: R<T>
    }


    fun f<T>(a: address): R<T> acquires R1 {
        let r = borrow_global_mut<R1<T>>(a);
        extract<T>(&mut r.x, 3)
    }

    public fun t0<T>(a: address): R<T> acquires R1 {
        assert!(false, 0);
        f(a)
    }

}

```

with full ast simplification and cfg simplification, the compiler reports the following error:

bug: bytecode verification failed with unexpected status code `EXTRANEOUS_ACQUIRES_ANNOTATION`.

After these two steps,  the call to `f` will be removed:

```
public t0<T>(a: address): R<T> /* def_idx: 1 */ {
B0:
	0: LdU64(0)
	1: Abort
}
```

However, `called_functions` is not updated in function data. Later, when generating acquired resource list in compiled module, indirect acquires is generated by incorrect called functions, leading to the issue.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

When optimization removes code, result of `get_called_functions` may contain function calls that have already been removed, which leads to incorrect computation of resources that are acquired indirectly. This PR fixes the issue by analyzing the stackless bytecode directly.

close #17801
close #14396

## How Has This Been Tested?

Existing tests and new test cases.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs [hunk 1]
```diff
@@ -1090,20 +1090,24 @@ impl ModuleContext<'_> {
...
-                    // Extend usage by that of callees from the same module. Acquires is only
-                    // local to a module.
-                    for callee in callees {
-                        if callee.module_id == module.get_id() {
-                            usage.extend(usage_map[&callee.id].iter().cloned());
+                let mut usage = usage_map[&fun.get_id()].clone();
+                let count = usage.len();
+                let target = self.targets.get_target(&fun, &FunctionVariant::Baseline);
+                // Check called functions directly from stacklessbytecode
+                for bc in target.get_bytecode() {
```
Comment (junxzm1990) [inline third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs]: The approach is smart. Maybe we can move the bytecode enumeration outside of the fixed-point loop? Either way, all functions need to be processed at least once.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs]: done
