### PR TITLE
[compiler-v2] Add access specifier check to reference safety

### LINKED ISSUE #13146: [Bug][Compiler-v2] GLOBAL_REFERENCE_ERROR error due to invalid acquiring of resource
# 🐛 Bug

When compiling the following code:
```
module 0x8675309::A {
    use std::signer;
    struct T1 has key {v: u64}

    public fun test(account: &signer) acquires T1 {
        let x = borrow_global_mut<T1>(signer::address_of(account));
        acquires_t1(account);
        move x;
    }

    fun acquires_t1(account: &signer) acquires T1 {
        T1 { v: _ } = move_from<T1>(signer::address_of(account));
    }
}
```

V2 will generate bytecode verification error: 

```
bug: BYTECODE VERIFICATION FAILED
  ┌─ tests/acquires-checker/v1-borrow-tests/borrow_global_acquires_invalid_1.move:7:9
  │
7 │         acquires_t1(account);
  │         ^^^^^^^^^^^^^^^^^^^^ ICE failed bytecode verifier: VMError {
    major_status: GLOBAL_REFERENCE_ERROR,
    sub_status: None,
    message: None,
    exec_state: None,
    location: Module(
        ModuleId {
            address: 0000000000000000000000000000000000000000000000000000000008675309,
            name: Identifier(
                "A",
            ),
        },
    ),
    indices: [
        (
            FunctionDefinition,
            1,
        ),
    ],
    offsets: [
        (
            FunctionDefinitionIndex(1),
            7,
        ),
    ],
}
```

While V1 generates the following compilation error:

```
error[E07003]: invalid operation, could create dangling a reference
  ┌─ tests/move_check/translated_ir_tests/move/borrow_tests/borrow_global_acquires_invalid_1.move:7:9
  │
6 │         let x = borrow_global_mut<T1>(signer::address_of(account));
  │                 -------------------------------------------------- It is still being mutably borrowed by this reference
7 │         acquires_t1(account);
  │         ^^^^^^^^^^^^^^^^^^^^ Invalid acquiring of resource 'T1'
```

### PR DESCRIPTION
**Pull request by wrwg**
## Description

Closes #13146

Adds a check that a global resource is not borrowed when it is declared in the access specifier list of a function.

This implements the full semantics of Move 2.0 access specifiers. However, if the 2.0 language is not enabled, access specifiers other then `acquires` will be rejected by the context checker, and for that special case the behavior is equivalent.

In order to test the extended access specifier semantics, we need to disable the existing acquires checker, which is not yet implemented for general access specifiers.

## Type of Change
- [x] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Existing failing test now works plus new tests

### CODE REVIEW

**Review by rahxephon89 — APPROVED** [review]
LGTM, thanks!

File: third_party/move/move-compiler-v2/tests/testsuite.rs [hunk 1]
```diff
@@ -269,7 +270,8 @@ const TEST_CONFIGS: Lazy<BTreeMap<&str, TestConfig>> = Lazy::new(|| {
             // Some reference tests create different errors since variable names are
             // known without optimizations, so we need to have a different exp file
             exp_suffix: Some("no-opt.exp"),
-            options: opts.clone().set_experiment(Experiment::OPTIMIZE, false),
+            options: opts.clone().set_experiment(Experiment::OPTIMIZE, false)
+                .set_experiment(Experiment::ACQUIRES_CHECK, false),
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/testsuite.rs:274]: Should we add the same todo as above here (i.e., `// TODO(#13485): Need to turn off acquires check for now to test 2.0 access specifiers`), so that we do not miss turning this back on later?

**Review by vineethk — APPROVED** [review]
LGTM (left a minor comment).

File: third_party/move/move-compiler-v2/tests/testsuite.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/testsuite.rs:274]: I think its fine, it is just 15 lines below the other comment, and both test configs are rather symmetric and belong together.
