### PR TITLE
[Compiler-v2] Generate a compiler error for global memory operation with incorrect type parameter

### LINKED ISSUE #11377: [Bug] [move-model] Model builder panics unexpectedly
# 🐛 Bug

The model builder crashes unexpectedly.
## To reproduce

Uncomment `move_from_no_key` in `third_party/move/move-compiler-v2/tests/ability-checker/ability_violation.move`, we will get
```
panicked at 'expected Type::Struct, found: TypeParameter(0)', third_party/move/move-model/src/ty.rs:536:13
```

## Expected Behavior

No panic.

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

For the global memory operation: `exists`, `move_from`, `move_to`, `borrow_global` and `borrow_global_mut`, the compiler requires that the type parameter must be converted into a concrete struct type during generation of stackless bytecode. Otherwise, it will panic with the message `panicked at 'expected Type::Struct, found: ...`, as mentioned in #11377. 

This PR changes this behavior by generating a compiler error instead of panicking.

Close #11377.

### Test Plan

1) Added a new test `global_invalid.move` to validate the result. The same test case is also added to the V1 compiler.
2) Updated the test case `ability_violation.move`.

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 1]
```diff
@@ -564,6 +564,22 @@ impl<'env> Generator<'env> {
...
+            | Operation::MoveFrom
+            | Operation::MoveTo
+                if self.env().get_node_instantiation(id)[0]
+                    .get_struct(self.env())
+                    .is_none() =>
+            {
+                self.error(
+                    id,
+                    format!(
+                        "expected `Type::Struct`, found: `{:?}`",
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:578]: Compiler V1 gives a much more verbose error message here, such as:
```
Error: error[E04009]: expected specific type
  ┌─ TEMPFILE:4:17
  │
4 │         assert!(exists<T>(addr), 0);
  │                 ^^^^^^^^^^^^^^^
  │                 │      │
  │                 │      Expected a struct type. Global storage operations are restricted to struct types declared in the current module. Found the type parameter: 'T'
  │                 Invalid call to exists.
```
Can we add some explanation here, too?  Note you can use 
```
            self.env.diag_with_labels(Severity::Error, &loc, &msg, error_details);
```
where `loc = self.env.get_node_loc(id)` and `error_details: Vec<(Loc, String)>` to add some further info.  Or maybe `diag_with_notes` if we just want to add some supporting info without particular location for it.

**Review by brmataptos — COMMENTED** [review]
Please also add the new tests under V1 to make it easier to compare outputs.

File: third_party/move/move-compiler-v2/tests/v1.unmatched [hunk 2]
```diff
@@ -265,6 +261,7 @@ move-compiler/tests/move_check/typing/{
   declare_pop_resource.move,
   entry_signature_no_warning.move,
   extraneous_acquire.move,
+  global_invalid.move,
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/tests/v1.unmatched:264]: It is here because global_invalid in V2 is placed in the `bytecode_generator` folder

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: done

**Comment by rahxephon89** [comment]
> Please also add the new tests under V1 to make it easier to compare outputs.

Added the same test under V1

**Review by vineethk — APPROVED** [review]
LGTM.

Also, thank you for the excellent PR description: makes it so much nicer to review.

**Review by brmataptos — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: Compiler v1 error messages are way to verbose (this is not only my idea but user feedback). We do not add explanations anywhere at this point. If we have the have them, I would like to have them separated from actual error and be optionally activated. We need to go back here at some point and remove the 'tutorial', it is inconsistent with the current messages.
