### PR TITLE
[Compiler-v2] Fix issue 11099

### LINKED ISSUE #11099: [Bug][Compiler-v2] unexpected type error when using inline function with generic types
# 🐛 Bug

When compiling the code:

```
module 0x42::M {
    use std::vector;

    struct S<Key> has copy, drop, store {
        data: vector<E<Key>>,
    }

    struct E<Key> has copy, drop, store {
        key: Key,
    }

    public fun foo<Key: store + drop>(
        map: S<Key>): vector<Key> {
        let keys: vector<Key> = vector::empty();
        let S { data } = map;
        vector::for_each(data, |e| {
            let E { key } = e;
            vector::push_back(&mut keys, key);
        });
        keys
    }

}
```
The following error message will be generated:

```
Diagnostics:
bug: unexpected type: ?10
   ┌─ tests/file-format-generator/unexpected_type.move:12:5
   │
12 │ ╭     public fun foo<Key: store + drop>(
13 │ │         map: S<Key>): vector<Key> {
14 │ │         let keys: vector<Key> = vector::empty();
15 │ │         let S { data } = map;
   · │
20 │ │         keys
21 │ │     }
   │ ╰─────^
```

I am not fully sure but it seems to be related to the inline function. cc @brianrmurphy @wrwg

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

This PR: 
    - Extend ExpWriter to support rewriting patterns
    - Close #11099 by rewriting the block pattern with type instantiation.

### CODE REVIEW

**Review by brmataptos — COMMENTED** [review]
Perhaps I should fix https://github.com/aptos-labs/aptos-core/issues/11093 myself first?

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 1]
```diff
@@ -1281,6 +1281,7 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
                 let mut result = et.translate_seq(&loc, seq, &result_type);
                 et.finalize_types();
                 result = et.post_process_placeholders(result.into_exp()).into();
+                result = et.rewrite_block_pattern(result.into_exp()).into();
```
Comment (wrwg) [inline third_party/move/move-model/src/builder/module_builder.rs:1284]: Can we (a) rename `post_process_placeholders` into `post_process_body` (b) fold the logic of `rewrite_block_pattern` into `post_process_body`. This way we avoid to rewrite the AST twice. Also easier to avoid to forget calling this function.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 2]
```diff
@@ -1515,6 +1515,32 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
         }
     }
 
+    /// Instantiate types for all all struct patterns in the block expression
+    /// This step is necessary because struct pattern may contain uninstantiated variable types
+    pub fn rewrite_block_pattern(&mut self, result_exp: Exp) -> Exp {
+        ExpData::rewrite(result_exp, &mut |e| {
+            let exp_data: ExpData = e.into();
+            if let ExpData::Block(id, pat, opt_exp, exp) = exp_data {
+                if let Struct(sid, std, patterns) = pat {
```
Comment (wrwg) [inline third_party/move/move-model/src/builder/exp_builder.rs:1524]: Please no unqualified user of symbols from other modules. Unless there is a function local use, e.g. as in `fn foo(e: Exp) { use ExpData::*'; ... }`

[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs:1524]: Agree, lets extend `ExpRewriter` to also visit patterns. This should not be too difficult.

As regards the concrete problem of type specialization after inference, node_id do not need to be rewritten. They content of the node_id table is specialized in the `finalize` functions, whereas the ids in the expression stay the same. But we need to recursively visit all patterns and specialize embedded type instantiations.

File: third_party/move/move-model/src/builder/module_builder.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/module_builder.rs]: done

**Review by brmataptos — APPROVED** [review]

**Review by wrwg — APPROVED** [review]
Nice!

**Comment by brmataptos** [comment]
This pretty much fixes https://github.com/aptos-labs/aptos-core/issues/11093.
