### PR TITLE
[Compiler-v2] Insertion of freeze operation when converting from mut to immut ref

### LINKED ISSUE #12539: [Bug][Compiler-v2] The result of mutate_immutable.move is not correct for V2
# 🐛 Bug

For the test case `mutate_immutable.move`, V2 does not generate the error for the statement `*(s: &S) = S { f: 0 };` while V1 generates the error:

```
error[E04006]: invalid subtype
  ┌─ tests/move_check/typing/mutate_immutable.move:5:10
  │
5 │         *(s: &S) = S { f: 0 };
  │          ^^^^^^^
  │          │   │
  │          │   Given: '&0x8675309::M::S'
  │          Invalid mutation. Expected a mutable reference
  │          Expected: '&mut _'
```

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR 

1) partially resolves the issue #12394 by inserting freeze operation when expression type is mutable ref while the expected expected type is immutable ref on the rhs of an expression.
2) closes #12539 by adding a corner case check when handling `Mutate` expression and `gen_select` in the bytecode generator.

This PR does not handle the case where the function returns a tuple that contains mutable reference type but the expected type on the lhs is immutable:

```
    fun t2(u1: &mut u64, u2: &mut u64): (&mut u64, &mut u64) {
        (u1, u2)
    }

    fun test_4() {
         let x: &u64;
         let y: &u64;
         (x, y) = t2(&mut 3, &mut 4);
   }
```

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Added two test cases in the unit test and one unit test in the transactional test.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 1]
```diff
@@ -1362,15 +1365,33 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
                             "Expected a single type, but found a tuple type",
                         );
                     }
-                    exps.push(exp.into_exp());
+                    let mut target_exp = exp;
+                    if expected_tys_opt.is_some()
+                        && ty.is_mutable_reference()
+                        && !self.translate_lhs
+                    {
+                        let expected_ty = expected_tys_opt.unwrap().get(i).unwrap();
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/exp_builder.rs:1386]: unwraps -> expects

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 2]
```diff
@@ -1397,13 +1418,15 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
             EA::Exp_::Assign(lhs, rhs) => {
                 self.require_impl_language(&loc);
                 let (rhs_ty, rhs) = self.translate_exp_free(rhs);
+                self.translate_lhs = true;
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/exp_builder.rs:1421]: How about we move this setting and resetting of this flag into `translate_lvalue_list`? Then we won't forget to do it around each of its calls.

Also, do we need to set and reset it around `translate_lvalue_fields`?

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    }
+
+    fun t2(u1: &mut u64, u2: &mut u64): (&u64, &mut u64) {
+        (u1, u2)
+    }
+
+    fun t3(s: &mut S) {
+        *(s: &S) = S {  };
+    }
+
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move:51]: There may be a few cases that are not resolved and still have this issue. An example:

```
    public fun t4() {
        let x: &u64;
        let y: &u64;
        (x, y) = (&mut 0, &mut 0);
    }
```

If you add this as a transactional test, you will see it leads to a bytecode verification error.

Comment (vineethk) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move:51]: Note that we do not run the final codegen and thus bytecode verification for tests under `checking`. Since this is fixing an error that manifested as a bytecode verification error, it would be good to add some of these tests in transactional tests as well.

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+    fun t1(s: &mut S): &S {
+        s
+    }
+
+    fun t2(u1: &mut u64, u2: &mut u64): (&u64, &mut u64) {
+        (u1, u2)
+    }
+
+    fun t3(s: &mut S) {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move:48]: If you add this code to transactional tests, you will notice that `S` needs drop ability. If we add drop ability, then v2 successfully processes this code, but v1 throws a compiler error, expecting s `to` be a mut ref.

This is a behavioral change, and we may want to explicitly call out whether we want to behave differently than v1 here (and have tests etc to demonstrate that).

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move:48]: Yeah, this is actually a bug revealed by another test case `mutable_immutable.mov`. I will file an issue for it.

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move (hunk 3 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move:51]: Thanks for catching it, @vineethk! There is a missing case for checking assignments.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 5]
```diff
@@ -80,6 +80,8 @@ pub(crate) struct ExpTranslator<'env, 'translator, 'module_translator> {
     pub placeholder_map: BTreeMap<NodeId, ExpPlaceholder>,
     /// A cached unification context, containing information about structs in the context.
     pub unification_context: CachedUnificationContext,
+    /// A flag to indicate whether in the middle of translating lhs part of an expression
+    pub translate_lhs: bool,
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:84]: Actually I am wondering whether we need this flag because if there is an operation of freeze to be inserted at LHS, it may already indicate an error?

[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-model/src/builder/exp_builder.rs:84]: Maybe an example like this?
```
let x = vector[1, 2, 3];
let r = &mut x;
*r[*r[1]] = 4;
```
Not sure about Move vs Rust syntax.

[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:84]: For this example, since Move treats vector::borrow as function call and the insertion of freeze operation for function  arguments is not controlled by this flag. However, it actually reveals another bug. Thanks @brmataptos!

**Comment by rahxephon89** [comment]
@vineethk @brmataptos, I have updated the code and tried to handle the comments.

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move (hunk 4 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move]: A fix is added to this PR

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move (hunk 3 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move]: Added a transactional test.

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 2 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs]: Actually translate_lvalue_list does not need to be guarded. I updated the use of this flag in the code.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 6]
```diff
@@ -1362,15 +1365,33 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
                         );
                     }
-                    exps.push(exp.into_exp());
+                    let mut target_exp = exp;
+                    if expected_tys_opt.is_some()
+                        && ty.is_mutable_reference()
+                        && !self.translate_lhs
+                    {
+                        let expected_ty = expected_tys_opt.unwrap().get(i).unwrap();
+                        if expected_ty.is_immutable_reference() {
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs]: done

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 7]
```diff
@@ -2461,15 +2509,26 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
             let oper_opt = entry.operation.clone();
             let index_opt = entry.temp_index;
             let ty = entry.type_.clone();
-            let ty = self.check_type(loc, &ty, expected_type, context);
-            let id = self.new_node_id_with_type_loc(&ty, loc);
-            if let Some(oper) = oper_opt {
+            let converted_ty = self.check_type(loc, &ty, expected_type, context);
+            let id = self.new_node_id_with_type_loc(&converted_ty, loc);
+            let mut ret = if let Some(oper) = oper_opt {
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:2530]: updated the code to have a dedicated function that takes the mutable reference of the expression and inserts the freeze operation when necessary.

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs]: Updated the name and use of this flag.

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 8]
```diff
@@ -385,13 +385,22 @@ impl<'env> Generator<'env> {
                 // appear where references are processed.
                 let rhs_temp = self.gen_arg(rhs, false);
                 let lhs_temp = self.gen_auto_ref_arg(lhs, ReferenceKind::Mutable);
-                if !self.temp_type(lhs_temp).is_mutable_reference() {
+                let lhs_type = self.get_node_type(lhs.node_id());
+
+                // For the case: `fun f(p: &mut S) { *(p :&S) =... }, we need to check whether `lhs_type` is immutable ref
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:390]: This comment is just confusing.  What is `lhs_type` in the move code you show?  Is it `&S` or `S`?

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 9]
```diff
@@ -867,15 +876,58 @@ impl<'env> Generator<'env> {
...
-                targets,
-                BytecodeOperation::Function(fun.module_id, fun.id, type_args),
-                args,
-                None,
-            )
-        })
+        let ret_type: Type = self.env().get_function(fun).get_result_type();
+        // For the code such as `let x: &u64; let y: &u64; (x,y) = f() where f returns (&mut, &mut)`
+        // we need to generate a new temp with mut ref type and then freeze it
+        if ret_type.is_tuple() {
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:882]: Move your `if let Type::Tupe(ret_tys) = ret_type` here since it also accomplishes this test.

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 10]
```diff
@@ -867,15 +876,58 @@ impl<'env> Generator<'env> {
...
+            let mut new_targets = vec![];
+            let mut target_map = BTreeMap::new();
+            if let Type::Tuple(ret_tys) = ret_type {
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/bytecode_generator.rs:885]: Move this up to eliminate the missing else branch.  (As mentioned above)

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move (hunk 3 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move]: Interesting.  What's different between this case and https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler/transactional-tests/tests/constants/by_reference.move and the same test for v2?  `&mut BYTES` is allowed, somehow.

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 8 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: revised the comment

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 9 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: done

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs (hunk 10 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: done

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move (hunk 3 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move]: Do you mean `let b = &mut BYTES;`?  Here `b` is implicitly has the type `&mut` while `x` and `y` in the example above has the type `&`.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 11]
```diff
@@ -1408,11 +1426,35 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
+                let mut rhs = rhs.into_exp();
+                // Insert freeze for rhs of the assignment
+                if lhs_ty.is_tuple() && rhs_ty.is_tuple() {
+                    if let Pattern::Tuple(_, lhs_tys) = &lhs {
+                        if let Type::Tuple(rhs_tys) = &rhs_ty {
+                            let lhs_tys = lhs_tys
+                                .iter()
+                                .map(|pat| self.get_node_type(pat.node_id()))
+                                .collect_vec();
+                            if let ExpData::Call(_, Operation::Tuple, _) = rhs.as_ref() {
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:1442]: Do this test for `ExpData::Call` first if there's any chance of it not being true.  Rust compiler might be able to reorder the tests, but I wouldn't take that chance.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 12]
```diff
@@ -1445,18 +1490,28 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
+                let id = if expected_type.is_immutable_reference() && *mutable {
+                    self.new_node_id_with_type_loc(&ty, &loc)
+                } else {
+                    self.new_node_id_with_type_loc(&result_ty, &loc)
+                };
+                let mut target_exp =
+                    ExpData::Call(id, Operation::Borrow(ref_kind), vec![target_exp.into_exp()])
+                        .into();
+                // Insert freeze for &mut when the expected type is &
+                if self.insert_freeze {
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:1511]: It seems odd that we could have a situation where `expected_type` is immutable, we have a mutable `Borrow`, but we don't insert a freeze because `self.insert_freeze` is false.  Is such a situation possible?  If so, what happens?  If not, why do we have 2 different ways of testing?

**Review by brmataptos — COMMENTED** [review]
Why do we need to insert freeze both in `exp_builder` and in `bytecode_generator`?  Why do we need both (are there example test cases for each)?

**Comment by rahxephon89** [comment]
> Why do we need to insert freeze both in `exp_builder` and in `bytecode_generator`? Why do we need both (are there example test cases for each)?

This is a good question @brmataptos. Initially, I wanted to insert freeze operation only in `exp_builder` but for the case where the return value is a tuple:

```
fun t2(u1: &mut u64, u2: &mut u64): (&mut u64, &mut u64) {
    (u1, u2)
}

fun test_4() {
        let x: &u64;
        let y: &u64;
        (x, y) = t2(&mut 3, &mut 4);
        assert!(*x == 3, 2);
        assert!(*y == 4, 3);
}
```

We need to convert the type of the first return value from &mut to &. For this case, it is much easier to do when generating the bytecode. We have a test case for it in the transactional test.

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 12 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:1511]: For this code:
```
    fun test_6() {
        let x: u64 = 3;
        *(&mut x: &u64) = 5;
    }
```,  if we don't have this condition, we will generate expression:
```
Freeze(Borrow(Mutable)(x)) = 5;
```
However, regardless of inserting freeze or not, the compiler should always return an error. That's why I asked a question above, maybe we don't need to this flag at the beginning. What do you think? @brmataptos

File: third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move (hunk 3 above)
Comment (brmataptos) [reply third_party/move/move-compiler-v2/tests/checking/typing/freeze_mut_ref.move]: > Note that we do not run the final codegen and thus bytecode verification for tests under `checking`. Since this is fixing an error that manifested as a bytecode verification error, it would be good to add some of these tests in transactional tests as well.

Maybe we should run through all passes for all checking tests.  It will take more time, but eng time is more expensive.

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 12 above)
Comment (brmataptos) [reply third_party/move/move-model/src/builder/exp_builder.rs:1511]: As discussed off-line, a similar test case is currently working in `tests/bytecode-generator/mutate_immutable.{move.exp}` in the current PR, but is not working in `tests/checking/typing/mutate_immutable.{move,exp}`.  Despite the identical names, the latter is the same as V1, while the other one is not.  The passes being run differ between those two tests, and it seems likely to be the reason the error is not caught for the `/checking/` test case.

File: third_party/move/move-compiler-v2/tests/bytecode-generator/mutate_immutable.move
Comment (brmataptos) [inline third_party/move/move-compiler-v2/tests/bytecode-generator/mutate_immutable.move:1]: Don't give this the same name as the test in `checking/typing`, since it is different and may lead to confusion.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/tests/bytecode-generator/mutate_immutable.move:1]: done

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 11 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs]: done

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 13]
```diff
@@ -867,6 +877,47 @@ impl<'env> Generator<'env> {
             .map(|(e, t)| self.maybe_convert(e, &t))
             .collect::<Vec<_>>();
         let args = self.gen_arg_list(&args, true);
+        let ret_type: Type = self.env().get_function(fun).get_result_type();
+        // For the code such as `let x: &u64; let y: &u64; (x,y) = f() where f returns (&mut, &mut)`
+        // we need to generate a new temp with mut ref type and then freeze it
+        if let Type::Tuple(ret_tys) = ret_type {
+            if ret_tys.len() == targets.len() {
+                let mut new_targets = vec![];
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs:893]: done

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 12 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:1505]: Added a new test function in `mutate_immutable_bytecode.move`

**Comment by brmataptos** [comment]
> We need to convert the type of the first return value from &mut to &. For this case, it is much easier to do when generating the bytecode. We have a test case for it in the transactional test.

It would be so useful to have it done earlier.  Perhaps we could expand
```
        let x: &u64;
        let y: &u64;
        (x, y) = t2(&mut 3, &mut 4);

```
into 
```
        let x: &u64;
        let y: &u64;
        let (x1: &mut u64, y1: &mut u64) = t2(&mut 3, &mut 4);
        x = freeze(x1);
        y = freeze(y1);
```
(If any LHS var (e.g., `x`) has less mutability than corresponding RHS, we create a new`&mut` version of the var (`x1`) to use in the let/assign, and add a freeze operation immediately after.

**Comment by rahxephon89** [comment]
> > We need to convert the type of the first return value from &mut to &. For this case, it is much easier to do when generating the bytecode. We have a test case for it in the transactional test.
> 
> It would be so useful to have it done earlier (in exp_builder). Perhaps we could expand
> 
> ```
>         let x: &u64;
>         let y: &u64;
>         (x, y) = t2(&mut 3, &mut 4);
> ```
> 
> into
> 
> ```
>         let x: &u64;
>         let y: &u64;
>         let (x1: &mut u64, y1: &mut u64) = t2(&mut 3, &mut 4);
>         x = freeze(x1);
>         y = freeze(y1);
> ```
> 
> (If any LHS var (e.g., `x`) has less mutability than corresponding RHS, we create a new`&mut` version of the var (`x1`) to use in the let/assign, and add a freeze operation immediately after.

Yeah, I was initially thinking the same idea but could not quickly figure out how to do it. Is there any existing code that does similar thing, e.g, creating a new scope and create temps/locals in it and does this thing?

**Comment by brmataptos** [comment]
> > > We need to convert the type of the first return value from &mut to &. For this case, it is much easier to do when generating the bytecode. We have a test case for it in the transactional test.
> > 
> > 
> > It would be so useful to have it done earlier (in exp_builder). Perhaps we could expand
> > ```
> >         let x: &u64;
> >         let y: &u64;
> >         (x, y) = t2(&mut 3, &mut 4);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > into
> > ```
> >         let x: &u64;
> >         let y: &u64;
> >         let (x1: &mut u64, y1: &mut u64) = t2(&mut 3, &mut 4);
> >         x = freeze(x1);
> >         y = freeze(y1);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (If any LHS var (e.g., `x`) has less mutability than corresponding RHS, we create a new`&mut` version of the var (`x1`) to use in the let/assign, and add a freeze operation immediately after.
> 
> Yeah, I was initially thinking the same idea but could not quickly figure out how to do it. Is there any existing code that does similar thing, e.g, creating a new scope and create temps/locals in it and does this thing?

Maybe inliner.rs but it may be kind of tricky.

**Comment by brmataptos** [comment]
Actually, `ast_simplifier.rs` is probably a better example, though we just need a tiny subset of it.

Wolfgang says we may want to do it after type inference, so you can use an implementation of trait `ExpRewriterFunctions` (defined in move-model/src/exp_rewriter.rs`) to help.

Your implementation of `ExpRewriterFunctions` should implement the cases `rewrite_assign,` `rewrite_block,` `rewrite_enter_scope`, and `rewrite_exit_scope`.  We use the `scope` methods to push and pop current symbol info on a `ScopedMap<Symbol, NodeId>` which we can use to get types as needed.  For `assign` and `block`, we can use `Pattern::vars_and_exprs()` (see move-model/src/ast.rs) to find vars and exprs as needed:
```
    for (var, opt_new_binding_exp) in pat.vars_and_exprs(exp) {
        get the types of var and opt_new_binding_exp
        if types have a mutability mismatch, create a new mut_var to replace var in the pattern and store it in a map.
    }
    use Pattern::replace_vars() to replace all needed var with mut_var
    if we are in rewrite_assign, then return a new Sequence(original Assign; new Assign (all var) = (all mut_var)).
    if we are in rewrite_block, then wrap the block body in a new block (let (all var) = (all mut_var); original body).
```
If you don't want to do it as part of this PR I can probably throw something together more easily.

**Comment by wrwg** [comment]
As discussed with Teng today, this should really be in the exp_builder. The reason is that not in every situation it might be clear what the expected and actual type is, thus triggering the conversion. (Situations are: argument, assign, let with type annotation, return, if-else). A conversion is essentially part of the type checking and inference, and maybe it is cleaner to eventually support this via type unification (i.e. type unification computes the set of conversions under which a type check is successful). Therefore lets keep this in the exp_builder.

Regards the complexity of adding generation of new temporaries to the exp builder for tuples, I would prefer we postpone this for now. That is I suggest we do _not_ fix the problem for tuple assigns. This is probably a rare occasion (we do know real code which hits this), so we can live for this for now until the conversion problem is consolidated.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 14]
```diff
@@ -2864,12 +2963,36 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
+        let exp_id = exp.node_id();
+        if expected_ty.is_immutable_reference() && ty.is_mutable_reference() {
+            // Insert Freeze operation
+            let new_id =
+                self.new_node_id_with_type_loc(expected_ty, &self.env().get_node_loc(exp_id));
+            *exp = ExpData::Call(new_id, Operation::Freeze, vec![exp.clone()]).into_exp();
+        }
+    }
+
+    /// Inserts the freeze operation when `exp` is a tuple expression
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:2981]: Similar here, try to use a more functional style.
```
fn freeze_tuple_exp(&self, lhs_tys: &Vec<Type>, rhs_tys: &Vec<Type>, exp: Exp, loc: &Loc) -> Exp {
    if lhs_tys.len() != rhs_tys.len() || lhs_tys == rhs_tys {
        return exp
    }
    let exp_id = exp.node_id();
    if let ExpData::Call(_, Operation::Tuple, rhs_vec) = exp.into() {
        let new_rhs = lhs_tys.iter().zip(rhs_tys.iter()).zip(rhs_vec)
            .map(|((lh_ty, rh_ty), rh)| { 
                self.try_freeze(lh_ty, rh_ty, rh)
            };
        let new_id_tuple = ...;
        ExpData::Call(new_id_tuple, Operation_Tuple, new_rhs).into_exp();
    } else {
        exp
    }
}
```

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (brmataptos) [reply third_party/move/move-model/src/builder/exp_builder.rs:2549]: Even better if you can make `try_freeze(..., exp: Exp) -> Exp` (have it just return the argument if no freeze is needed).  It's clearer, and does less work.

**Review by brmataptos — APPROVED** [review]
This looks like it probably so I'm approving, but I think your code could be more clear, and you could avoid a bit of work by using a more functional style rather than `mut` variables and mutation (as long as it doesn't require cloning data structures).  If we didn't have the impending deadline, I'd push for more changes.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 15]
```diff
@@ -2864,12 +2963,36 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
+    fn freeze_tuple_exp(&self, lhs_tys: &Vec<Type>, rhs_tys: &Vec<Type>, exp: &mut Exp, loc: &Loc) {
+        let mut new_exp = exp.clone().into();
+        if lhs_tys.len() != rhs_tys.len() {
+            return;
+        }
+        let mut new_rhs = vec![];
+        if let ExpData::Call(_, Operation::Tuple, rhs_vec) = &mut new_exp {
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:3020]: Can we just check equality by ` lhs_tys == rhs_tys` or `lhs_tys.eq(rhs_tys)`?

[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:3020]: nvm, just noticed your example below

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 14 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:3028]: It turns out that the if-else requires an explicit clone:
```
 if let ExpData::Call(_, Operation::Tuple, rhs_vec) = exp.clone().into() {
...
```
Not sure in this case should we still use this style?

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 16]
```diff
@@ -385,13 +385,23 @@ impl<'env> Generator<'env> {
                 // appear where references are processed.
                 let rhs_temp = self.gen_arg(rhs, false);
                 let lhs_temp = self.gen_auto_ref_arg(lhs, ReferenceKind::Mutable);
-                if !self.temp_type(lhs_temp).is_mutable_reference() {
+                let lhs_type = self.get_node_type(lhs.node_id());
+
+                // For the case: `fun f(p: &mut S) { *(p :&S) =... },
+                // we need to check whether p (with explicit type annotation) is an immutable ref
+                if lhs_type.is_immutable_reference()
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: done

File: third_party/move/move-compiler-v2/src/bytecode_generator.rs [hunk 17]
```diff
@@ -1091,19 +1109,25 @@ impl<'env> Generator<'env> {
...
         let oper_temp = self.gen_auto_ref_arg(oper, ReferenceKind::Immutable);
+        let oper_type = self.get_node_type(oper.node_id());
 
         // If we are in reference mode and a &mut is requested, the operand also needs to be
         // &mut.
         if self.reference_mode()
             && self.reference_mode_kind == ReferenceKind::Mutable
-            && !self.temp_type(oper_temp).is_mutable_reference()
+            && (oper_type.is_immutable_reference() // To check the corner case `&mut x...; (x:&T). = ...`, we need this condition
+                || !self.temp_type(oper_temp).is_mutable_reference())
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/bytecode_generator.rs]: done

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:3035]: done

**Review by wrwg — APPROVED** [review]

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 14 above)
Comment (brmataptos) [reply third_party/move/move-model/src/builder/exp_builder.rs:3028]: You can use probably use `exp.as_ref()` and then `rhs_vec` will be a ref and you can clone `rh` as needed.  In any case, `Exp` is interned, so cloning is fairly shallow anyway.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 18]
```diff
@@ -2864,12 +2963,36 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
-                // Insert Freeze operation
-                let new_id =
-                    self.new_node_id_with_type_loc(&param_ty, &self.env().get_node_loc(exp_id));
-                *exp = ExpData::Call(new_id, Operation::Freeze, vec![exp.clone()]).into_exp();
+            self.try_freeze(&param_ty, &exp_ty, exp);
+        }
+    }
+
+    /// Inserts the freeze operation when `expected_ty` is immutable ref and ty is mutable ref
+    fn try_freeze(&self, expected_ty: &Type, ty: &Type, exp: &mut Exp) {
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs]: done

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 14 above)
Comment (rahxephon89) [reply third_party/move/move-model/src/builder/exp_builder.rs:3043]: done

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 19]
```diff
@@ -1467,12 +1462,16 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
                                 .iter()
                                 .map(|pat| self.get_node_type(pat.node_id()))
                                 .collect_vec();
-                            self.freeze_tuple_exp(&lhs_tys, rhs_tys, &mut rhs, &loc);
+                            self.freeze_tuple_exp(&lhs_tys, rhs_tys, rhs, &loc)
+                        } else {
+                            self.try_freeze(&lhs_ty, &rhs_ty, rhs)
                         }
+                    } else {
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:1469]: Don't waste time here, but in the future, you can get rid of some of these redundant `else` clauses by combining matches in a tuple, e.g.:
```
if let (Pattern::Tuple(_, lhs_tys), Type::Tuple(rhs_tys)) = (&lhs, &rhs_ty) {
    ...
}
```
With dependencies it doesn't work as well (e.g., the innermost `lhs_tys`.) and sometimes it can move things too far apart, so don't go overboard.

Btw, it would be really good if you do other than just repeat the same variable name.  Why is one `lhs_tys` a `&Vec<Pattern>` and another one a `Vec<Type>`?  The first one probably should be called `lhs_pats` instead.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 20]
```diff
@@ -2959,19 +2962,23 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
-                self.add_conversions(cand, &instantiation, &mut translated_args);
+                let translated_args = self.add_conversions(cand, &instantiation, translated_args);
                 let specialized_expected_type = self.subs.specialize(expected_type);
-                let mut call_exp = ExpData::Call(id, oper, translated_args).into_exp();
+                let call_exp = ExpData::Call(id, oper, translated_args).into_exp();
                 // Insert freeze for the return value
-                if result_type.is_tuple() && specialized_expected_type.is_tuple() {
-                    if let Tuple(result_tys) = result_type {
+                let call_exp = if result_type.is_tuple() && specialized_expected_type.is_tuple() {
+                    if let Tuple(ref result_tys) = result_type {
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:2970]: It seems more common to use `if let Tuple(result_tys) = &result_type {` which I think has the same result.

Comment (brmataptos) [reply third_party/move/move-model/src/builder/exp_builder.rs:2970]: And again, you could eliminate some redundant `else` branches with a tuple:
```
if let (Tuple(result_tys), Tuple(expected_tys)) = (&result_type, specialized_expected_type) {
    ...
}
```

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 21]
```diff
@@ -2959,19 +2962,23 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
                 }
-                self.add_conversions(cand, &instantiation, &mut translated_args);
+                let translated_args = self.add_conversions(cand, &instantiation, translated_args);
                 let specialized_expected_type = self.subs.specialize(expected_type);
-                let mut call_exp = ExpData::Call(id, oper, translated_args).into_exp();
+                let call_exp = ExpData::Call(id, oper, translated_args).into_exp();
                 // Insert freeze for the return value
-                if result_type.is_tuple() && specialized_expected_type.is_tuple() {
-                    if let Tuple(result_tys) = result_type {
+                let call_exp = if result_type.is_tuple() && specialized_expected_type.is_tuple() {
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:2969]: You don't need the `is_tuple()` tests here, since the match conditions below will do the same test.

Although that leaves the possibility of an empty type.  But you can add that test to `freeze_tuple_exp()` at the top, where you're already checking lengths.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 22]
```diff
@@ -3001,45 +3008,61 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
     /// the only supported conversion is from `&mut T` to `&T` and we treat with it in an ad-hoc
     /// manor.
-    fn add_conversions(&self, entry: &AnyFunEntry, instantiation: &[Type], args: &mut [Exp]) {
+    fn add_conversions(
+        &self,
+        entry: &AnyFunEntry,
+        instantiation: &[Type],
+        args: Vec<Exp>,
+    ) -> Vec<Exp> {
+        let mut new_args = vec![];
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:3017]: We can again use a functional style.  Let's see if it is any clearer:
```
{
    let params = entry.get_signature().1;
    let new_args = params.iter().map(|Parameter(_, ty, _)| ty.instantiate(instantiation))
        .zip(args)
        .map(|(param_ty, exp)| {
                    let exp_ty = self.env().get_node_type()(exp.node_id()),
                    self.try_freeze(&param_ty, &exp_ty, exp)
                  })
        .collect_vec();
    new_args
}
```
Seems nicer to me.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 23]
```diff
@@ -2887,21 +3008,61 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
...
+        &self,
+        lhs_tys: &Vec<Type>,
+        rhs_tys: &Vec<Type>,
+        exp: Exp,
+        loc: &Loc,
+    ) -> Exp {
+        if lhs_tys.len() != rhs_tys.len() || lhs_tys.eq(rhs_tys) {
+            return exp;
+        }
+        if let ExpData::Call(_, Operation::Tuple, rhs_vec) = exp.as_ref() {
```
Comment (brmataptos) [inline third_party/move/move-model/src/builder/exp_builder.rs:3054]: Note that we're making a new vector and `Call(...Tuple..)` expression below for *every* tuple assignment, even if it doesn't have reference types.  While `Exp` is interned, its constructors are not memoized, so we are generating a lot of duplicated structures (which keep using memory, unfortunately, due to `Exp` interning).

Maybe we need a function `need_freeze(lh_ty, rh_ty) -> bool` that we can use to first test whether we even need the new expression:
```
    let need_freeze = lhs_tys.iter().zip(rhs_tys.iter()).any(|(lh_ty, rh_ty)| self.need_freeze(lh_ty, rh_ty)));
    if let (true, ExpData::Call(_, Operation::Tuple, rhs_vec)) = (need_freeze, exp.as_ref()) {
        ...
    }
```

**Review by brmataptos — APPROVED** [review]
We still have more improvements we can make, but this is ok for now if you want to move on to fix other issues.
