### PR TITLE
[tool] Coverage crash fix

### LINKED ISSUE #15117: [Bug][compiler-v2] Coverage testing DevEx issues
@brmataptos @fEst1ck @georgemitenkov @rahxephon89 @runtian-zhou @vineethk @wrwg

# `--move-2` flag DevEx

I am trying to run `aptos move test --coverage` for [this commit of an ongoing Move v2 red-black tree implementation](https://github.com/econia-labs/econia-v5/blob/d14e1f5b40281387631cb417a4a935c5a22c4832/src/move/research/red-black-map/variants/b/sources/red_black_map.move), but it is failing with the following trace:

```sh
aptos move test --coverage      
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING RedBlackMap
error[E01013]: unsupported language construct
  ┌─ /Users/alex/repos/econia-v5/src/move/research/red-black-map/variants/b/sources/red_black_map.move:6:5
  │
6 │     enum Color has copy, drop {
  │     ^^^^ Move 2 language construct is not enabled: enum types

error[E01013]: unsupported language construct
   ┌─ /Users/alex/repos/econia-v5/src/move/research/red-black-map/variants/b/sources/red_black_map.move:60:38
   │
60 │             if (parent_ref_mut.color is Color::Black)
   │                                      ^^ Move 2 language construct is not enabled: `is` expression

error[E01013]: unsupported language construct
   ┌─ /Users/alex/repos/econia-v5/src/move/research/red-black-map/variants/b/sources/red_black_map.move:81:70
   │
81 │             if (uncle_index == NIL || (self.nodes[uncle_index].color is Color::Black)) {
   │                                                                      ^^ Move 2 language construct is not enabled: `is` expression
```

EDIT: Per https://github.com/aptos-labs/aptos-core/issues/15117#issuecomment-2447584475, tests pass for `aptos move test --coverage --move-2 --dev`, but is there a way to eliminate the need to pass `--move-2` all over the place? (now captured at #15124)

# Coverage against source is broken

1. `aptos move coverage source --module red_black_map --dev --move-2` is broken (but displaying against bytecode works)

### PR DESCRIPTION
**Pull request by vineethk**
## Description

Fixes #15117, #15698, #15032.

Starting point for this PR was https://github.com/aptos-labs/aptos-core/pull/15250, but there are several modifications.

Main changes:
- When we compute source coverage for a module `m`, we look at how various modules within the  package containing `m` contribute to the coverage of `m` (due to inline functions, e.g.,).
- Names from source map are used in the disassembly listing (which causes the large change set in the expected files in tests).

## How Has This Been Tested?
- Manually tested each of the scenarios in #15117, #15698, #15032, and verified that we do not crash.
- Manually tested some handcrafted Move projects for sanity checks.
- Existing tests: baselines have been updated and checked that they only change variable names in disassembly listings.

## Type of Change
- [x] Bug fix

## Which Components or Systems Does This Change Impact?
- [x] Other: Move Coverage Tool

### CODE REVIEW

**Comment by vineethk** [comment]
* **#15857** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15857?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15857?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/tools/move-coverage/src/source_coverage.rs [hunk 1]
```diff
@@ -38,22 +38,84 @@ pub struct FunctionSourceCoverage {
     pub uncovered_locations: Vec<Loc>,
 }
 
+/// Source-level positive coverage information for a function.
+#[derive(Clone, Debug, Serialize)]
+pub struct FunctionSourceCoverageV2 {
```
Comment (rahxephon89) [inline third_party/move/tools/move-coverage/src/source_coverage.rs:43]: Could you add a comment explaining when to use FunctionSourceCoverageV2 and when to use the original version. Is V2 potentially a replacement for V1 or an extension to be used in certain places?

File: third_party/move/tools/move-coverage/src/bin/coverage-summaries.rs [hunk 2]
```diff
@@ -24,57 +25,92 @@ use std::{
     version
 )]
 struct Args {
-    /// The path to the coverage map or trace file
-    #[clap(long = "input-trace-path", short = 't')]
+    /// The path to the coverage map file
+    #[clap(long = "input-trace-path")]
```
Comment (rahxephon89) [inline third_party/move/tools/move-coverage/src/bin/coverage-summaries.rs:29]: Just nit: are we going to remove all abbreviation for all options in the CLI?

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/tools/move-coverage/src/bin/coverage-summaries.rs (hunk 2 above)
Comment (vineethk) [reply third_party/move/tools/move-coverage/src/bin/coverage-summaries.rs:29]: I removed them for all the files touched here, as it is recommended practice for CLI (see https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos/CONTRIBUTING.md?plain=1#L155).

File: third_party/move/tools/move-coverage/src/source_coverage.rs (hunk 1 above)
Comment (vineethk) [reply third_party/move/tools/move-coverage/src/source_coverage.rs:43]: Fair point. I'll add corresponding comments.

The plan is to deprecate and remove the old one, but I think the old one is used by some external tools (like mutation testing), so wanted to keep it around until it is safe to remove.

**Review by wrwg — APPROVED** [review]
