### PR TITLE
Fix issue #16155

### LINKED ISSUE #16155: [Bug] Compiler does not catch recursive type definitions via function types
# 🐛 Bug

Consider the following transactional test:
```
//# publish
module 0xc0ffee::m {
    struct Foo(|Bar|) has copy, drop;
    struct Bar(|Foo|) has copy, drop;
}
```

This results in a bytecode verification error, instead of a nicer compiler error:
```
Error: compilation errors:
 bug: bytecode verification failed with unexpected status code `RECURSIVE_STRUCT_DEFINITION`. This is a compiler bug, consider reporting it.
Error message: none
  ┌─ TEMPFILE:2:1
  │  
2 │ ╭ module 0xc0ffee::m {
3 │ │     struct Foo(|Bar|) has copy, drop;
4 │ │     struct Bar(|Foo|) has copy, drop;
5 │ │ }
  │ ╰─^
```

## Expected Behavior

Compiler error, instead of the above compiler bug message.

### PR DESCRIPTION
**Pull request by junxzm1990**
## Description

#16155 reports a recursive structure definition that involves function types and bypasses compiler checks. This is because the existing [recursive struct checker](https://github.com/aptos-labs/aptos-core/blob/jun/bug_16155/third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs#L60) does not check function types nested inside structure definitions.

The fix adds support for function types, as well as other missing types (tuple and reference).

Close #16155

## How Has This Been Tested?
- New [compiler test cases](https://github.com/aptos-labs/aptos-core/blob/jun/bug_16155/third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move) added
- Existing compile tests and transactional_tests

## Key Areas to Review
- Potential side effects of new supports of other types in [recursive struct checker](https://github.com/aptos-labs/aptos-core/blob/jun/bug_16155/third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs#L60) 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs [hunk 1]
```diff
@@ -101,7 +101,27 @@ impl<'a> RecursiveStructChecker<'a> {
                         self.report_invalid_field(&struct_env, &field_env);
                     }
                 },
-                Type::Primitive(_) | Type::TypeParameter(_) | Type::Fun(..) => {},
+                Type::Tuple(ty_vec) => {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs:104]: Tuple types cannot appear in structs right now, so this changes from `unreachable` in the previous code to having this default implementation here.

We may want to still keep this as unreachable, or at least add a clear note saying this is not currently reachable.

File: third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs [hunk 2]
```diff
@@ -195,7 +214,21 @@ impl<'a> RecursiveStructChecker<'a> {
                     .iter()
                     .any(|ty| self.ty_contains_struct(path, ty, loc.clone(), struct_id, checked))
             },
-            Type::Primitive(_) | Type::TypeParameter(_) | Type::Fun(..) => false,
+            Type::Vector(ty) => self.ty_contains_struct(path, ty, loc, struct_id, checked),
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs:217]: Curious: why was this code moved down here?

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+    struct S2(|S3|) has copy, drop;
+    struct S3(|&S1|) has copy, drop;
+}
+
+module 0xc0fff12::m15 {
+    struct S1  { x: u64, y: u64, f : S2 } has copy, drop;
+    struct S2(|S3|) has copy, drop;
+    struct S3(|S4|) has copy, drop;
+    struct S4(|&S1|) has copy, drop;
+}
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move:91]: We could perhaps add a test with cycle formation through enums, references, and functions types.

**Review by vineethk — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs (hunk 1 above)
Comment (junxzm1990) [reply third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs:104]: I am not aware of that. Will change accordingly.

File: third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs (hunk 2 above)
Comment (junxzm1990) [reply third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs:217]: I believe it is unintentional.

File: third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move (hunk 3 above)
Comment (junxzm1990) [reply third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move:91]: Will add.

**Comment by junxzm1990** [comment]
@vineethk all comments addressed. Please re-review and approve.

@rahxephon89 and @JakeSilverman , this is a simple one. So when getting some cycles, could you take a look so that we can close the issue?

**Review by rahxephon89 — APPROVED** [review]

**Review by vineethk — APPROVED** [review]
