### PR TITLE
fix issue #17188

### LINKED ISSUE #17188: [Bug] Incorrect error location in Move tests when there is an arithmetic error
# 🐛 Bug

Consider the following move program:
```move
module 0xc0ffee::m {
    #[test]
    public fun demonstrate_conversions() {
        let x = 0;
        assert!(x == 0, 700);

        let big_number: u64 = 1000;
        let small_number: u8 = (big_number as u8);
        assert!(small_number == 255, 703);
    }
}
```

When we run `aptos move test`, we get the following error:
```
│ error[E11001]: test failure
│   ┌─ /Users/vineeth/Code/review/testing/checker/sources/main.move:5:9
│   │
│ 3 │     public fun demonstrate_conversions() {
│   │                ----------------------- In this function in 0xc0ffee::m
│ 4 │         let x = 0;
│ 5 │         assert!(x == 0, 700);
│   │         ^^^^^^ Test was not expected to error, but it gave an arithmetic error with error message: "Cannot cast u64(1000) to u8". Error originating in the module 0000000000000000000000000000000000000000000000000000000000c0ffee::m rooted here
```

Clearly, the location pinpointed for the error is incorrect.

### PR DESCRIPTION
**Pull request by junxzm1990**
## Description
The compiler's peephole optimizations on file-format bytecode has an issue on maintaining the code loc info. See #17188 for an example. 

Specifically, the optimizer ignored previously-maintained location mapping during recursive optimizations. This PR fixes the issue.

Close #17188 

## How Has This Been Tested?
- Existing `move-unit-test` with a new test case borrowed from #17188 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

### CODE REVIEW

**Comment by junxzm1990** [comment]
* **#17277** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17277?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/17277?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/optimizers.rs [hunk 1]
```diff
@@ -32,6 +32,13 @@ impl TransformedCodeChunk {
         Self::new(vec![], vec![])
     }
 
+    /// Extract a contiguous sub-chunk from this chunk,
+    pub fn truncate(block: &TransformedCodeChunk, start: u16, end: u16) -> TransformedCodeChunk {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/optimizers.rs]:
```suggestion
    pub fn extract(&self, start: CodeOffset, end: CodeOffset) -> TransformedCodeChunk {
```

File: third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs [hunk 2]
```diff
@@ -71,14 +71,14 @@ impl BasicBlockOptimizerPipeline {
...
-        code: &[Bytecode],
+        original_block: &TransformedCodeChunk,
         cfg: &VMControlFlowGraph,
     ) -> BTreeMap<CodeOffset, TransformedCodeChunk> {
         let mut optimized_blocks = BTreeMap::new();
         for block_id in cfg.blocks() {
             let start = cfg.block_start(block_id);
             let end = cfg.block_end(block_id); // `end` is inclusive
-            let mut block = TransformedCodeChunk::make_from(&code[start as usize..=end as usize]);
+            let mut block = TransformedCodeChunk::truncate(original_block, start, end);
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs]:
```suggestion
            let mut block = original_block.extract(start, end);
```

File: third_party/move/tools/move-unit-test/tests/test_sources/issue_17188.move [hunk 3]
```diff
@@ -0,0 +1,11 @@
+module 0xc0ffee::m {
+    #[test]
```
Comment (vineethk) [inline third_party/move/tools/move-unit-test/tests/test_sources/issue_17188.move:4]: Could we add a few more tests like this where we error and check the message for error location?

Comment (junxzm1990) [reply third_party/move/tools/move-unit-test/tests/test_sources/issue_17188.move:4]: Let me think about it.

Comment (junxzm1990) [reply third_party/move/tools/move-unit-test/tests/test_sources/issue_17188.move:4]: Added!

**Review by wrwg — APPROVED** [review]
