### PR TITLE
[compiler] Fix visibility check for public structs/enums

### LINKED ISSUE #19348: [Bug] Panic instead of error when accessing private struct from another module
# 🐛 Bug

```move
//# publish
module 0xA::A {
    struct W(|| has drop) has drop;
    public fun f() {}
    public inline fun make_w(): W {
        f
    }
}

//# publish
module 0xB::B {
    use 0xA::A;

    fun test(): 0xA::A::W {
        A::make_w()
    }
}
```

Running `RUST_BACKTRACE=1 aptos move compile --language-version 2.4 ` will panic with:
```
thread 'main' (574016) panicked at third_party/move/move-model/src/model.rs:3640:13:
FunId 0xa::A::pack$W undefined
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/panicking.rs:80:14
   2: move_model::model::ModuleEnv::into_function::{{closure}}
             at .../aptos-core-orig/third_party/move/move-model/src/model.rs:3640:13
   3: core::option::Option<T>::unwrap_or_else
             at .../.rustup/toolchains/1.93.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1067:21
   4: move_model::model::ModuleEnv::into_function
             at .../aptos-core-orig/third_party/move/move-model/src/model.rs:3639:53
   5: move_model::model::ModuleEnv::get_used_function_from_compiled_module
             at .../aptos-core-orig/third_party/move/move-model/src/model.rs:3692:20
   6: move_model::model::ModuleEnv::get_used_function
             at .../aptos-core-orig/third_party/move/move-model/src/model.rs:3677:14
   7: move_stackless_bytecode::stackless_bytecode_generator::StacklessBytecodeGenerator::generate_bytecode
             at .../aptos-core-orig/third_party/move/move-model/bytecode/src/stackless_bytecode_generator.rs:881:22
   8: move_stackless_bytecode::stackless_bytecode_generator::StacklessBytecodeGenerator::generate_function
             at .../aptos-core-orig/third_party/move/move-model/bytecode/src/stackless_bytecode_generator.rs:131:18
   9: aptos_framework::extended_checks::ExtendedChecker::get_stackless_data
             at .../aptos-core-orig/aptos-move/framework/src/extended_checks.rs:967:46
  10: aptos_framework::extended_checks::ExtendedChecker::check_and_record_events
             at .../aptos-core-orig/aptos-move/framework/src/extended_checks.rs:835:29
  11: aptos_framework::extended_checks::ExtendedChecker::run
...
```

If run as a transactional test, will fail with:

```
task 1 'publish'. lines 10-17:
Error: Unable to publish module '000000000000000000000000000000000000000000000000000000000000000b::B'. Got VMError: {
    major_status: LOOKUP_FAILED,
    sub_status: None,
    location: 0xb::B,
    indices: [(FunctionHandle, 2)],
    offsets: [],
}
```

### Another case

```move
//# publish
module 0xAA::theirs {
    struct Inner has drop, copy {
        val: u64,
    }

    public fun make_inner(v: u64): Inner {
        Inner { val: v }
    }
}

//# publish
module 0xBB::mine {
    use 0xAA::theirs::Inner;

    enum Wrapper has drop {
        Wrapped { field: Inner },
    }

    public fun make_wrapper(v: u64): Wrapper {
        Wrapper::Wrapped { field: 0xAA::theirs::make_inner(v) }
    }

    public fun steal_via_match(x: Wrapper): u64 {
        match (x) {
            Wrapper::Wrapped { field: Inner { val } } => val,
        }
    }
}
```

This has the same symptom but doesn't use inline.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

Fixes #19348: cross-module access of a private struct causes a Rust panic in `aptos move compile` instead of a proper compilation error.

### Root cause

Two bugs allowed private struct operations to slip through to file format generation, which then generated references to struct API wrappers (e.g. `pack$W`, `unpack$W`) that don't exist for private structs, causing either a Rust panic (via `ATTACH_COMPILED_MODULE`) or a VM `LOOKUP_FAILED` error at publish time.

**Bug 1 — `function_checker.rs`: match arm patterns not traversed**

`collect_struct_op_from_exp` for `ExpData::Match` only checked the discriminator type for cross-module struct unpacks. Nested `Pattern::Struct` nodes inside match arm patterns (e.g. `Inner { val }` inside `Wrapper::Wrapped { field: Inner { val } }`) were never visited, so the visibility checker silently missed them.

**Bug 2 — `function_generator.rs`: no visibility check before emitting struct API calls**

At all 7 cross-module struct operation sites (Pack, PackVariant, Unpack, UnpackVariant, TestVariant, BorrowField, BorrowVariantField), the file format generator checked the language version but never checked struct visibility before calling the API generation functions.

Importantly, `function_checker.rs` operates on the high-level model AST and detects explicit struct operations (e.g. `Operation::Pack`). However, it cannot handle the case where a function value is **implicitly wrapped into or unwrapped from a struct wrapper** (e.g. `struct W(|| has drop)`) via type coercion — in that case, no explicit `Pack`/`Unpack` node appears in the AST, so the checker never sees it. The pack/unpack is only materialized at the stackless bytecode level. The fix in `function_generator.rs` therefore serves as a necessary extra layer of defense: it catches private struct API calls regardless of whether the checker upstream detected the violation, preventing references to non-existent API wrappers from being emitted.

### Fix

- **`function_checker.rs`**: For `ExpData::Match`, also traverse the field-level sub-patterns of each arm's top-level pattern to catch nested struct unpacks. The top-level arm pattern is already reported via the discriminator check; only the sub-patterns are additionally traversed.

- **`function_generator.rs`**: Add `check_cross_module_struct_visibility` helper on `FunctionContext`, called at all 7 cross-module struct operation sites after the language version check. It emits a user error for private structs or package/friend structs accessed without the appropriate relationship, preventing the bad API call from being generated.

## How Has This Been Tested?

New transactional tests in `no-v1-comparison/structs_visibility/`:
- `inline_private_struct_pack` — explicit pack via inline function (caught by checker)
- `inline_private_struct_pack_1` — implicit pack via function value coercion (caught by file format gen fix)
- `private_struct_unpack` — unpack of private struct in match arm pattern (caught by checker fix)
- `private_struct_unpack_nested` — two-level nested struct unpack in match arm (verifies recursive traversal)
- `inline_friend_struct_pack` — friend struct: declared friend succeeds, non-friend fails
- `inline_package_struct_pack` — package struct accessed from outside package fails

## Key Areas to Review

- `function_checker.rs` `collect_struct_op_from_exp`: the `ExpData::Match` arm — specifically the choice to traverse only sub-patterns of the top-level arm pattern (not the top-level itself, which is already covered by the discriminator check) to avoid duplicate diagnostics.
- `function_generator.rs` `check_cross_module_struct_visibility`: the friend/package visibility logic and its placement at all 7 struct API call sites.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [x] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

---

> [!NOTE]
> **Medium Risk**
> Touches Move compiler visibility enforcement in both the post-inlining checker and file-format generation; incorrect logic could reject valid programs or still allow invalid cross-module struct operations, but changes are localized and covered by new transactional tests.
> 
> **Overview**
> Fixes missed/unsafe cross-module struct/enum access checks so invalid private/friend/package struct operations produce **user-facing compile errors** instead of panics/VM lookup failures.
> 
> The function checker now walks match-arm sub-patterns to detect *nested* `unpack` operations inside patterns, and the file-format generator centralizes and applies `check_cross_module_struct_access` before emitting cross-module `pack`/`unpack`/variant-test/field-borrow API calls, enforcing visibility (private vs friend/package) in addition to language-version gating.
> 
> Adds transactional tests covering cross-module pack via inlining (private/friend/package) and private struct unpacks in match patterns, including nested unpacks.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 20e01e1ca6f167703ed0f246c28bdde769ef4d90. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by rahxephon89** [comment]
* **#19351** <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/19351?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/19351?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 1]
```diff
@@ -2212,6 +2248,44 @@ impl<'a> FunctionGenerator<'a> {
...
+        struct_env: &StructEnv,
+        fun_mid: ModuleId,
+        op: &str,
+    ) -> bool {
+        let visibility = struct_env.get_visibility();
+        let struct_name = struct_env.get_full_name_str();
+        let module_name = struct_env.module_env.get_full_name_str();
+        if visibility == Visibility::Private {
+            self.module.error(
+                &self.loc,
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs]: fixed

File: third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs [hunk 2]
```diff
@@ -512,11 +512,32 @@ fn collect_struct_op_from_exp(func: &FunctionEnv, exp: &ExpData, ops: &mut Vec<S
...
+            }
+            // Arm patterns may contain nested struct unpacks not covered by the discriminator.
+            // The top-level pattern of each arm always matches the discriminator type (already
+            // reported above), so only traverse its sub-patterns (field-level patterns) to catch
+            // inner struct unpacks like `Inner { val }` inside `Wrapper::Wrapped { field: Inner { val } }`.
+            for arm in arms {
+                let sub_pats: Vec<&Pattern> = match &arm.pattern {
+                    Pattern::Struct(_, _, _, fields) => fields.iter().collect(),
+                    Pattern::Tuple(_, pats) => pats.iter().collect(),
+                    _ => vec![],
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs]: use full pattern instead of wildcard

File: third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs [hunk 3]
```diff
@@ -512,11 +512,39 @@ fn collect_struct_op_from_exp(func: &FunctionEnv, exp: &ExpData, ops: &mut Vec<S
...
-            if let Type::Struct(mid, sid, _) = env.get_node_type(id).drop_reference() {
-                push(mid.qualified(sid), StructOpKind::Unpack, id);
+        // Match expression unpacks the discriminator; arm patterns may unpack nested structs
+        ExpData::Match(_, discriminator, arms) => {
+            let disc_node = discriminator.node_id();
+            // The discriminator itself is unpacked when it is a struct/enum type
+            if let Type::Struct(mid, sid, _) = env.get_node_type(disc_node).drop_reference() {
+                push(mid.qualified(sid), StructOpKind::Unpack, disc_node);
+            }
+            // Arm patterns may contain nested struct unpacks not covered by the discriminator.
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs]: this big comment describing each of the arms should be broken down/simplified. eg.,
- "handle nested struct unpacks in sub-patterns" for the first two arms, above them
- "no sub-patterns" for the rest arms.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 4]
```diff
@@ -887,6 +888,12 @@ impl<'a> FunctionGenerator<'a> {
                         ));
                         return;
                     }
+                    let op_loc = fun_ctx.fun.get_bytecode_loc(ctx.attr_id);
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs]: can we please combine the two checks: language version and the visibility check into a helper, so all call sites can call the helper instead of duplicating the two-check logic everywhere?

File: third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs (hunk 3 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs]: done

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 4 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs]: done

**Review by wrwg — APPROVED** [review]
