### PR TITLE
[Compiler-v2] Bug fixes in serializer, compiled unit and enable compiler v2 in framework and package system unit test 

### LINKED ISSUE #10936: [Bug][Compiler-v2] AnnotatedCompiledUnit has unknown loc
# 🐛 Bug

When an AnnotatedCompiledUnit is created, an unknown loc is assigned with a default file hash. However it needs to be updated to the hash of the corresponding file because in the [`build_all`](https://github.com/aptos-labs/aptos-core/blob/8bfd27c95109ae9502ff061759049f5bfe4b56d0/third_party/move/tools/move-package/src/compilation/compiled_package.rs#L679) function, the hash is used to retrieve `source_path` from `file_map` otherwise, the compiler will panic.

### LINKED ISSUE #10958: [Bug][Compiler-v2] Serializer panicked when the target function contains acquires clause and bytecode version is 6 or below
# 🐛 Bug

When compiling `move-stdlib` with bytecode version 6 or below, the function `serialize_function_handle` will return an error because functions in the `features` modules use `acquires Features`, which further leads to panic in the function `serialize_function_handles`.

### LINKED ISSUE #10992: [Bug][Compiler-v2] stackless_control_flow_graph panics when collecting blocks
# 🐛 Bug

When compiling the package in the test `third_party/move/tools/move-package/tests/test_sources/compilation/case_insensitive_check` using V2, the compiler panics with the following stack trace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', third_party/move/move-model/bytecode/src/stackless_control_flow_graph.rs:168:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: move_stackless_bytecode::stackless_control_flow_graph::StacklessControlFlowGraph::collect_blocks
   4: move_stackless_bytecode::stackless_control_flow_graph::StacklessControlFlowGraph::new_backward
             at /Users/tengzhang/aptos-core/third_party/move/move-model/bytecode/src/stackless_control_flow_graph.rs:56:22
   5: move_stackless_bytecode::livevar_analysis::LiveVarAnalysisProcessor::analyze
             at /Users/tengzhang/aptos-core/third_party/move/move-model/bytecode/src/livevar_analysis.rs:140:19
   6: <move_compiler_v2::pipeline::livevar_analysis_processor::LiveVarAnalysisProcessor as move_stackless_bytecode::function_target_pipeline::FunctionTargetProcessor>::process
             at /Users/tengzhang/aptos-core/third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs:31:13
   7: move_stackless_bytecode::function_target_pipeline::FunctionTargetProcessor::process_and_maybe_remove
             at /Users/tengzhang/aptos-core/third_party/move/move-model/bytecode/src/function_target_pipeline.rs:108:14
   8: move_stackless_bytecode::function_target_pipeline::FunctionTargetsHolder::process
             at /Users/tengzhang/aptos-core/third_party/move/move-model/bytecode/src/function_target_pipeline.rs:293:17
   9: move_stackless_bytecode::function_target_pipeline::FunctionTargetPipeline::run_with_hook
             at /Users/tengzhang/aptos-core/third_party/move/move-model/bytecode/src/function_target_pipeline.rs:514:29
  10: move_stackless_bytecode::function_target_pipeline::FunctionTargetPipeline::run
             at /Users/tengzhang/aptos-core/third_party/move/move-model/bytecode/src/function_target_pipeline.rs:549:9
  11: move_compiler_v2::run_move_compiler
             at /Users/tengzhang/aptos-core/third_party/move/move-compiler-v2/src/lib.rs:68:9
  12: move_package::compilation::compiled_package::build_and_report_no_exit_v2_driver
             at /Users/tengzhang/aptos-core/third_party/move/tools/move-package/src/compilation/compiled_package.rs:1077:24
  13: core::ops::function::FnMut::call_mut
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:166:5
  14: move_package::compilation::compiled_package::CompiledPackage::build_all
             at /Users/tengzhang/aptos-core/third_party/move/tools/move-package/src/compilation/compiled_package.rs:673:17
  15: move_package::compilation::build_plan::BuildPlan::compile_with_driver
             at /Users/tengzhang/aptos-core/third_party/move/tools/move-package/src/compilation/build_plan.rs:197:33
  16: move_package::compilation::build_plan::BuildPlan::compile_no_exit
             at /Users/tengzhang/aptos-core/third_party/move/tools/move-package/src/compilation/build_plan.rs:131:9
  17: move_package::BuildConfig::compile_package_no_exit
             at /Users/tengzhang/aptos-core/third_party/move/tools/move-package/src/lib.rs:214:54
  18: aptos_framework::built_package::BuiltPackage::build
             at /Users/tengzhang/aptos-core/aptos-move/framework/src/built_package.rs:183:13
  19: <aptos::move_tool::CompilePackage as aptos::common::types::CliCommand<alloc::vec::Vec<alloc::string::String>>>::execute::{{closure}}
             at /Users/tengzhang/aptos-core/crates/aptos/src/move_tool/mod.rs:319:20
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/future/future.rs:125:9
  21: aptos::common::types::CliCommand::execute_serialized_with_logging_level::{{closure}}
             at /Users/tengzhang/aptos-core/crates/aptos/src/common/types.rs:1210:28
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/future/future.rs:125:9
  23: aptos::common::types::CliCommand::execute_serialized::{{closure}}
             at /Users/tengzhang/aptos-core/crates/aptos/src/common/types.rs:1198:14
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/future/future.rs:125:9
  25: aptos::move_tool::MoveTool::execute::{{closure}}
             at /Users/tengzhang/aptos-core/crates/aptos/src/move_tool/mod.rs:104:66
  26: aptos::Tool::execute::{{closure}}
             at /Users/tengzhang/aptos-core/crates/aptos/src/lib.rs:67:42
  27: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:63
  28: tokio::runtime::coop::with_budget
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  29: tokio::runtime::coop::budget
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  30: tokio::runtime::park::CachedParkThread::block_on
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:31
  31: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/blocking.rs:66:9
  32: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  33: tokio::runtime::context::runtime::enter_runtime
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  34: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  35: tokio::runtime::runtime::Runtime::block_on
             at /Users/tengzhang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:313:50
  36: aptos::main
             at /Users/tengzhang/aptos-core/crates/aptos/src/main.rs:27:18
  37: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5

```

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

This PR:
- Close #10936
- Close #10958
- Close #10992 
- Add a new env variable "ENABLE_V2". If it is set to "1", unit tests in framework, move-example and third_party/move_package will run v2 as well.
- Change the compiler config when running unit tests in move_package so that known_attributes will be printed out. Baseline in the exp files are updated accordingly.

TODO: 
- This PR does not compare output between V1 and V2 in the move_package test. Once the compiler V2 is more stable, the comparison will be added.

### Testing

For both the fix of #10936 and #10958, testing is done using `aptos move compile --compiler-version=v2` against `move-stdlib`. framework unit-test will cover them once the flag `ENABLE_V2` is set to 1 by default. The fix of #10992 is verified by running the test case `third_party/move/tools/movepackage/tests/test_sources/compilation/case_insensitive_check` with `ENABLE_V2` set to 1.

### CODE REVIEW

File: third_party/move/move-binary-format/src/serializer.rs [hunk 1]
```diff
@@ -496,7 +496,14 @@ fn serialize_function_handle(
     serialize_ability_sets(binary, &function_handle.type_parameters)?;
     if major_version >= VERSION_7 {
         serialize_access_specifiers(binary, &function_handle.access_specifiers)
-    } else if function_handle.access_specifiers.is_some() {
+    } else if function_handle.access_specifiers.is_some()
```
Comment (rahxephon89) [inline third_party/move/move-binary-format/src/serializer.rs:499]: If bytecode version is 6 or below, check whether the access_specifier is the traditional one

File: third_party/move/tools/move-package/src/compilation/compiled_package.rs [hunk 2]
```diff
@@ -559,7 +559,11 @@ impl CompiledPackage {
                 },
             )
             .collect::<Vec<_>>();
-        for (dep_package_name, _, _, _) in &transitive_dependencies {
+        let mut source_package_map: BTreeMap<String, Symbol> = BTreeMap::new();
```
Comment (rahxephon89) [inline third_party/move/tools/move-package/src/compilation/compiled_package.rs:562]: The map is from path to package name, which is used when traversing all_compiled_units to obtain the package name.

File: third_party/move/move-binary-format/src/file_format.rs [hunk 3]
```diff
@@ -886,6 +886,15 @@ pub struct AccessSpecifier {
     pub address: AddressSpecifier,
 }
 
+impl AccessSpecifier {
+    pub fn is_traditional_acquires(&self) -> bool {
```
Comment (rahxephon89) [inline third_party/move/move-binary-format/src/file_format.rs:890]: Check whether an access specifier is the traditional one. This check is used when serializing the function handle.

File: aptos-move/framework/tests/move_unit_test.rs [hunk 4]
```diff
@@ -37,6 +40,23 @@ fn run_tests_for_pkg(path_to_pkg: impl Into<String>) {
     if ok != UnitTestResult::Success {
         panic!("move unit tests failed")
     }
+    if read_env_var(ENABLE_V2) == "1" {
```
Comment (rahxephon89) [inline aptos-move/framework/tests/move_unit_test.rs:43]: run test against v2 when ENABLE_V2 is set

File: third_party/move/move-compiler-v2/src/lib.rs [hunk 5]
```diff
@@ -169,11 +172,15 @@ pub fn check_errors<W: WriteColor>(
...
 pub fn annotate_units(env: &GlobalEnv, units: Vec<CompiledUnit>) -> Vec<AnnotatedCompiledUnit> {
-    let loc = env.unknown_move_ir_loc();
+    let mut loc = env.unknown_move_ir_loc();
     units
         .into_iter()
         .map(|u| match u {
             CompiledUnit::Module(named_module) => {
+                let mid = named_module.module.self_id();
+                if let (Some(hash), Some(span)) = get_module_file_hash(env, mid.name().as_str()) {
+                    loc = Loc::new(hash, span.start().0, span.end().0);
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/src/lib.rs:182]: Update loc if its name can be found from env

File: third_party/move/tools/move-package/tests/test_runner.rs [hunk 6]
```diff
@@ -28,21 +33,16 @@ use tempfile::tempdir;
...
-    package_hooks::register_package_hooks(Box::new(TestHooks()));
-    let update_baseline = read_env_update_baseline();
-    if path
-        .components()
-        .any(|component| component == Component::Normal(OsStr::new("deps_only")))
-    {
-        return Ok(());
+fn run_test_impl(path: &Path, v2_flag: bool) -> datatest_stable::Result<String> {
+    let mut compiler_config = CompilerConfig {
+        known_attributes: KnownAttribute::get_all_attribute_names().clone(),
```
Comment (rahxephon89) [inline third_party/move/tools/move-package/tests/test_runner.rs:38]: Add known_attributes to the compiler config, which leads to update of exp files in this PR

File: third_party/move/tools/move-package/tests/test_runner.rs [hunk 7]
```diff
@@ -130,6 +142,27 @@ pub fn run_test(path: &Path) -> datatest_stable::Result<()> {
...
+        return Ok(());
+    }
+
+    let output_v1 = run_test_impl(path, false)?;
+    let update_baseline = read_env_update_baseline();
+    let res_v1 = check_or_update(path, output_v1.clone(), update_baseline, false);
+    if read_env_var(ENABLE_V2) == "1" {
+        let output_v2 = run_test_impl(path, true)?;
+        if output_v1 != output_v2 {
+            // TODO: compare the result between V1 and V2.
```
Comment (rahxephon89) [inline third_party/move/tools/move-package/tests/test_runner.rs:160]: Comparison of V1 and V2 will be added later as explained in the description of this PR

File: third_party/move/move-compiler-v2/src/lib.rs [hunk 8]
```diff
@@ -168,23 +168,22 @@ pub fn check_errors<W: WriteColor>(
...
-    let loc = env.unknown_move_ir_loc();
+pub fn annotate_units(units: Vec<CompiledUnit>) -> Vec<AnnotatedCompiledUnit> {
     units
         .into_iter()
         .map(|u| match u {
             CompiledUnit::Module(named_module) => {
                 AnnotatedCompiledUnit::Module(AnnotatedCompiledModule {
-                    loc,
-                    module_name_loc: loc,
+                    loc: named_module.source_map.definition_location,
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/src/lib.rs:177]: loc is used in compiled_package to retrieve the package_name

File: third_party/move/move-model/src/builder/module_builder.rs [hunk 9]
```diff
@@ -3622,7 +3622,7 @@ impl<'env, 'translator> ModuleBuilder<'env, 'translator> {
         }
         let mut function_data: BTreeMap<FunId, FunctionData> = Default::default();
         for (name, entry) in &self.parent.fun_table {
-            if name.module_name != self.module_name {
```
Comment (rahxephon89) [inline third_party/move/move-model/src/builder/module_builder.rs:3625]: For scripts in two different files, since the module name are both "<SELF>", the check will fail. As a result, one script function will be added to multiple modules, leading to the error in #10992.

File: third_party/move/move-compiler-v2/src/lib.rs [hunk 10]
```diff
@@ -168,23 +168,22 @@ pub fn check_errors<W: WriteColor>(
...
+                    module_name_loc: named_module.source_map.definition_location,
```
Comment (wrwg) [inline third_party/move/move-compiler-v2/src/lib.rs:178]: Perhaps pull the loc into a let

File: third_party/move/tools/move-package/src/compilation/compiled_package.rs [hunk 11]
```diff
@@ -675,11 +682,23 @@ impl CompiledPackage {
         };
         let mut root_compiled_units = vec![];
         let mut deps_compiled_units = vec![];
+        let obtain_package_name = |default: Option<Symbol>, source_path_str: &str| -> Symbol {
+            if default.is_none() && source_package_map.contains_key(source_path_str) {
+                *source_package_map.get(source_path_str).unwrap()
```
Comment (wrwg) [inline third_party/move/tools/move-package/src/compilation/compiled_package.rs:687]: Hmm. Should we have a test for this path?

**Review by wrwg — APPROVED** [review]
Nice!

**Review by vineethk — APPROVED** [review]
Again, really nice work figuring all these out quickly and fixing them!

I only have minor comments, otherwise LGTM.

File: third_party/move/tools/move-package/src/compilation/compiled_package.rs (hunk 11 above)
Comment (rahxephon89) [reply third_party/move/tools/move-package/src/compilation/compiled_package.rs:687]: When running several tests in `move-package` such as `tests/test_sources/compilation/one_dep_renamed`, `tests/test_sources/compilation/one_dep_assigned_address` in V2, this path is covered. Since CI does not run V2 by default, it is not shown in CI yet.

File: third_party/move/tools/move-package/src/compilation/compiled_package.rs [hunk 12]
```diff
@@ -675,11 +682,23 @@ impl CompiledPackage {
...
+            } else {
+                default.unwrap()
+            }
+        };
         for annot_unit in all_compiled_units {
-            let source_path = PathBuf::from(file_map[&annot_unit.loc().file_hash()].0.as_str());
+            let source_path_str = file_map[&annot_unit.loc().file_hash()].0.as_str();
```
[the remark this answers is not in the document]
Comment (rahxephon89) [reply third_party/move/tools/move-package/src/compilation/compiled_package.rs]: done

File: third_party/move/move-compiler-v2/src/lib.rs (hunk 10 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/lib.rs]: done
