### PR TITLE
[compiler-v2] Do not pop non-droppables on stack flush

### LINKED ISSUE #14223: [Bug][move-compiler-v2] Differing behavior w.r.t ability checks in the presence of unreachable code
# 🐛 Bug

```move
module 0xCAFE::Module0 {
    struct S {}

    public fun f() {
        let x = S {};
        abort 1;
        let S {} = x;
    }
}
```

V1 compiles fine and running the compiled function will abort with `1`.

V2 will fail bytecode verifier with `POP_WITHOUT_DROP_ABILITY`:
```
bug: bytecode verification failed with unexpected status code `POP_WITHOUT_DROP_ABILITY`. This is a compiler bug, consider reporting it.
  ┌─ ~/debug_package/sources/repro.move:7:9
  │
7 │         abort 1;
  │         ^^^^^^^
```

### PR DESCRIPTION
**Pull request by wrwg**
## Description

Fixes #14223 

On stack flush we must not pop values which cannot be dropped. Rather they should be stored in temps. This faciltates scenarios where an `abort` happens before the end of a block. Without this, we pop the value before the abort, leading to a bytecode verification error.

There is still an issue with a missing warning, added #14320 for that.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Added tests

### CODE REVIEW

**Comment by wrwg** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14321?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14321** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14321?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#14316** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14316?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wrwg and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 1]
```diff
@@ -1025,8 +1025,10 @@ impl<'a> FunctionGenerator<'a> {
             if before && ctx.is_alive_before(temp)
                 || !before && ctx.is_alive_after(temp, &[], false)
                 || self.pinned.contains(&temp)
+                || !ctx.fun_ctx.is_droppable(temp)
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:1028]: Could we just pin all the non-droppable temps as an alternative, given that is common to anywhere in the function (i.e., not specific to a particular program point)? Would be a bit cleaner and abstract.

Comment (wrwg) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:1028]: That doesn't seem to be cleaner, since pinned values is something else. For example, they can't be moved. I think this is as clean as it can get, just can't pop non-droppabble from the stack.

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs [hunk 2]
```diff
@@ -1025,8 +1025,10 @@ impl<'a> FunctionGenerator<'a> {
...
             {
-                // Only need to save to a local if the temp is still used afterwards
+                // Only need to save to a local if the temp is still used afterwards,
+                // or if it is not droppable
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:1031]: For the sake of completeness: "or is pinned".

File: third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs (hunk 1 above)
Comment (vineethk) [reply third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:1028]: Ah gotcha - had not considered the non-movable bit about the pinned locals.

**Review by vineethk — APPROVED** [review]

**Review by rahxephon89 — APPROVED** [review]
@wrwg, please update the name of the test case from `bug_14233...` to `bug_14223...` to avoid potential confusion.
