### PR TITLE
[Prover] Bitwise operation in aborts_if condition

### LINKED ISSUE #14459: [Bug][prover] Bitvector not working in context of aborts_if with clause
Drop the following into the prover functional test dir:

```
module 0x42::test {
    use std::error;

    spec module {
        pragma verify = true;
    }

    fun assert_no_spec(x: u64) {
        assert!(x > 815);
    }

    fun assert_with_spec(x: u64) {
        assert!(x > 815);
    }
    spec assert_with_spec  {
        aborts_if x > 815 with std::error::internal(0) | (0xCA26CBD9BE << 24);
    }
}

```

Boogie error:

```
Move prover returns: [internal] boogie exited with compilation errors:
aborts_if_compiler_codes.bpl(3672,47): Error: invalid type for argument 0 in application of $Or'Bv64': int (expected: bv64)
aborts_if_compiler_codes.bpl(3672,70): Error: invalid type for argument 1 in application of $Or'Bv64': int (expected: bv64)
aborts_if_compiler_codes.bpl(3675,4): Error: mismatched types in assignment command (cannot assign bv64 to int)
3 type checking errors detected in aborts_if_compiler_codes.bpl
```

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR closes #14459 by adding support of expression with bv operation in the abort_if condition.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Added a new test.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rahxephon89** [comment]
* **#14552** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14552?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rahxephon89 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by wrwg — APPROVED** [review]

File: third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs [hunk 1]
```diff
@@ -461,15 +461,41 @@ impl<'a> NumberOperationAnalysis<'a> {
...
+                                                | ExpData::Value(..)
+                                                | ExpData::Call(_, ASTOperation::Cast, _)
                                         );
-                                        update_temporary(arg, &merged, global_state, state);
+                                        if let ExpData::Call(
+                                            _,
+                                            ASTOperation::SpecFunction(mid, sid, _),
+                                            _,
+                                        ) = arg.clone().into()
+                                        {
```
Comment (brmataptos) [inline third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs:476]: This is a pretty convoluted expression.  Perhaps a helper function with an informative name would be useful?  Or at least a comment to say what you are checking here.

File: third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs [hunk 2]
```diff
@@ -461,15 +461,41 @@ impl<'a> NumberOperationAnalysis<'a> {
...
-                                            allow_merge,
+                                        let mut update_flag = matches!(
+                                            arg.clone().into(),
+                                            ExpData::Temporary(..)
+                                                | ExpData::LocalVar(..)
+                                                | ExpData::Value(..)
+                                                | ExpData::Call(_, ASTOperation::Cast, _)
                                         );
-                                        update_temporary(arg, &merged, global_state, state);
+                                        if let ExpData::Call(
```
Comment (brmataptos) [inline third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs:471]: It would probably simplify the code if you used a match expression and combined this with the previous statement, e.g.:
```
    let update_flag = match arg.clone().into() {
        ExpData::Temporary(..) | ... => true,
        ExpData::Call(_, ASTOperation::SpecFunction(mid, sid, _), _) => {
            let module_env = ..
            ...
            !spec_f.is_move_fun && self.func_target...
        },
        _ => false,
     }
```

**Review by brmataptos — CHANGES_REQUESTED** [review]
Code is a bit obfuscated.

File: third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs]: done

File: third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs (hunk 2 above)
Comment (rahxephon89) [reply third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs]: done

File: .github/workflows/lint-test.yaml [hunk 3]
```diff
@@ -164,20 +164,7 @@ jobs:
           ref: ${{ github.event.pull_request.head.sha }}
           fetch-depth: 0 # Fetch all git history for accurate target determination
 
-      - name: Check if dev_setup.sh has changed
```
Comment (rahxephon89) [inline .github/workflows/lint-test.yaml:167]: Need to execute `dev_setup.sh` before running the unit test so that the newest version of Boogie can be installed.

**Review by brmataptos — APPROVED** [review]
