### PR TITLE
[compiler v2] Generate friend handles in CompiledModule

### LINKED ISSUE #11485: [Bug][Compiler-v2] LOOKUP_FAILED error
# 🐛 Bug

When testing `0x1::table_with_length::test_upsert`,  `0x1::any::test_any` and `0x1::copyable_any::test_any` using V2, the following bytecode verification error will be generated:

```
┌── test_upsert ──────
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::table_with_length rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: LOOKUP_FAILED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("table_with_length") }), indices: [(FunctionHandle, 7)], offsets: [] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::table_with_length,
│     indices: [(FunctionHandle, 7)],
│     offsets: [],
│     exec_state: None,
│ }
└──────────────────
```

```
┌── test_any ──────
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::any rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: LOOKUP_FAILED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("any") }), indices: [(FunctionHandle, 7)], offsets: [] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::any,
│     indices: [(FunctionHandle, 7)],
│     offsets: [],
│     exec_state: None,
│ }
└──────────────────
```

```
┌── test_any ──────
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::copyable_any rooted here{
│     message: Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!
│ Error: VMError { major_status: LOOKUP_FAILED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier("copyable_any") }), indices: [(FunctionHandle, 7)], offsets: [] },
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     location: 0x1::copyable_any,
│     indices: [(FunctionHandle, 7)],
│     offsets: [],
│     exec_state: None,
│ }
└──────────────────
```

The error is raised from [verify_imported_functions](https://github.com/aptos-labs/aptos-core/blob/f92718217fe1d3ec6185517415282df1563df87e/third_party/move/move-bytecode-verifier/src/dependencies.rs#L332) in `third_party/move/move-bytecode-verifier/src/dependencies.rs`

### PR DESCRIPTION
**Pull request by wrwg**
This was missing, leading to LOOKUP_FAILURE errors for friend modules.

Test plan: manually tested against unit tests in aptos-stdlib. Unfortunately the txn framework doesn't support module bundles. (Module friends need to published at once.)

Close #11485

### CODE REVIEW

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs [hunk 1]
```diff
@@ -151,6 +151,12 @@ impl ModuleGenerator {
             let acquires_list = &acquires_map[&fun_env.get_id()];
             FunctionGenerator::run(self, ctx, fun_env, acquires_list);
         }
+
+        // At handles of friend modules
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs:155]: At --> Add

**Review by brmataptos — APPROVED** [review]
See typo in comment.

**Review by vineethk — APPROVED** [review]
