### PR TITLE
[compiler-v2] Perform check of uninitialized locals in code spec blocks

### LINKED ISSUE #15928: [Bug][compiler-v2][prover] Compiler panic when translating an assertion with an uninitialized variable
# 🐛 Bug

When compiling the following function using V2:

```
    public fun test() {
        let z;
        assert {
            assert z == 3;
        }
        z = 2;
    }
```

Instead of generating a compiler error, the compiler panicked with the error:

```
thread '<unnamed>' panicked at third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs:899:47:
temp has mapping
```

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR adds checking of uninitialized locals in the spec block.

close #15928 

## How Has This Been Tested?

1) existing tests;
2) a new test case.

## Key Areas to Review

Whether the fix covers all cases for spec blocks.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/pipeline/uninitialized_use_checker.rs [hunk 1]
```diff
@@ -216,11 +212,24 @@ impl UninitializedUseChecker {
...
                             },
-                            target.get_local_name_for_error_message(*src)
+                            target.get_local_name_for_error_message(*temp)
                         ),
                     );
                 }
-            });
+            };
+            if let Bytecode::SpecBlock(_, spec) = bc {
+                for cond in &spec.conditions {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/pipeline/uninitialized_use_checker.rs:221]: Is `conditions` the only field of `spec` that needs to be checked? How about `update_map`?

**Review by vineethk — APPROVED** [review]

File: third_party/move/move-compiler-v2/src/pipeline/uninitialized_use_checker.rs (hunk 1 above)
Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/pipeline/uninitialized_use_checker.rs:221]: Yes, `update_map` is not yet filled in this phase AFAIK. The test case with `update z = y;` is used to show it.

Comment (vineethk) [reply third_party/move/move-compiler-v2/src/pipeline/uninitialized_use_checker.rs:221]: Maybe we can just say that in a comment here, so that it is explicit to the reader.

Comment (rahxephon89) [reply third_party/move/move-compiler-v2/src/pipeline/uninitialized_use_checker.rs:223]: done

**Review by wrwg — APPROVED** [review]
