### PR TITLE
[Compiler-v2] Fix #11210

### LINKED ISSUE #11210: [Bug][Compiler-v2] panic when instantiating the type of a node for a pattern during inlining
# 🐛 Bug

When compiling the following code:

```
    fun test_fold() {
        use std::vector;
        let v = vector[1];
        let accu = vector::fold(v, 0, |_, _| 0 );
        assert!(accu == 0 , 0)
    }
```

The compiler will panic with the message`thread 'move_stdlib_unit_tests' panicked at 'index out of bounds: the len is 1 but the index is 1', third_party/move/move-model/src/ty.rs:546:21`.  More concretely, the panic happens when [instantiate](https://github.com/aptos-labs/aptos-core/blob/f070c3612559ae4b317b70e0015f443a90d920ac/third_party/move/move-compiler-v2/src/inliner.rs#L1146) type of the node of a pattern with the type_args of the inliner.

### PR DESCRIPTION
**Pull request by rahxephon89**
### Description

close #11210 by implementing a non-recursive call version of rewrite_pattern in inliner.rs.

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/inliner.rs [hunk 1]
```diff
@@ -1140,6 +1140,14 @@ impl<'env, 'rewriter> ExpRewriterFunctions for InlinedRewriter<'env, 'rewriter>
         }
     }
 
+    fn internal_rewrite_pattern(&mut self, pat: &Pattern, entering_scope: bool) -> (bool, Pattern) {
```
Comment (wrwg) [inline third_party/move/move-compiler-v2/src/inliner.rs:1143]: I don't understand this. The internal_ functions are supposed to be not overriden, thats why the are called internal. Also this kind of deactivates recursive rewriting.

Is it perhaps that we need to make rewrite_pattern non-recursive as we do the traversal now in the rewriter?

**Review by wrwg — APPROVED** [review]
