### PR TITLE
[prover] Enable dynamic dispatch in the prover

### LINKED ISSUE #19277: [prover] Missing support for stored function values in verification
## Summary

The Move Prover does not currently support verifying code that stores function values (closures) in resources and later calls them. The Boogie backend fails to generate correct memory label declarations when specs reference stored function values via behavioral predicates (`result_of`, `aborts_of`, `ensures_of`).

## Example

See `third_party/move/move-prover/tests/inference/calculator.exp.move` — a calculator that stores operations as `|u64|u64` closures in a `State::Continuation` variant. Spec inference produces correct-looking specs, but verification fails with Boogie compilation errors (undeclared memory label identifiers) because the backend doesn't handle the intermediate states needed for stored function value invocation.

## Expected behavior

Verification should succeed for code that stores and invokes function values in resources, provided specs are correct.

### PR DESCRIPTION
**Pull request by wrwg**
## Summary

Closes #19277

Enables the Move prover to verify programs that store function values in struct fields and invoke them dynamically. Example (`vault.move`):

```move
struct Strategy(|FungibleAsset|FungibleAsset) has store, copy;
spec Strategy {
    modifies_of<self.0> *;
    invariant forall input: FungibleAsset, result: FungibleAsset:
        ensures_of<self.0>(input, result) ==>
            fungible_asset::asset_metadata(result) == fungible_asset::asset_metadata(input) &&
            fungible_asset::amount(result) >= fungible_asset::amount(input);
}

struct Vault has key {
    store: Object<FungibleStore>,
    strategy: Strategy
}

public fun harvest(caller: &signer, vault_obj: Object<Vault>) {
    let vault = &mut Vault[vault_obj.object_address()];
    let balance = fungible_asset::balance(vault.store);
    let assets = fungible_asset::withdraw(caller, vault.store, balance);
    let returned_assets = (vault.strategy.0)(assets);
    fungible_asset::deposit(vault.store, returned_assets);
}

spec harvest {
    let store_addr = object::object_address(Vault[vault_obj.object_address()].store);
    ensures FungibleStore[store_addr].balance >= old(FungibleStore[store_addr].balance);
}
```

The prover infers full frame conditions for `harvest` (including abort conditions for each dynamically dispatched call) and verifies the postcondition that the vault's balance never decreases.

### Changes

**Dynamic dispatch for stored function values**
- Add `StructFieldInfo` Boogie datatype variant for behavioral predicates on function-typed struct fields
- Struct-level `modifies_of`/`reads_of` declarations (stored on `StructData`) with memory effect derivation and validation
- `modifies_of<f> *` / `reads_of<f> *` wildcard support via `FrameSpec` flags
- Fix `reads_all` wildcard incorrectly skipping modification validation — `reads_of<f> *` now only subsumes read checks, not write checks
- Fix frame conditions in `$apply` for pure closures: unmentioned memory types now preserved instead of unconstrained after havoc
- Fix opaque call `SaveMem` ordering: memory saves execute before label defines

**Expression targets in behavioral predicates**
- `ensures_of<target>(args)` now accepts arbitrary expressions in `<...>`, not just identifiers — e.g. `ensures_of<vault.strategy.0>(input, result)` works directly without a `let` workaround
- Parser uses `parse_dot_or_index_chain` for the target, supporting field access chains, index expressions, qualified names
- Sourcifier no longer emits `let` bindings for non-simple targets — inferred specs are more readable
- Fix `translate_name` to error on type arguments for local variables (was silently ignored)

**Spec inference improvements**
- Calculator and vault inference tests now verify successfully
- Inferred specs use inline expression targets instead of `let` workarounds

**Other fixes**
- Sourcifier: `is_state_neutral` prevents label hoisting over unlabeled globals, let-extraction preserves label scoping
- Inliner tolerates lambda lifting failures by falling back instead of asserting
- Closure `new_unique_name` now checks `temp_names` to prevent lambda parameter shadowing

## Test plan

- [x] Vault inference test: `Verification: Succeeded.`
- [x] Calculator inference test: `Verification: Succeeded.`
- [x] All 13 inference tests pass
- [x] All 215 prover tests pass (including new `stored_fun_values` and `stored_fun_access_errors`)
- [x] All 2216 compiler tests pass
- [x] `closure_non_provable` baseline updated: false positive removed

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>

---

> [!NOTE]
> **Medium Risk**
> Updates the Move compiler/model pipeline in spec parsing, typing, and memory-effect validation to support dynamic dispatch and wildcards, which can affect prover soundness and introduce new validation failures.
> 
> **Overview**
> Enables dynamic dispatch in specifications by letting behavior predicates (`requires_of`/`ensures_of`/etc.) target **any function-typed expression** (not just named functions with optional type args), and adjusts diagnostics and state-label propagation accordingly.
> 
> Extends `modifies_of`/`reads_of` with `*` wildcards and `self.N` field selectors, and allows these declarations in **struct spec blocks** to constrain function-typed fields. The env/spec pipeline now derives and stores field access memory, and validates closure values stored into fields (via struct `pack` and field `mutate`) against declared access bounds.
> 
> Improves robustness and test expectations: the inliner no longer asserts on failed lambda lifting, wildcard semantics distinguish read vs write (`reads_of *` does not permit writes), and many golden tests are updated for new lambda parameter naming and revised error locations/messages.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit e14a49c80ae8197e467529066a99207595776331. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by wrwg** [comment]
* **#19379** <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/19379?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/aptos-labs/aptos-core/19379?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by wrwg** [comment]
**[Claude Agent]** Addressed review feedback:

1. **CI clippy fix**: Merged identical `if_same_then_else` branches in `derive_struct_field_frame_access` (line 6795)
2. **Cursor Bugbot — lambda param shadowing**: `new_unique_name` now also collects `Temporary` display names (via `self.temp_names`) when computing the used-name set, preventing lambda parameter names from shadowing captured temporaries

File: third_party/move/move-model/src/sourcifier.rs [hunk 1]
```diff
@@ -2092,7 +2110,15 @@ impl<'a> ExpSourcifier<'a> {
...
-                        let name = self.new_unique_name(args, &format!("arg{}", i));
+                        let base = Self::PARAM_NAMES[i % Self::PARAM_NAMES.len()];
+                        // Include already-chosen lambda params in the scope to avoid
+                        // duplicate names when there are more params than PARAM_NAMES.
+                        let scope: Vec<Exp> = args
+                            .iter()
+                            .cloned()
+                            .chain(lambda_param_exps.iter().cloned())
+                            .collect();
+                        let name = self.new_unique_name(&scope, base);
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/sourcifier.rs:2117]: **[Claude Agent]** Already fixed in a previous commit.

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs [hunk 2]
```diff
@@ -713,6 +736,101 @@ fn validate_closure_access_of_compliance(env: &GlobalEnv) {
...
+                                    used_memory: BTreeSet::new(),
+                                    old_memory: BTreeSet::new(),
+                                };
+                                &empty_access
+                            },
+                        };
+                        // Wildcard declarations subsume everything
+                        if access.frame_spec.modifies_all || access.frame_spec.reads_all {
+                            continue;
+                        }
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs]: **[Claude Agent]** Valid issue — fixed. When `reads_all` is true but `modifies_all` is false, modification checks were incorrectly skipped. Now only `modifies_all` causes a full skip; `reads_all` only subsumes read checks. Added a test case in `stored_fun_access_errors.move` that stores a modifying function into a `reads_of *` struct and verifies the expected error.

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs [hunk 3]
```diff
@@ -713,6 +736,101 @@ fn validate_closure_access_of_compliance(env: &GlobalEnv) {
...
+                    struct_env.get_field_access_of().to_vec()
+                };
+                if !field_access.is_empty() {
+                    let struct_env = env.get_struct(struct_qid);
+                    let fields: Vec<_> = struct_env.get_fields().collect();
+                    for (arg_idx, arg) in args.iter().enumerate() {
+                        if arg_idx >= fields.len() {
+                            continue;
+                        }
+                        let field = &fields[arg_idx];
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs:842]: **[Claude Agent]** False positive — `get_fields()` explicitly sorts by the `offset` field (declaration order), not by BTreeMap key order. See `get_fields_optional_variant()` in `model.rs` which uses `.sorted_by_key(|data| data.offset)`.

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 4]
```diff
@@ -6140,7 +6144,11 @@ impl ExpTranslator<'_, '_, '_> {
                         let expected_types =
                             self.compute_behavior_arg_types(arg_ty, result_ty, kind);
                         let id = self.new_node_id_with_type_loc(&ty, loc);
-                        let fun_exp = if let Some(temp_idx) = temp_index {
+                        let fun_exp = if let Some(oper) = operation {
+                            // For struct field locals, use the associated Select operation
+                            // with empty args (will be rewritten by data invariant instrumenter)
+                            ExpData::Call(id, oper, vec![]).into_exp()
+                        } else if let Some(temp_idx) = temp_index {
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs]: **[Claude Agent]** False positive — result variables in `ensures` conditions are intentionally defined with `operation = Some(Operation::Result(i))` (see `module_builder.rs:2699-2705`). Generating `ExpData::Call(id, Operation::Result(0), vec![])` is the correct semantic representation for function return values used as behavior predicate targets. This is new code with no prior behavior to break.

File: third_party/move/move-prover/tests/sources/functional/inline-lambda.exp [hunk 5]
```diff
@@ -1,232 +1,30 @@
...
-   =     at tests/sources/functional/inline-lambda.move:32: inline_1
-
-error: unknown assertion failed
-   ┌─ tests/sources/functional/inline-lambda.move:32:13
-   │
-32 │             assert w == e(x); // e is translated into an uninterpreted spec fun
-   │             ^^^^^^^^^^^^^^^^^
+Move prover returns: exiting with condition generation errors
+error: imperative expressions not supported in specs
+   ┌─ tests/sources/functional/inline-lambda.move:39:47
```
Comment (rahxephon89) [inline third_party/move/move-prover/tests/sources/functional/inline-lambda.exp:3]: Is this intended?

Comment (wrwg) [reply third_party/move/move-prover/tests/sources/functional/inline-lambda.exp:3]: Yes -- that is why I added the commennt to the error message.

It was hidden before since the prover was running its tests still in v1 compiler mode, where inline functions are lambda-lifted in specs and not inlined. I needed to turn this off for other reasons, and now we see this because the while is unfolded into a spec expression.

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs]: Fixed

**Review by rahxephon89 — APPROVED** [review]

File: third_party/move/move-compiler-v2/legacy-move-compiler/src/parser/syntax.rs [hunk 6]
```diff
@@ -4624,10 +4637,26 @@ fn parse_modifies_of(context: &mut Context) -> Result<SpecBlockMember, Box<Diagn
     let start_loc = context.tokens.start_loc();
     // consume "modifies_of"
     consume_token(context.tokens, Tok::Identifier)?;
-    // "<" Identifier ">"
+    // "<" Identifier | self.N ">"
     consume_token(context.tokens, Tok::Less)?;
-    let fun_param = parse_identifier(context)?;
+    let fun_param = parse_identifier_or_self_field(context)?;
     consume_token(context.tokens, Tok::Greater)?;
+    // Check for wildcard: "modifies_of<f> *;"
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/legacy-move-compiler/src/parser/syntax.rs]: this and the other check for wildcard code are near identical: would be worth abstracting into a helper.

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs [hunk 7]
```diff
@@ -713,6 +736,106 @@ fn validate_closure_access_of_compliance(env: &GlobalEnv) {
         };
 
         body.visit_post_order(&mut |exp| {
+            // Check struct pack operations: when a closure is stored into a struct
+            // field with reads_of/modifies_of declarations, validate compliance.
+            if let ExpData::Call(call_id, Operation::Pack(mid, sid, _), args) = exp {
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs]: this compliance validation is only done at pack/call sites, but not when function-valued field is later overwritten. Is this sound?

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs [hunk 8]
```diff
@@ -713,6 +736,106 @@ fn validate_closure_access_of_compliance(env: &GlobalEnv) {
...
+                let struct_qid = mid.qualified(*sid);
+                let field_access = {
+                    let struct_env = env.get_struct(struct_qid);
+                    struct_env.get_field_access_of().to_vec()
+                };
+                if !field_access.is_empty() {
+                    let struct_env = env.get_struct(struct_qid);
+                    let fields: Vec<_> = struct_env.get_fields().collect();
```
Comment (vineethk) [inline third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs]: Is going through all fields of all variants the right behavior here (given that we are packing a specific variant, if it an enum)?

**Review by vineethk — APPROVED** [review]
Approving assuming comments are addressed.

File: third_party/move/move-model/src/ast.rs [hunk 9]
```diff
@@ -1264,6 +1268,35 @@ impl ExpData {
...
+                Operation::Behavior(_, range)
+                | Operation::SpecPublish(range)
+                | Operation::SpecRemove(range)
+                | Operation::SpecUpdate(range),
+                _,
+            ) if range.pre.is_some() || range.post.is_some() => {
+                neutral = false;
+                false
+            },
+            _ => neutral,
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/ast.rs:1296]: **[Claude Agent]** Fixed — added `Operation::SpecFunction(_, _, range)` to the `is_state_neutral` or-pattern so labeled spec function calls are correctly treated as state-dependent. All 215 prover tests pass.

File: third_party/move/move-compiler-v2/legacy-move-compiler/src/parser/syntax.rs (hunk 6 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/legacy-move-compiler/src/parser/syntax.rs]: **[Claude Agent]** Good point — extracted a shared `parse_access_of_header` helper that parses the common prefix (`keyword<param>`) and wildcard (`*;`) check. Both `parse_modifies_of` and `parse_reads_of` now call this helper.

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs (hunk 8 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs]: **[Claude Agent]** Good catch — `get_fields()` returns all fields across all variants. Fixed to use `get_fields_optional_variant(variant)` where `variant` comes from the `Pack` operation's third field (previously discarded with `_`).

File: third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs (hunk 7 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs]: **[Claude Agent]** Good catch — it was not sound. Field mutation via `s.field = new_closure` (desugared to `Mutate(Select(...),...)`) bypassed the compliance check. Added a `Mutate` case that validates the RHS against the field's `reads_of`/`modifies_of` declarations, using the same logic (now extracted into a shared `validate_field_access` helper to avoid duplication with the Pack case).

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 10]
```diff
@@ -5970,9 +5991,17 @@ impl ExpTranslator<'_, '_, '_> {
...
+                    // (inner) StateLabeled propagation set it — treat as a
+                    // barrier and don't merge with the outer range.  Only
+                    // label-free Behaviors inherit the enclosing range.
+                    let merged = if existing_range.pre.is_some() || existing_range.post.is_some() {
+                        existing_range.clone()
+                    } else {
+                        MemoryRange {
+                            pre: self.range.pre,
+                            post: self.range.post,
+                        }
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs:6004]: **[Claude Agent]** False positive. The barrier logic is intentional and correct. Per-field merge (`existing.or(outer)`) was tested and breaks inference tests (`state_labels.move`, `vault.move`) — it leaks outer labels into inner state contexts, creating invalid label combinations (e.g., identical pre/post labels producing single-state notation `S |~` where two-state is required, and cyclic label references). The barrier ensures that once an inner `StateLabeled` has set any label on an operation, the outer propagation leaves that operation's range intact rather than merging in labels from a different state context.
