### PR TITLE
[compiler v2] Fix equalities, FreezeRef conversion

### LINKED ISSUE #11434: [Bug][Compiler-v2] Cannot check equality between mutable and immutable reference
# 🐛 Bug

After landing the PR #11371, the compiler V2 will generate an error when trying to check equality between mutable and immutable reference. For instance, for the following function:

```
 fun t0(s: S, s_ref: &S) {
    (&mut s == s_ref: bool);
}
```

The compiler will generate the error:

```
Diagnostics:
error: invalid call of `==`: mutability mismatch (&mut != &) for argument 2
   ┌─ tests/checking/typing/eq.move:18:20
   │
18 │         (&mut s == s_ref: bool);
   │                    ^^^^^
```

### LINKED ISSUE #11738: [Bug][Compiler-v2]  mutability mismatch of reference (&mut != &) in equality expression
# 🐛 Bug

When compiling the following code:

```
    fun t3(): bool {
        let x = 5;
        let y = 7;
        &mut x == &y
    }
```

The following error will be generated:

```
+ error: invalid call of `==`: mutability mismatch (&mut != &) for argument 2
+    ┌─ tests/checking/typing/mutable_eq_and_neq.move:43:19
+    │
+ 43 │         &mut x == &y
+    │                   ^^
```

Same issues happens when compiling experimental package in third_party/move/documentation/examples/diem-framework/move-packages/experimental using V2:

```
    ┌─ /Users/tengzhang/aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/experimental/../core/sources/configs/DiemSystem.move:286:27
    │
286 │         if (config_ref == &new_validator_config) {
    │                           ^^^^^^^^^^^^^^^^^^^^^
```

### LINKED ISSUE #12151: [Bug][compiler v2] Bytecode verifier error on mut ref equality check
# 🐛 Bug

The following code successfully compiles with v1, but has a bytecode verifier error in v2 (when run with code in this branch, in a transactional test):

```
module 0xc0ffee::m {
    fun test(): bool {
        let x = 1;
        let r1 = &mut x;
        let r2 = &mut x;
        r1 == r2
    }
}
```

This issue is applicable after landing https://github.com/aptos-labs/aptos-core/pull/11892, with the original discussion here: https://github.com/aptos-labs/aptos-core/pull/11892#issuecomment-1957207608

### PR DESCRIPTION
**Pull request by wrwg**
This enables the comparison of references with mixed mutability (`&x == &mut y`), and introduces generation of the `FreezeRef` operation when an argument is widned from mutable to immutable references. The later applies for any kind of function call, not only equalities. Without freeze, certain scenarios produce borrow errors in reference safety and/or the bytecode verifier.

Note that this PR is intended to work together with the new reference safety analysis, so some tests do not yet work without it.

Fixes #12151
Fixes #11738
Fixes #11434

### CODE REVIEW

File: third_party/move/move-model/src/builder/exp_builder.rs [hunk 1]
```diff
@@ -2672,6 +2672,7 @@ impl<'env, 'translator, 'module_translator> ExpTranslator<'env, 'translator, 'mo
             }
             let mut success = true;
             for (i, arg_ty) in arg_types.iter().enumerate() {
+                /*
```
Comment (vineethk) [inline third_party/move/move-model/src/builder/exp_builder.rs:2675]: Delete commented out code?

**Review by vineethk — APPROVED** [review]
LGTM, assuming the commented out code is taken care of.

**Review by rahxephon89 — APPROVED** [review]
LGTM, thanks!

File: third_party/move/move-compiler-v2/tests/checking/typing/eq_invalid.exp [hunk 2]
```diff
@@ -1,55 +1,79 @@
...
-error: invalid call of `==`: expected `u8` but found `u128` for argument 2
-   ┌─ tests/checking/typing/eq_invalid.move:13:21
+error: no matching declaration of `==`
+   ┌─ tests/checking/typing/eq_invalid.move:13:9
    │
 13 │         (0: u8) == (1: u128);
-   │                     ^
+   │         ^^^^^^^^^^^^^^^^^^^^
+   │
+   = outruled candidate `==(&#0, &#0): bool` (expected `&?3` but found `u8` for argument 1)
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/typing/eq_invalid.exp:9]: https://github.com/aptos-labs/aptos-core/issues/12234

File: third_party/move/move-compiler-v2/tests/checking/typing/neq_invalid.exp [hunk 3]
```diff
@@ -1,67 +1,91 @@
...
-error: invalid call of `!=`: expected `u8` but found `u128` for argument 2
-   ┌─ tests/checking/typing/neq_invalid.move:13:21
+error: no matching declaration of `!=`
+   ┌─ tests/checking/typing/neq_invalid.move:13:9
    │
 13 │         (0: u8) != (1: u128);
-   │                     ^
+   │         ^^^^^^^^^^^^^^^^^^^^
+   │
+   = outruled candidate `!=(&#0, &#0): bool` (expected `&?3` but found `u8` for argument 1)
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/checking/typing/neq_invalid.exp:9]: See bug above

File: third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_mutual_borrows_invalid.exp [hunk 4]
```diff
@@ -1,21 +1,5 @@
 
 Diagnostics:
-error: cannot copy mutable reference in local `s1` which is still borrowed
-   ┌─ tests/reference-safety/v1-tests/call_mutual_borrows_invalid.move:15:9
-   │
-14 │         let f = freeze(s1);
-   │                 ---------- previous call result
-15 │         mut_imm(s1, f);
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_mutual_borrows_invalid.exp:8]: What is the problem? The error is legit.

File: third_party/move/move-model/src/builder/exp_builder.rs (hunk 1 above)
Comment (wrwg) [reply third_party/move/move-model/src/builder/exp_builder.rs:2675]: Done

File: third_party/move/move-compiler-v2/tests/reference-safety/eq_ref.exp [hunk 5]
```diff
@@ -0,0 +1,9 @@
+
+Diagnostics:
+error: cannot mutably borrow local `x` since other references exists
+   ┌─ tests/reference-safety/eq_ref.move:16:19
+   │
+16 │         &mut x == &mut x; // error expected, will be fixed with new reference safety
```
[the remark this answers is not in the document]
Comment (wrwg) [reply third_party/move/move-compiler-v2/tests/reference-safety/eq_ref.exp]: Actually no error expected here since both args are frozen and then it is allowed.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs [hunk 6]
```diff
@@ -1010,7 +1009,15 @@ impl<'env, 'state> LifetimeAnalysisStep<'env, 'state> {
     ///
     /// If we walk this graph now from the root to the leaves, we can determine safety by directly comparing
     /// hyper edge siblings.
-    fn check_borrow_safety(&mut self, temps: &BTreeSet<TempIndex>) {
+    fn check_borrow_safety(&mut self, temps_vec: &[TempIndex]) {
+        // First check direct duplicates
+        for (i, temp) in temps_vec.iter().enumerate() {
```
Comment (brmataptos) [inline third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1014]: You could probably do something like:
```
let temps = BTreeSet<_>::new();
for temp in temps_vec.iter().rev() {
    if temps.contains(temp) {
        self.exclusive_access_direct_dup_error(temp.clone())
   } else {
        temps.insert(temp.clone());
   }
}
```
and reduce this from `O(N^2)` to `O(N log N)` or so.

Or we can save that for later optimization if needed.

**Review by brmataptos — APPROVED** [review]
Looks good.  See one potential loop optimization.

File: third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs (hunk 6 above)
Comment (wrwg) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1014]: Sorry I saw only after merge.

I'm certain there is a non-quadratic version, but I can't quite see what you mean,  this seems to generate an error for every iteration?

Comment (brmataptos) [reply third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs:1014]: No, only if we've already seen `temp` does it yield an error.  And we're processing `iter().rev()` so it's going backwards over the vec just as before.  Though actually, now that I think about it, that might not matter unless we are showing the location.
