### PR TITLE
[compiler-v2] Add type information to cons_to_idx

### LINKED ISSUE #13201: [Bug][Compiler-v2] incorrect type of an empty vector constant leads to STLOC_TYPE_MISMATCH_ERROR
# 🐛 Bug

When compiling the following code:

```
module 0x42::m {
    use std::bcs;
    use std::string::{Self};
    use std::vector;

    const KEYS: vector<vector<u8>> = vector[];
    const VALUES: vector<u64> = vector[];

    public entry fun init(
    ) {
        let _ = vector::map(KEYS, |key|{ string::utf8(key)});
        let _ = vector::map(VALUES, |v|{ bcs::to_bytes<u64>(&v)});
    }
}
```

The following error will be generated:

```
    ┌─ /aptos-core/third_party/move/move-compiler-v2/../move-stdlib/sources/vector.move:161:23
    │
161 │     public inline fun for_each<Element>(v: vector<Element>, f: |Element|) {
    │                       ^^^^^^^^ ICE failed bytecode verifier: VMError {
    major_status: STLOC_TYPE_MISMATCH_ERROR,
    sub_status: None,
    message: None,
    exec_state: None,
    location: Module(
        ModuleId {
            address: 0000000000000000000000000000000000000000000000000000000000000042,
            name: Identifier(
                "m",
            ),
        },
    ),
    indices: [
        (
            FunctionDefinition,
            0,
        ),
    ],
    offsets: [
        (
            FunctionDefinitionIndex(0),
            29,
        ),
    ],
}
```

However the error will not be generated if `KEYS` is replaced by `vector[]` in the code. Also, although the error is triggered by the second let statement but if the first let statement is remove, there will be no error.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR fixes #13201 by attaching the type information to cons_to_idx to make sure different ConstantPoolIndex will be generated when there are multiple constants which have the same value but different types. For instance in the following code, both KEYS and VALUES are empty vectors but one is of type `vector<vector<u8>>` and the other is of type `vector<u64>`.

```
module 0x42::m {
    use std::bcs;
    use std::string::{Self};
    use std::vector;

    const KEYS: vector<vector<u8>> = vector[];
    const VALUES: vector<u64> = vector[];

    public entry fun init(
    ) {
        let _ = vector::map(KEYS, |key|{ string::utf8(key)});
        let _ = vector::map(VALUES, |v|{ bcs::to_bytes<u64>(&v)});
    }
}
```

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

PR #13205 already added test cases. Only need to make sure existing tests still pass. 

## Key Areas to Review

Some changes in #13205  are reverted. Need to make sure it is OK to do so.

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs [hunk 1]
```diff
@@ -75,8 +75,8 @@ pub struct ModuleGenerator {
         BTreeMap<(QualifiedId<StructId>, usize, FF::SignatureIndex), FF::FieldInstantiationIndex>,
     /// A mapping from type sequences to signature indices.
     types_to_signature: BTreeMap<Vec<Type>, FF::SignatureIndex>,
-    /// A mapping from constants sequences to pool indices.
-    cons_to_idx: BTreeMap<Constant, FF::ConstantPoolIndex>,
+    /// A mapping from constants sequences (with the corresponding type information) to pool indices.
+    cons_to_idx: BTreeMap<(Constant, Type), FF::ConstantPoolIndex>,
```
Comment (rahxephon89) [inline third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs:79]: Use (constant, type) so that constants having the same value but with different types have different constant pool index.

**Review by brmataptos — APPROVED** [review]
Looks good but maybe keep the entirely empty vector case for the gas savings.

**Review by brmataptos — APPROVED** [review]
